/**
 * admin
 */
var hakwonTmpl = {
	/*	공통	*/
	common : {
		/*	초기화	*/
		init : [
			'	<div class="sk-spinner sk-spinner-wave">'
			, '		<div class="sk-rect1"></div>'
			, '		<div class="sk-rect2"></div>'
			, '		<div class="sk-rect3"></div>'
			, '		<div class="sk-rect4"></div>'
			, '		<div class="sk-rect5"></div>'
			, '	</div>'
		].join('')
		, main : [
			'메인 화면 입니다.'
		].join('')
		, pageNav : [
 			'{{if pageList.length === 0 }}'
			, '	<button type="button" class="btn btn-white active">1</button>'
			, '{{/if}}'
			, '{{if pageList.length > 0 }}'
			, '		<button type="button" data-act="left" class="btn btn-white"><i class="fa fa-chevron-left"></i></button>'
			, '	{{each(i, loopPage) pageList}}'
			, '		<button type="button" class="btn btn-white {{= (currentPageNo==loopPage.pageNo)?"active":""}}">{{= loopPage.pageNo}}</button>'
			, '	{{/each}}'
			, '		<button type="button" data-act="right" class="btn btn-white"><i class="fa fa-chevron-right"></i> </button>'
			, '{{/if}}'
		].join('')
		, commNaviMenu : [
			'<h1>광고 리스트</h1>'
			, '<ol class="breadcrumb">'
			, '	<li>'
			, '		<a href="#">홈</a>'
			, '	</li>'
			, '	<li class="active">'
			, '		<strong>광고 리스트</strong>'
			, '	</li>'
			, '</ol>'
		].join('')
		/*	로그인	*/
		, login : [
			'	<div class="middle-box text-center loginscreen animated fadeInDown">'
			, '		<h1 class="logo-name"><small>HAKWONBAND</small><br>LOGIN</h1>'
			, '		<h3>Welcome to HAKWONBAND</h3>'
			, '		<form class="m-t" role="form" action="">'
			, '			<div class="form-group">'
			, '				<input type="text" name="userId" value="" class="form-control m-b-xs" placeholder="아이디">'
			, '				<input type="password" name="userPass" value="" class="form-control" placeholder="비밀번호">'
			, '				<div class="checkbox i-checks">'
			, '					<label for="login_auto"> <input type="checkbox" name="loginSave" value="Y" id="login_auto"> 자동로그인</label>'
			, '					<label for="login_rememberid"> <input type="checkbox" name="idSave" value="Y" id="login_rememberid"> 아이디 기억</label>'
			, '				</div>'
			, '			</div>'
			, '			<button type="button" ng-click="login()" data-act="login" class="btn btn-primary btn-lg block full-width m-b">로그인</button>'
			, '		</form>'
			, '		<p class="m-t"> <small>HAKWONBAND &copy; 2015</small> </p>'
			, '	</div>'
		].join('')
		/*	비어 있는 대시 보드 영역	*/
		, emptyDashBoard : [
			'<div class="middle-box text-center animated fadeInRightBig">'
			, '	<h3 class="font-bold" ng-click="debugOn()">준비 중 입니다.</h3>'
			, '	<div ng-if="isDebug === true">'
			, '		<div>브라우저 정보 : {{browserVal}}</div><br />'
			, '		<div>사용자 정보 : {{userAuthVal}}</div><br />'
			, '		<button type="button" ng-click="getMobileAuthKey()">인증키 재 요청</button><br />'
			, '		<button type="button" ng-click="getTestMessage()">테스트 메시지 요청</button><br />'
			, '	</div>'
			, '</div>'
		].join('')
		/*	대시 보드 영역	*/
		, dashBoard : [
			'<div class="middle-box text-center animated fadeInRightBig">'
			, '	<h3 class="font-bold">준비 중 입니다.</h3>'
			, '</div>'
		].join('')
	}
};

/*	left 영역	*/
hakwonTmpl.leftMenu = {
	/*	사용자 프로필	*/
	userProfile : [
		'	<img alt="image" class="img-circle" src="{{= userAuth.profilePath}}" width="100px">'
		, '	<span class="block m-t-xs m-b text-white"> <strong class="font-bold">{{= userAuth.userName}}</strong> / {{= userAuth.userId}}</span>'
	].join('')
};

/*	광고	*/
hakwonTmpl.advertise = {
	/*	입금 관리	*/
	bankDeposit : {
		list : [
			'<div class="col-md-2 col-md-offset-2">'
			, '	<select class="form-control" name="mappingFlag">'
			, '		<option value="">맵핑여부</option>'
			, '		<option value="Y">Y</option>'
			, '		<option value="N">N</option>'
			, '	</select>'
			, '</div>'
			, '<div class="col-md-2">'
			, '	<select name="searchType" class="form-control">'
			, '		<option value="">검색 조건</option>'
			, '		<option value="depositName">입금자명</option>'
			, '	</select>'
			, '</div>'
			, '<div class="col-md-4 input-group">'
			, '	<input type="text" name="searchText" class="form-control" placeholder="검색어 입력">'
			, '	<span class="input-group-btn"> <button type="button" ng-click="search()" class="btn btn-primary">검색</button> </span>'
			, '</div>'
			, '<div class="ibox m m-t-xl">'
			, '	<div class="ibox-content" data-view="data-div">'
			, '		<table class="table table-hover table_link">'
			, '			<thead>'
			, '				<tr>'
			, '					<th>입금자명</th>'
			, '					<th>입금금액(원)</th>'
			, '					<th>입금일</th>'
			, '					<th>등록자</th>'
			, '					<th>광고 제목</th>'
			, '					<th>광고맵핑여부</th>'
			, '				</tr>'
			, '			</thead>'
			, '			<tbody></tbody>'
			, '		</table>'
			, '		<div class="text-right">'
			, '			<a href="'+PageUrl.edvertise.bankDepositWrite+'" class="btn btn-primary">입금정보 등록</a>'
			, '		</div>'
			, '	</div>'
			, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
			, '</div>'
		].join('')
		, list_row : [
			'{{each(i, loopBankDeposit) bankDepositList}}'
			, '<tr data-act="view" data-no="{{= loopBankDeposit.deposit_no}}" style="cursor:hand; cursor:pointer;">'
			, '	<td><span>{{= loopBankDeposit.deposit_name}}</span></td>'
			, '	<td><span>{{= commProto.numberWithCommas(loopBankDeposit.amount)}}</span></td>'
			, '	<td><span>{{= loopBankDeposit.deposit_date}}</span></td>'
			, '	<td><span>{{= loopBankDeposit.reg_user_name}}</span></td>'
			, '	<td><span>{{= loopBankDeposit.advertise_title}}</span></td>'
			, '	<td><span class="tooltip-demo"><button type="button" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="right" title="{{= loopBankDeposit.advertise_title}}">{{= loopBankDeposit.advertise_req_no?"Y":"N"}}</button></span></td>'
			, '</tr>'
			, '{{/each}}'
		].join('')
		, list_nodata : [
			'<tr>'
			, '	<td class="text-center" style="padding:200px 0 !important;">등록된 입금정보가 없습니다</td>'
			, '</tr>'
		].join('')
		, viewForm : [
			'<div class="ibox m" data-view="data-view"></div>'
		].join('')
		, viewData : [
			, '	<div class="ibox-title" data-money="{{= bankDepositInfo.amount}}">'
			, '		<h2>{{= bankDepositInfo.deposit_name}} {{= bankDepositInfo.hakwon_name?" - "+bankDepositInfo.hakwon_name:""}} {{= bankDepositInfo.advertise_title?" - "+bankDepositInfo.advertise_title:""}}</h2>'
			, '	</div>'
			, '	<div class="ibox-content ad_view">'
			, '		<h3 class="text_title">입금 정보</h3>'
			, '		<table class="table table-bordered table_center m-b-xl" summary="입금관련 정보를 나타내는 표 입니다">'
			, '			<thead>'
			, '				<tr>'
			, '					<th>입금자명</th>'
			, '					<th>입금액</th>'
			, '					<th>은행명</th>'
			, '					<th>입금일</th>'
			, '					<th>등록자</th>'
			, '					<th>등록일</th>'
			, '				</tr>'
			, '			</thead>'
			, '			<tbody>'
			, '				<tr>'
			, '					<td>{{= bankDepositInfo.deposit_name}}</td>'
			, '					<td>{{= commProto.numberWithCommas(bankDepositInfo.amount)}}</td>'
			, '					<td>{{= bankDepositInfo.bank_name}}</td>'
			, '					<td>{{= bankDepositInfo.deposit_date}}</td>'
			, '					<td>{{= bankDepositInfo.reg_user_name}}</td>'
			, '					<td>{{= bankDepositInfo.reg_date}}</td>'
			, '				</tr>'
			, '			</tbody>'
			, '		</table>'

			, '		<h3 class="text_title">광고정보</h3>'
			, '		{{if isNull(bankDepositInfo.advertise_req_no) }}'
			, '		<!-- 광고 맵핑정보 없을때 시작 -->'
			, '		<div class="alert alert-danger text-center">맵핑된 광고정보가 없습니다. 광고를 검색해 주세요.</div>'
			, '		<!-- 광고 맵핑정보 없을때 끝 -->'
			, '		<h3 class="text_title">광고검색후 맵핑하기</h3>'
			, '		<div class="panel panel-default">'
			, '			<div class="panel-heading">'
			, '				<i class="fa fa-info-circle"></i> 광고 검색'
			, '			</div>'
			, '			<div class="panel-body">'
			, '				<div class="col-md-6 col-md-offset-3 input-group m-t">'
			, '					<input type="text" name="advertiseSearchText" class="form-control" placeholder="광고명, 학원명, 원장명 검색">'
			, '					<span class="input-group-btn"> <button type="button" data-act="advertiseSearch" class="btn btn-primary">검색</button> </span>'
			, '				</div>'
			, '				<div class="col-md-6 col-md-offset-3 feed-activity-list m-t-xl search_result" data-view="advertise_search_view">'
			, '				</div>'
			, '			</div>'
			, '		</div>'
			, '		{{/if}}'

			, '		{{if isNull(bankDepositInfo.advertise_req_no) == false }}'
			, '		<table data-mapping="Y" class="table table-bordered table_center m-b-xl" summary="입금한 광고의 광고정보를 나타내는 표 입니다">'
			, '			<thead>'
			, '				<tr>'
			, '					<th>학원명</th>'
			, '					<th>광고제목</th>'
			, '					<th>원장</th>'
			, '					<th>광고 삭제</th>'
			, '				</tr>'
			, '			</thead>'
			, '			<tbody>'
			, '				<tr>'
			, '					<td>{{= bankDepositInfo.hakwon_name}}</td>'
			, '					<td><a href="'+PageUrl.edvertise.bannerView+'?reqNo={{= bankDepositInfo.advertise_req_no}}">{{= bankDepositInfo.advertise_title}}</a></td>'
			, '					<td>{{= bankDepositInfo.master_user_name}}</td>'
			, '					<td><button type="button" data-act="mappingDelete" value="{{= bankDepositInfo.advertise_req_no}}" class="btn btn-danger">삭제</button></td>'
			, '				</tr>'
			, '			</tbody>'
			, '		</table>'
			, '		{{/if}}'

			, '	</div>'
			, '	<div class="ibox-content text-right">'
			, '		<button type="button" data-act="list" class="btn btn-default" style="float:left;">목록으로</button>'
			, '		<button type="button" data-act="modify" class="btn btn-warning">수정하기</button>'
			, '		<button type="button" data-act="delete" class="btn btn-danger">삭제하기</button>'
			, '	</div>'
		].join('')
		, search_row : [
			'	<h4>검색결과</h4>'
			, '{{each(i, loopAdvertise) dataList}}'
			, '	<div class="feed-element">'
			, '		<a href="#" class="pull-left">'
			, '			<img alt="image" class="img-circle" src="{{= comm.hakwonLogoImg(loopAdvertise.hakwon_logo_path)}}">'
			, '		</a>'
			, '		<div class="media-body">'
			, '			<div class="pull-right"><button type="button" data-act="advertiseMapping" data-money="{{= loopAdvertise.pre_calc_price}}" value="{{= loopAdvertise.advertise_req_no}}" class="btn btn-primary btn-outline">선택</button></div>'
			, '			<strong>{{= loopAdvertise.hakwon_name}} / {{= loopAdvertise.master_user_name}}</strong><br><strong class="text-danger">입금 예정 금액 : {{= commProto.numberWithCommas(loopAdvertise.pre_calc_price)}}원</strong>'
			, '			광고제목 : {{= loopAdvertise.title}} ({{= loopAdvertise.reg_date}})'
			, '		</div>'
			, '	</div>'
			, '{{/each}}'
		].join('')
		, search_row_nodata : [
			'	<h4>검색결과</h4>'
			, '<div class="feed-element no_data">입력된 정보로 검색된 광고가 없습니다</div>'
		].join('')
		, editForm : [
			'<div class="ibox" data-view="data-view"></div>'
		].join('')
		, edit : [
			'	<div class="ibox-content form-horizontal">'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_01">입금자명</label>'
			, '			<div class="col-sm-10">'
			, '				<input type="text" maxLength="20" name="deposit_name" value="{{= bankDepositInfo.deposit_name}}" class="form-control" placeholder="입금자명을 입력하세요" id="ad_pay_01">'
			, '			</div>'
			, '		</div>'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_02">입금금액</label>'
			, '			<div class="col-sm-10">'
			, '				<input type="number" name="amount" value="{{= bankDepositInfo.amount}}" onkeydown="commProto.onlyNumber(event)" onkeypress="commProto.onlyNumber(event)" class="form-control" placeholder="입금액을 입력하세요" id="ad_pay_02">'
			, '			</div>'
			, '		</div>'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_03">은행명</label>'
			, '			<div class="col-sm-10">'
			, '				<select name="bank_code" data-value="{{= bankDepositInfo.bank_code}}" class="form-control">'
			, '					<option value="">은행 선택</option>'
			, '	{{each(i, loopBank) bankList}}'
			, '					<option value="{{= loopBank.code}}" {{= bankDepositInfo.bank_code==loopBank.code?"selected":""}}>{{= loopBank.code_name}}</option>'
			, '	{{/each}}'
			, '				</select>'
			, '			</div>'
			, '		</div>'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_04">입금일</label>'
			, '			<div class="col-sm-10">'
			, '				<input type="date" name="deposit_date" value="{{= bankDepositInfo.deposit_date}}" class="form-control" placeholder="입금일을 입력하세요" id="ad_pay_04">'
			, '			</div>'
			, '		</div>'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_05">기타 설명</label>'
			, '			<div class="col-sm-10">'
			, '				<textarea rows="10" cols="30" name="comment" class="form-control">{{= bankDepositInfo.comment}}</textarea>'
			, '			</div>'
			, '		</div>'
			, '		<div class="ibox-content text-right">'
			, '			<button type="button" data-act="cancel" class="btn btn-default">취소하기</button>'
			, '			<button type="button" data-act="edit" class="btn btn-primary">완료하기</button>'
			, '		</div>'
			, '	</div>'
		].join('')
		, write : [
			'<div class="ibox">'
			, '	<div class="ibox-content form-horizontal">'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_01">입금자명</label>'
			, '			<div class="col-sm-10">'
			, '				<input type="text" class="form-control" maxLength="20" name="deposit_name" placeholder="입금자명을 입력하세요" id="ad_pay_01">'
			, '			</div>'
			, '		</div>'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_02">입금금액</label>'
			, '			<div class="col-sm-10">'
			, '				<input type="number" class="form-control" name="amount" onkeydown="commProto.onlyNumber(event)" onkeypress="commProto.onlyNumber(event)" placeholder="입금액을 입력하세요" id="ad_pay_02">'
			, '			</div>'
			, '		</div>'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_03">은행명</label>'
			, '			<div class="col-sm-10">'
			, '				<select name="bank_code" class="form-control">'
			, '					<option value="">은행 선택</option>'
			, '				</select>'
			, '			</div>'
			, '		</div>'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_04">입금일</label>'
			, '			<div class="col-sm-10">'
			, '				<input type="date" name="deposit_date" class="form-control" placeholder="입금일을 입력하세요" id="ad_pay_04">'
			, '			</div>'
			, '		</div>'
			, '		<div class="form-group">'
			, '			<label class="col-sm-2 control-label" for="ad_pay_05">기타 설명</label>'
			, '			<div class="col-sm-10">'
			, '				<textarea rows="10" cols="30" name="comment" class="form-control"></textarea>'
			, '			</div>'
			, '		</div>'
			, '		<div class="ibox-content text-right">'
			, '			<button type="button" ng-click="cancel()" class="btn btn-default">취소하기</button>'
			, '			<button type="button" ng-click="regist()" class="btn btn-primary">등록하기</button>'
			, '		</div>'
			, '	</div>'
			, '</div>'
		].join('')
	}
};

hakwonTmpl.adBanner = {
	/*	광고 리스트	*/
	list : [
		'<div class="col-md-2 col-md-offset-3">'
		, '	<select name="depositYn" class="form-control">'
		, '		<option value="">결제 여부</option>'
		, '		<option value="Y">결제</option>'
		, '		<option value="N">미결제</option>'
		, '	</select>'
		, '</div>'
		, '<div class="col-md-4 input-group">'
		, '		<input type="text" name="searchText" class="form-control" placeholder="광고 제목으로 검색">'
		, '		<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '	</div>'
		, '	<div class="ibox m m-t-xl">'
		, '		<div class="ibox-content" data-view="data-div">'
		, '			<table class="table table-hover table_link">'
		, '				<thead>'
		, '					<tr>'
		, '						<th>번호</th>'
		, '						<th>제목</th>'
		, '						<th>학원명</th>'
		, '						<th>광고 사이즈</th>'
		, '						<th>결제여부</th>'
		, '						<th>취소여부</th>'
		, '						<th>관리자 중지</th>'
		, '						<th>광고노출여부</th>'
		, '					</tr>'
		, '				</thead>'
		, '				<tbody></tbody>'
		, '			</table>'
		, '			<div class="ibox-content text-center" style="padding:200px 0; display:none;">'
		, '				등록된 광고가 없습니다'
		, '			</div>'
		, '		</div>'
		, '		<div data-view="pagination" class="text-center m-b-xl m-t-xl"></div>'
		, '</div>'
	].join('')
	/*	리스트 로우	*/
	, listRow : [
		'{{each(i, loopAdvertiseInfo) advertiseReqList}}'
		, '<tr>'
		, '	<td><span>{{= loopAdvertiseInfo.advertise_req_no}}</span></td>'
		, '	<td><a href="#" data-req-no="{{= loopAdvertiseInfo.advertise_req_no}}" data-act="adBannerDetail">{{= loopAdvertiseInfo.title}}</a></td>'
		, '	<td><span>{{= loopAdvertiseInfo.hakwon_name}}</span></td>'
		, '	<td><span>{{= loopAdvertiseInfo.banner_size}}칸</span></td>'
		, '	<td><span>{{= loopAdvertiseInfo.deposit_yn=="Y"?"입금 완료":"입금 확인 중"}}</span></td>'
		, '	<td><span>-</span></td>'
		, '	<td><span>{{= loopAdvertiseInfo.stop_admin_yn}}</span></td>'
		, '	<td><span>{{= (loopAdvertiseInfo.view_count > 0 && loopAdvertiseInfo.deposit_yn == "Y" && loopAdvertiseInfo.stop_admin_yn == "N" )?"노출중":"" }}</span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	/*	리스트 로우 nodata	*/
	, listRowNoData : [
		'<div class="ibox-content text-center" style="padding:200px 0;">'
		, '	등록된 광고가 없습니다'
		, '</div>'
	].join('')
	/*	광고 상세	*/
	, view : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>{{ reqDetailInfo.title }}</h2>'
		, '	</div>'
		, '	<div class="ibox-content ad_view">'
		, '		<h3 class="text_title">광고 정보</h3>'
		, '		<table class="table table-bordered table_center" data-view="table-view" summary="광고의 크기, 결제여부, 취소여부를 나타내는 표 입니다">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>학원명</th>'
		, '					<th>광고 영역 크기</th>'
		, '					<th>결제여부</th>'
		, '					<th>광고금액</th>'
		, '					<th>시도 / 구군</th>'
		, '					<th>취소여부</th>'
		, '					<th>관리자 중지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '				<tr>'
		, '					<td><a href="'+PageUrl.hakwonDetail.classList+'?hakwon_no={{reqDetailInfo.hakwon_no}}">{{reqDetailInfo.hakwon_name}}</a></td>'
		, '					<td>{{reqDetailInfo.banner_size}}칸</td>'
		, '					<td>{{reqDetailInfo.deposit_yn=="Y"?"입금 완료":"미입금"}}</td>'
		, '					<td>{{CommUtil.numberWithCommas(reqDetailInfo.price)}}원</td>'
		, '					<td>{{reqDetailInfo.sido}} / {{reqDetailInfo.gugun}}</td>'
		, '					<td>{{reqDetailInfo.cancel_yn}}</td>'
		, '					<td>{{reqDetailInfo.stop_admin_yn}}</td>'
		, '				</tr>'
		, '			</tbody>'
		, '		</table>'

		, '		<h4 class="text_title">광고 이미지</h4>'
		, '		<img ng-src="{{reqDetailInfo.banner_web_path}}" class="ad_img" alt="광고 이미지">'

		, '		<h5 class="text_title">광고 현황 <small>현재 노출중 지역은 배경 컬러로 표시됩니다.</small></h5>'
		, '		<table summary="지역별 광고 기간 현황을 나타냅니다." class="table table-bordered  table_center">'
		, '			<thead>'
		, '				<tr>'
		, '					<td>동/읍/면</td>'
		, '					<td ng-repeat="loopViewMonth in viewMonthArray">{{CommUtil.yearMonthFormatter(loopViewMonth)}}</td>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '				<tr ng-repeat="loopLocalDongName in localDongNameArray">'
		, '					<td>{{loopLocalDongName}}</td>'
		, '					<td data-dong="{{loopLocalDongName}}" data-month="{{loopViewMonth}}" ng-repeat="loopViewMonth in viewMonthArray">'
		, '						<i style="display:none;" class="fa fa-check ad_check text-navy"></i>'
		, '					</td>'
		, '				</tr>'
		, '			</tbody>'
		, '		</table>'
		, '		<h4 class="text_title">광고 금액 정보</h4>'
		, '		<div class="table-responsive m-t">'
		, '			<table class="table invoice-table">'
		, '				<thead>'
		, '				<tr>'
		, '					<th>기간정보</th>'
		, '					<th>배너크기</th>'
		, '					<th>가격</th>'
		, '					<th>지역</th>'
		, '					<th>합계</th>'
		, '				</tr>'
		, '				</thead>'
		, '				<tbody>'
		, '				<tr ng-repeat="loopMonthPrice in monthPriceList">'
		, '					<td>{{CommUtil.yearMonthFormatter(loopMonthPrice.view_month)}}</td>'
		, '					<td>{{loopMonthPrice.banner_size}}칸</td>'
		, '					<td>{{CommUtil.numberWithCommas(loopMonthPrice.price)}}원</td>'
		, '					<td>{{loopMonthPrice.dong_count}}</td>'
		, '					<td>{{CommUtil.numberWithCommas(loopMonthPrice.total_price)}}</td>'
		, '				</tr>'
		, '				</tbody>'
		, '			</table>'
		, '		</div>'
		, '		<table class="table invoice-total">'
		, '			<tbody>'
		, '			<tr>'
		, '				<td><strong>합계 :</strong></td>'
		, '				<td>￦{{CommUtil.numberWithCommas(reqDetailInfo.price)}}</td>'
		, '			</tr>'
		, '			</tbody>'
		, '		</table>'
		, '		<div class="well m-t"><strong>입금계좌정보 : </strong>{{reqDetailInfo.bank_info}}</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" ng-click="goList()" style="float:left;">목록으로</button>'
		, '		<button type="button" data-type="stop" class="btn btn-primary" ng-click="stop()" style="float:right;">{{reqDetailInfo.stop_admin_yn=="Y"?"활성화":"중지"}}</button>'
		, '	</div>'
		, '</div>'
	].join('')
	/*	원별 가격 등록폼	*/
	, monthPrice : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>월별 가격 등록</h2>'
		, '	</div>'
		, '	<div class="ibox-content form-horizontal">'
		, '		<form>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">년도</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="row">'
		, '					<div class="col-md-3">'
		, '						<select name="year" class="form-control m-b">'
		, '						</select>'
		, '						<button type="button" data-act="save" class="btn btn-primary">저장</button>'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">광고기간</label>'
		, '			<div class="col-sm-11">'
		, '				<table class="table table-bordered table_center" data-type="calendar_table" summary="">'
		, '					<thead>'
		, '						<tr>'
		, '							<th>베너 크기</th>'
		, '						</tr>'
		, '					</thead>'
		, '					<tbody></tbody>'
		, '				</table>'
		, '			</div>'
		, '		</div>'
		, '		</form>'
		, '	</div>'
		, '</div>'
	].join('')
};

/*	학원	*/
hakwonTmpl.hakwon = {
	/*	학원 리스트	*/
	list : [
		'<div class="col-md-2 col-md-offset-3">'
		, '	<select name="searchSido" class="form-control" ng-model="searchSido" ng-change="sidoSelect()" ng-options="sidoVal for sidoVal in sidoArray track by sidoVal">'
		, '		<option value="">시도 전체</option>'
		, '	</select>'
		, '	<select name="searchGugun" class="form-control">'
		, '		<option value="">구군 전체</option>'
		, '	</select>'
		, '	<select name="adminRegYn" class="form-control" ng-change="adminRegYnChange()" ng-model="adminRegYn">'
		, '		<option value="">전체</option>'
		, '		<option value="N">정식 등록 학원</option>'
		, '		<option value="Y">관리자 등록 학원</option>'
		, '	</select>'
		, '	<select name="searchStatus" class="form-control" ng-change="statusChange()" ng-model="searchStatus">'
		, '		<option value="">상태</option>'
		, '		<option value="001">인증</option>'
		, '		<option value="002">미인증</option>'
		, '		<option value="003">원장님&선생님 접근 금지</option>'
		, '	</select>'
		, '	<select name="searchCateCode" class="form-control" ng-change="cateChange()" ng-model="searchCateCode" ng-options="hakwonCate.cateCode as hakwonCate.cateName for hakwonCate in hakwonCateList track by hakwonCate.cateCode">'
		, '		<option value="">카테고리</option>'
		, '	</select>'
		, '</div>'
		, '<div class="col-md-4 input-group">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="학원명 또는 원장명(아이디)">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>학원번호</th>'
		, '					<th>학원명</th>'
		, '					<th>지역</th>'
		, '					<th>업종</th>'
		, '					<th>원장명(아이디)</th>'
		, '					<th>학원 상태</th>'
		, '					<th>등록일</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody></tbody>'
		, '		</table>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="adminHakwonRegist" class="btn btn-primary">관리자 학원등록</button>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopHakwon) hakwonList}}'
		, '	<tr>'
		, '		<td><span>{{= loopHakwon.hakwon_no}}</span></td>'
		, '		<td>'
		, '	{{if loopHakwon.admin_reg_yn == "Y" }}'
		, '			<a href="#" onclick="alert(\'관리자 등록 학원 입니다.\');return false;">'
		, '	{{/if}}'
		, '	{{if loopHakwon.admin_reg_yn != "Y" }}'
		, '			<a href="{{= PageUrl.hakwonDetail.introduce}}?hakwon_no={{= loopHakwon.hakwon_no}}">'
		, '	{{/if}}'
		, '				<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopHakwon.logo_file_path, "hakwon", true) }}" alt="" width="30" height="30">{{= loopHakwon.hakwon_name }}'
		, '			</a>'
		, '		</td>'
		, '		<td><span>{{= loopHakwon.old_addr1}}</span></td>'
		, '		<td><span>{{= loopHakwon.hakwon_cate_name }}</span></td>'
		, '		<td><a href="{{= PageUrl.master.view+"?masterUserNo="+loopHakwon.master_user_no}}">{{= loopHakwon.master_user_name }}</a></td>'
		, '		<td>'
		, '	{{if loopHakwon.admin_reg_yn == "Y" }}'
		, '			<a href="'+PageUrl.hakwon.adminModify+'?hakwon_no={{= loopHakwon.hakwon_no}}" class="btn btn-default" style="display:inline-block; padding:2px 10px;">관리자 등록 학원 수정</a>'
		, '	{{/if}}'
		, '	{{if loopHakwon.admin_reg_yn != "Y" }}'
		, '			{{= loopHakwon.hakwon_status_name}}'
		, '	{{/if}}'
		, '		</td>'
		, '		<td><span>{{= loopHakwon.reg_date }}시</span></td>'
		, '	</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'<div class="ibox-content text-center" style="padding:200px 0;">등록된 학원이 없습니다</div>'
	].join('')
	, regist : [
		'<form>'
		, '<div class="ibox m">'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_01">학원명</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="text" name="hakwonName" class="form-control" placeholder="20자까지" maxLength="20" id="academy_write_01">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_02">로고 이미지</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" class="input_file" data-act="photo_upload" id="academy_write_02" accept="image/*">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">이미지 확인</label>'
		, '			<div class="col-sm-11" data-view="image_preveiw">'
		, '				<button type="button" ng-click="logoDelete()" class="btn btn-default">삭제</button>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_02">전화번호</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="tel" name="telNo" class="form-control" placeholder="전화번호" id="academy_write_02">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_03">업종</label>'
		, '			<div class="col-sm-11">'
		, '				<select name="hakwonCate" class="form-control" ng-options="hakwonCate.cateName for hakwonCate in hakwonCateList track by hakwonCate.cateCode" ng-model="searchCateCode">'
		, '					<option value="">카테고리</option>'
		, '				</select>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_04">지번주소</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="col-md-4 input-group m-b">'
		, '					<input type="text" class="form-control" name="searchOldDong" placeholder="동 이름으로 검색" id="academy_write_04">'
		, '					<span class="input-group-btn"> <button type="button" data-act="searchOldAddr" class="btn btn-primary">검색</button> </span>'
		, '				</div>'
		, '				<ul class="address_search_result" style="display:none;" data-view="oldAddrList"></ul>'
		, '				<div class="row">'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="oldAddr1" class="form-control" placeholder="검색된 주소">'
		, '					</div>'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="oldAddr2" class="form-control" placeholder="기타주소 입력">'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_05">도로명주소</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="col-md-4 input-group m-b">'
		, '					<input type="text" name="searchStreetDong" class="form-control" placeholder="동 이름으로 검색" id="academy_write_05">'
		, '					<span class="input-group-btn"> <button type="button" data-act="searchStreetDong" class="btn btn-primary">검색</button> </span>'
		, '				</div>'
		, '				<ul class="address_search_result" style="display:none;" data-view="streetAddrList"></ul>'
		, '				<div class="row">'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="streetAddr1" class="form-control" placeholder="검색된 주소" readOnly="true">'
		, '					</div>'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="streetAddr2" class="form-control" placeholder="기타주소 입력">'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" ng-click="goList()" class="btn btn-default">취소하기</button>'
		, '		<button type="button" ng-click="regist()" class="btn btn-primary">등록하기</button>'
		, '	</div>'
		, '</div>'
		, '</form>'
	].join('')
	, adminModifyForm : [
		'<form data-view="modifyForm"></form>'
	].join('')
	/*	관리자 수정	*/
	, adminModify : [
		'<div class="ibox m">'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_01">학원명</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="text" name="hakwonName" value="{{= hakwonInfo.hakwon_name}}" class="form-control" placeholder="20자까지" maxLength="20" id="academy_write_01">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_02">로고 이미지</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" class="input_file" data-act="photo_upload" id="academy_write_02" accept="image/*">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">이미지 확인</label>'
		, '			<div class="col-sm-11" data-view="image_preveiw">'
		, '{{if isNull(hakwonInfo.logo_file_path) == false }}'
		, '				<img alt="image" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN + hakwonInfo.logo_file_path}}" data-file-no="{{= hakwonInfo.logo_file_no}}">'
		, '{{/if}}'
		, '				<button type="button" data-act="logoDelete" class="btn btn-default">삭제</button>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_02">전화번호</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="tel" name="telNo" class="form-control" value="{{= hakwonInfo.tel_no_1}}" placeholder="전화번호" id="academy_write_02">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_03">업종</label>'
		, '			<div class="col-sm-11">'
		, '				<select name="hakwonCate" class="form-control" ng-options="hakwonCate.cateName for hakwonCate in hakwonCateList track by hakwonCate.cateCode" ng-model="searchCateCode">'
		, '					<option value="">카테고리</option>'
		, '{{each(i, loopHakwonCate) hakwonCateList}}'
		, '					<option value="{{= loopHakwonCate.cateCode}}" {{= loopHakwonCate.cateCode == hakwonInfo.hakwon_cate?"selected":""}}>{{= loopHakwonCate.cateName}}</option>'
		, '{{/each}}'
		, '				</select>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_04">지번주소</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="col-md-4 input-group m-b">'
		, '					<input type="text" class="form-control" name="searchOldDong" placeholder="동 이름으로 검색" id="academy_write_04">'
		, '					<span class="input-group-btn"> <button type="button" data-act="searchOldAddr" class="btn btn-primary">검색</button> </span>'
		, '				</div>'
		, '				<ul class="address_search_result" style="display:none;" data-view="oldAddrList"></ul>'
		, '				<div class="row">'
		, '					<div class="col-md-6">'
		, '						<input type="text" data-addr-no="{{= hakwonInfo.addr_no}}" name="oldAddr1" value="{{= hakwonInfo.old_addr1}}" class="form-control" placeholder="검색된 주소">'
		, '					</div>'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="oldAddr2" value="{{= hakwonInfo.old_addr2}}" class="form-control" placeholder="기타주소 입력">'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_05">도로명주소</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="col-md-4 input-group m-b">'
		, '					<input type="text" name="searchStreetDong" class="form-control" placeholder="동 이름으로 검색" id="academy_write_05">'
		, '					<span class="input-group-btn"> <button type="button" data-act="searchStreetDong" class="btn btn-primary">검색</button> </span>'
		, '				</div>'
		, '				<ul class="address_search_result" style="display:none;" data-view="streetAddrList"></ul>'
		, '				<div class="row">'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="streetAddr1" value="{{= hakwonInfo.street_addr1}}" class="form-control" placeholder="검색된 주소" readOnly="true">'
		, '					</div>'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="streetAddr2" value="{{= hakwonInfo.street_addr2}}" class="form-control" placeholder="기타주소 입력">'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="cancel" class="btn btn-default">취소하기</button>'
		, '		<button type="button" data-act="delete" class="btn btn-default">삭제하기</button>'
		, '		<button type="button" data-act="modify" class="btn btn-primary">등록하기</button>'
		, '	</div>'
		, '</div>'
	].join('')
	, oldAddrRow : [
		'{{each(i, loopOldAddr) dataList}}'
		, '<li data-addr-no="{{= loopOldAddr.addr_no}}" data-act="oldAddrLI">'
		, '	<a href="#" onclick="return false;" data-addr-no="{{= loopOldAddr.addr_no}}">{{= loopOldAddr.zip_code}} <span>{{= loopOldAddr.sido}} {{= loopOldAddr.gugun}} {{= loopOldAddr.dong}} </span>{{= loopOldAddr.ri}} {{= loopOldAddr.bldg_name}} {{= loopOldAddr.bunji}}</a>'
		, '</li>'
		, '{{/each}}'
	].join('')
	/*	학원상세폼	*/
	, hakwonDetailForm : [
		'<div class="col-md-3" data-view="left">'+hakwonTmpl.common.init+'</div>'
		, '<div class="col-md-9" data-view="content">'+hakwonTmpl.common.init+'</div>'
	].join('')
	/*	학원 상세 왼쪽 메뉴	*/
	, hakwonDetailLeft : [
		'	<div class="ibox float-e-margins">'
		, '		<div class="ibox-title">'
		, '			<h2>MENU</h2>'
		, '		</div>'
		, '		<div class="ibox-content class_menu">'
		, '			<ul>'
		, '				<li class="{{= menuType=="introduce"?"active":""}}"><a href="{{= PageUrl.hakwonDetail.introduce+"?hakwon_no="+hakwonInfo.hakwon_no}}">학원 소개</a></li>'
		, '				<li class="{{= menuType=="classList"?"active":""}}"><a href="{{= PageUrl.hakwonDetail.classList+"?hakwon_no="+hakwonInfo.hakwon_no}}">반</a></li>'
		, '				<li class="{{= menuType=="teacherList"?"active":""}}"><a href="{{= PageUrl.hakwonDetail.teacherList+"?hakwon_no="+hakwonInfo.hakwon_no}}">선생님</a></li>'
		, '				<li class="{{= menuType=="parentList"?"active":""}}"><a href="{{= PageUrl.hakwonDetail.parentList+"?hakwon_no="+hakwonInfo.hakwon_no}}">학부모</a></li>'
		, '				<li class="{{= menuType=="studentList"?"active":""}}"><a href="{{= PageUrl.hakwonDetail.studentList+"?hakwon_no="+hakwonInfo.hakwon_no}}">학생</a></li>'
		, '			</ul>'
		, '		</div>'
		, '		<div class="ibox-title">'
		, '			<h2>학원 정보</h2>'
		, '		</div>'
		, '		<div class="ibox-content no-padding border-left-right class_photo">'
		, '			<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(hakwonInfo.logo_file_path, "hakwon", true)}}">'
		, '		</div>'
		, '		<div class="ibox-content profile-content">'
		, '			<div class="class_profile">'
		, '				<h3><strong>{{= hakwonInfo.hakwon_name}}</strong></h3>'
		, '				<ul>'
		, '					<li>지역 : {{= hakwonInfo.old_sido}}</li>'
		, '					<li>업종 : {{= hakwonInfo.hakwon_cate_name}}</li>'
		, '					<li>주소 : {{= hakwonInfo.old_addr1 + " " + hakwonInfo.old_addr2}}</li>'
		, '					<li>전화번호 : <a href="tel:{{= hakwonInfo.tel_no_1}}">{{= hakwonInfo.tel_no_1}}</a></li>'
		, '					<li data-view="statusLi" data-status="{{= hakwonInfo.hakwon_status}}">학원 상태 : {{= hakwonInfo.hakwon_status_name}}</li>'
		, '				</ul>'
		, '			</div>'
		, '			<select name="hakwon_status" class="form-control m-b">'
		, '				<option value="001" {{= hakwonInfo.hakwon_status == "001"?"selected":""}}>인증</option>'
		, '				<option value="002" {{= hakwonInfo.hakwon_status == "002"?"selected":""}}>미인증</option>'
		, '				<option value="003" {{= hakwonInfo.hakwon_status == "003"?"selected":""}}>원장님&선생님 접근 금지</option>'
		, '			</select>'
		, '			<button type="button" data-toggle="modal" data-target="#hakwon_status_layer" class="btn btn-primary btn-block m-t-xl">학원 상태 변경</button>'
		, '			<div class="modal inmodal" id="hakwon_status_layer" tabindex="-1" role="dialog" aria-hidden="true">'
		, '				<div class="modal-dialog">'
		, '					<div class="modal-content animated fadeIn">'
		, '						<div class="modal-header">'
		, '							<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>'
		, '							<h4 class="modal-title">학원 상태 변경</h4>'
		, '						</div>'
		, '						<div class="modal-body">'
		, '							<textarea rows="5" cols="" name="hakwonStatusMessage" class="form-control m-b" placeholder="원장님께 전달할 메세지를 입력해 주세요."></textarea>'
		, '						</div>'
		, '						<div class="modal-footer">'
		, '							<button type="button" class="btn btn-white" data-dismiss="modal">닫기</button>'
		, '							<button type="button" class="btn btn-primary" data-act="hakwonStatusChange">확인</button>'
		, '						</div>'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="ibox-content class_teacher_list">'
		, '			<h4>학원장</h4>'
		, '			<div class="ceo_info">'
		, '				<a href="{{= PageUrl.master.view+"?masterUserNo="+hakwonInfo.master_user_no}}">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(hakwonInfo.master_photo_file_path, "photo", true)}}" alt="{{= hakwonInfo.master_user_name}}" width="30" height="30">'
		, '					<strong class="name">{{= hakwonInfo.master_user_name}}</strong> <span>{{= hakwonInfo.master_user_gender_name}}/{{= !hakwonInfo.master_user_age||hakwonInfo.master_user_age==0?"생일 미입력":hakwonInfo.master_user_age+"세"}}</span>'
		, '				</a>'
		, '				<button class="btn btn-default btn_message" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button>'
		, '			</div>'
		, '		</div>'
		, '	{{if managerInfo }}'
		, '		<div class="ibox-content class_teacher_list">'
		, '			<h4>매니저</h4>'
		, '			<div class="ceo_info">'
		, '				<a href="{{= PageUrl.manager.view+"?managerUserNo="+managerInfo.user_no}}">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(managerInfo.photo_file_no, "photo", true)}}" alt="{{= managerInfo.user_name}}" width="30" height="30">'
		, '					<strong class="name">{{= managerInfo.user_name}}</strong>'
		, '				</a>'
		, '			</div>'
		, '		</div>'
		, '	{{/if}}'
		, '	</div>'
	].join('')
	/*	학원상세 소개	*/
	, hakwonIntroduce : [
		'{{if !hakwonInfo.introduction }}'
		, '	<div class="ibox float-e-margins">'
		, '		<div class="ibox-title text-center" style="padding:200px 0;">'
		, '			등록된 소개 정보가 없습니다.'
		, '		</div>'
		, '	</div>'
		, '{{/if}}'
		, '{{if hakwonInfo.introduction}}'
		, '	<div class="ibox float-e-margins">'
		, '		<div class="ibox-content">{{html hakwonInfo.introduction}}</div>'
		, '	</div>'
		, '{{/if}}'
		, '<div class="ibox-content text-right">'
		, '	<a href="#/hakwon/detail/introUpdate?hakwon_no={{= hakwonInfo.hakwon_no}}" class="btn btn-primary">학원소개 수정</a>'
		, '</div>'
	].join('')
	/*	학원상세 소개 수정	*/
	, hakwonIntroUpdate : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">내용</label>'
		, '			<div class="col-sm-11">'
		, '				<textarea cols="140" data-lib="editor" rows="10" class="form-control">{{= hakwonInfo.introduction }}</textarea>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">지도첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="input-group">'
		, '					<input type="text" name="daumMapHtml" class="form-control">'
		, '					<span class="input-group-btn"> <button type="button" data-act="daumMapInsert" class="btn btn-primary">지도삽입</button> </span>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">Youtube 동영상 첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="input-group">'
		, '					<input type="text" name="youtubeID" class="form-control">'
		, '					<span class="input-group-btn"> <button type="button" data-act="youtubeInsert" placeholder="Youtube 동영상 코드를 입력해 주세요." class="btn btn-primary">동영상 삽입</button> </span>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" class="input_file" data-act="file_upload" multiple>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">첨부파일</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="attachment" data-list="attachment">'
		, '				{{if fileList && fileList.length > 0}}'
		, '				{{each(i, loopFile) fileList}}'
		, '					<div class="file-box" data-file-no="{{= loopFile.file_no}}">'
		, '						<div class="file">'
		, '					{{if loopFile.image_yn == "Y" }}'
		, '							<div class="image">'
		, '								<img alt="image" class="img-responsive" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+loopFile.file_path}}">'
		, '							</div>'
		, '					{{/if}}'
		, '					{{if loopFile.image_yn != "Y" }}'
		, '							{{if loopFile.file_ext_type.indexOf("video") == 0 }}'
		, '							<div class="icon" data-file-type="video" data-file-url="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+loopFile.file_path}}">'
		, '								<i class="fa fa-file"></i>'
		, '							</div>'
		, '							{{/if}}'
		, '							{{if loopFile.file_ext_type.indexOf("video") != 0 }}'
		, '							<div class="icon">'
		, '								<i class="fa fa-file"></i>'
		, '							</div>'
		, '							{{/if}}'
		, '					{{/if}}'
		, '							<div class="file-name">'
		, '								<p>{{= loopFile.file_name}}</p>'
		, '							</div>'
		, '							<button type="button" data-file-no="{{= loopFile.file_no}}" data-act="fileDel" class="btn btn-circle btn_file_del" title="삭제">X</button>'
		, '						</div>'
		, '					</div>'
		, '				{{/each}}'
		, '				{{/if}}'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" data-act="introUpdateCancel">취소하기</button>'
		, '		<button type="button" class="btn btn-primary" data-act="introUpdateSave">등록하기</button>'
		, '		<button type="button" class="btn btn-primary" data-act="introUpdatePreview">미리보기</button>'
		, '	</div>'
		, '</div>'
	].join('')
	/*	학원상세(반 리스트)	*/
	, hakwonClassList : [
		'	<div class="ibox float-e-margins">'
		, '		<div class="ibox-content">'
		, '			<table class="table table-hover table_link">'
		, '				<thead>'
		, '					<tr>'
		, '						<th>반명</th>'
		, '						<th>학생수</th>'
		, '					</tr>'
		, '				</thead>'
		, '				<tbody>'
		, '	{{each(i, loopData) dataList}}'
		, '					<tr>'
		, '						<td>'
		, '							<a href="#">'
		, '								<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopData.logo_file_path, "hakwon", true)}}" alt="{{= loopData.class_title}}" width="30" height="30">{{= loopData.class_title}}'
		, '							</a>'
		, '						</td>'
		, '						<td><span>{{= loopData.student_count}}</span></td>'
		, '					</tr>'
		, '	{{/each}}'
		, '	{{if !dataList || dataList.length == 0 }}'
		, '					<tr>'
		, '						<td colspan="2" class="box_nodata">등록된 반이 없습니다.</td>'
		, '					</tr>'
		, '	{{/if}}'
		, '				</tbody>'
		, '			</table>'
		, '		</div>'
		, '	</div>'
	].join('')
	/*	학원상세(학생 리스트)	*/
	, hakwonStudentList : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>학교</th>'
		, '					<th>성별</th>'
		, '					<!-- <th>메세지</th> -->'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '	{{each(i, loopData) dataList}}'
		, '				<tr>'
		, '					<td><span><input type="checkbox" class="i-checks" name="input"></span></td>'
		, '					<td>'
		, '						<a href="{{= PageUrl.student.view+"?studentUserNo="+loopData.user_no}}"><img class="img-circle" src="hakwonCommon.createFilePullPath(loopData.user_photo_path, "photo", true)" alt="{{= loopData.user_name}}" width="30" height="30"> {{= loopData.user_name}}</a>'
		, '					</td>'
		, '					<td><span>{{= loopData.user_id}}</span></td>'
		, '					<td><span>{{= loopData.school_info}}</span></td>'
		, '					<td><span>{{= loopData.user_gender=="M"?"남자":"여자"}}</span></td>'
		, '					<!-- <td><span><button class="btn btn-default btn_message" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></span></td> -->'
		, '				</tr>'
		, '	{{/each}}'
		, '	{{if !dataList || dataList.length == 0 }}'
		, '					<tr>'
		, '						<td colspan="5" class="box_nodata">등록된 학생이 없습니다</td>'
		, '					</tr>'
		, '	{{/if}}'
		, '			</tbody>'
		, '		</table>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	학원상세(학부모 리스트)	*/
	, hakwonParentList : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>성별</th>'
		, '					<th>나이</th>'
		, '					<!-- <th>메세지</th> -->'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '	{{each(i, loopData) dataList}}'
		, '				<tr>'
		, '					<td><span><input type="checkbox" class="i-checks" name="input"></span></td>'
		, '					<td>'
		, '						<a href="{{= PageUrl.parent.view+"?parentUserNo="+loopData.user_no}}"><img class="img-circle" src="hakwonCommon.createFilePullPath(loopData.user_photo_path, "photo", true)" alt="ㅇㅇㅇ반 프로필" width="30" height="30"> 홍길동</a>'
		, '					</td>'
		, '					<td><span>{{= loopData.user_id}}</span></td>'
		, '					<td><span>{{= loopData.user_gender=="M"?"남자":"여자"}}</span></td>'
		, '					<td><span>{{= !loopData.user_age||loopData.user_age==0?"생일 미입력":loopData.user_age}}</span></td>'
		, '					<!-- <td><span><button class="btn btn-default btn_message" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></span></td> -->'
		, '				</tr>'
		, '	{{/each}}'
		, '	{{if !dataList || dataList.length == 0 }}'
		, '					<tr>'
		, '						<td colspan="5" class="box_nodata">등록된 학부모가 없습니다.</td>'
		, '					</tr>'
		, '	{{/if}}'
		, '			</tbody>'
		, '			</tbody>'
		, '		</table>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	학원상세(선생님 리스트)	*/
	, hakwonTeacherList : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>성별</th>'
		, '					<th>담당교과</th>'
		, '					<!-- <th>메세지</th> -->'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '	{{each(i, loopData) dataList}}'
		, '				<tr>'
		, '					<td><span><input type="checkbox" class="i-checks" name="input"></span></td>'
		, '					<td>'
		, '						<a href="{{= PageUrl.teacher.view+"?teacherUserNo="+loopData.user_no}}"><img class="img-circle" src="hakwonCommon.createFilePullPath(loopData.user_photo_path, "photo", true)" alt="ㅇㅇㅇ반 프로필" width="30" height="30"> 홍길동</a>'
		, '					</td>'
		, '					<td><span>{{= loopData.user_id}}</span></td>'
		, '					<td><span>{{= loopData.user_gender=="M"?"남자":"여자"}}</span></td>'
		, '					<td><span>수학</span></td>'
		, '					<!-- <td><span><button class="btn btn-default btn_message" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></span></td> -->'
		, '				</tr>'
		, '	{{/each}}'
		, '	{{if !dataList || dataList.length == 0 }}'
		, '					<tr>'
		, '						<td colspan="6" class="box_nodata">등록된 선생님이 없습니다</td>'
		, '					</tr>'
		, '	{{/if}}'
		, '			</tbody>'
		, '		</table>'
		, '	</div>'
		, '</div>'
	].join('')
};
/*	셋팅	*/
hakwonTmpl.setting = {
	/*	광고 입금 계좌 정보	*/
	advertiseBankInfo : [
		'<div class="ibox m">'
		, '	<div class="ibox-content form-horizontal" data-view="defaultPriceView">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="default_bank_info_01">입금 계좌 정보</label>'
		, '			<div class="col-sm-4">'
		, '				<input type="text" name="bankInfo" value="" class="form-control" id="default_bank_info_01">'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="save" class="btn btn-warning">저장</button>'
		, '	</div>'
		, '</div>'
	].join('')
	/*	베너 기본 가격	*/
	, bannerDefaultPrice : {
		form : [
			'<div class="ibox m">'
			, '	<div class="ibox-content form-horizontal" data-view="defaultPriceView"></div>'
			, '	<div class="ibox-content text-right">'
			, '		<button type="button" data-act="save" class="btn btn-warning">저장</button>'
			, '	</div>'
			, '</div>'
		].join('')
		, listRow : [
			'	{{each(i, loopPrice) dataList}}'
			, '		<div class="form-group" data-id="{{= loopPrice.cateCode}}">'
			, '			<label class="col-sm-1 control-label" for="default_price_01">베너크기</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="number" name="size" value="{{= loopPrice.size}}" onkeydown="commProto.onlyNumber(event)" onkeypress="commProto.onlyNumber(event)" class="form-control" id="default_price_01" readOnly="readOnly">'
			, '			</div>'
			, '			<label class="col-sm-1 control-label" for="default_price_02">기본 가격</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="number" name="price" value="{{= loopPrice.price}}" onkeydown="commProto.onlyNumber(event)" onkeypress="commProto.onlyNumber(event)" class="form-control" id="default_price_02">'
			, '			</div>'
			, '		</div>'
			, '	{{/each}}'
		].join('')
	}
	/*	카테고리	*/
	, category : {
		form : [
			'<div class="ibox m">'
			, '	<div class="ibox-content form-horizontal" data-view="hakwonCateList"></div>'
			, '	<div class="ibox-content text-right">'
			, '		<button type="button" data-act="newCate" class="btn btn-warning">새 업종 추가</button>'
			, '	</div>'
			, '</div>'
		].join('')
		, listCateRow : [
			'	{{each(i, loopCate) dataList}}'
			, '		<div class="form-group" data-id="{{= loopCate.cateCode}}">'
			, '			<label class="col-sm-1 control-label" for="category_name_01">업종명</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="text" name="cate_name" value="{{= loopCate.cateName}}" class="form-control" id="category_name_01">'
			, '			</div>'
			, '			<label class="col-sm-1 control-label" for="category_name_02">노출 순서</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="text" name="cate_order" value="{{= loopCate.cateOrder}}" onkeydown="commProto.onlyNumber(event)" onkeypress="commProto.onlyNumber(event)" class="form-control" id="category_name_02">'
			, '			</div>'
			, '			<div class="col-sm-2">'
			, '				<button type="button" data-act="rowModify" class="btn btn-default">수정</button>'
			, '				<button type="button" data-act="rowDelete" class="btn btn-default">삭제</button>'
			, '			</div>'
			, '		</div>'
			, '	{{/each}}'
		].join('')
		, newCateRow : [
			, '		<div class="form-group" data-id="new">'
			, '			<label class="col-sm-1 control-label" for="category_name_01">신규 업종명</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="text" name="cate_name" class="form-control" id="category_name_01">'
			, '			</div>'
			, '			<label class="col-sm-1 control-label" for="category_name_02">노출 순서</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="text" name="cate_order" class="form-control" onkeydown="commProto.onlyNumber(event)" onkeypress="commProto.onlyNumber(event)" id="category_name_02">'
			, '			</div>'
			, '			<div class="col-sm-2">'
			, '				<button type="button" data-act="newSave" class="btn btn-default">저장</button>'
			, '				<button type="button" data-act="newCancel" class="btn btn-default">취소</button>'
			, '			</div>'
			, '		</div>'
		].join('')
	}
};

/*	원장	*/
hakwonTmpl.master = {
	listForm : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="이름으로 검색">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>성별</th>'
		, '					<th>학원</th>'
		, '					<th>가입일</th>'
		, '					<th>메세지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '				<tr><td colspan="8">'+hakwonTmpl.common.init+'</td></tr>'
		, '			</tbody>'
		, '		</table>'
		, '	</div>'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기" onclick="alert(\'준비 중 입니다.\');">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopData) dataList}}'
		, '<tr>'
		, '	<td><span><input type="checkbox" value="{{= loopData.user_no}}" class="i-checks" name="input"></span></td>'
		, '	<td>'
		, '		<a href="'+PageUrl.master.view+'?masterUserNo={{= loopData.user_no}}"><img class="img-circle" src="{{= comm.userProfileImg(loopData.user_photo_path)}}" alt="" width="30" height="30"> {{= loopData.user_name}}</a>'
		, '	</td>'
		, '	<td><span>{{= loopData.user_id}}</span></td>'
		, '	<td><span>{{= loopData.user_gender=="M"?"남":"여"}}</span></td>'
		, '	<td><span>{{= loopData.hakwon_names}}</span></td>'
		, '	<td><span>{{= loopData.reg_date}}</span></td>'
		, '	<td><span><button class="btn btn-default btn_message" data-user-no="{{= loopData.user_no}}" type="button" title="메세지 보내기" onclick="alert(\'준비 중 입니다.\');"><i class="fa fa-envelope"></i> </button></span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'<tr>'
		, '	<td class="text-center" style="padding:200px 0 !important;">검색된 원장님이 없습니다.</td>'
		, '</tr>'
	].join('')
	/*	원장 상세	*/
	, viewForm : ['<div class="col-md-8 col-md-offset-2" data-view="data-view">'+hakwonTmpl.common.init+'</div>'].join('')
	, viewData : [
		'	<div class="widget-head-color-box blue-bg p-lg text-center">'
		, '		<h2 class="font-bold">{{= userInfo.user_name}}</h2>'
		, '		<img src="{{= hakwonCommon.createFilePullPath(userInfo.photo_file_path, "photo", true)}}" class="circle-border m-md img-responsive" alt="{{= userInfo.user_name}}" width="300">'
		, '		<p>{{= userInfo.user_gender_name}} / {{= !userInfo.user_age||userInfo.user_age==0?"생일 미입력":userInfo.user_age+"세"}}</p>'
		, '	</div>'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">연락정보</h3>'
		, '		<div class="row">'
		, '			<div class="col-md-10">'
		, '				<ul>'
		, '					<li>아이디 : {{= userInfo.user_id}}</li>'
		, '					<li>이메일 : <a href="mailto:{{= userInfo.user_email}}">{{= userInfo.user_email}}</a></li>'
		, '					<li>전화번호 : <a href="tel:{{= userInfo.tel1_no}}">{{= userInfo.tel1_no}}</a></li>'
		, '					<li>가입 일자 : {{= userInfo.reg_date}}</li>'
		, '				</ul>'
		, '			</div>'
		, '			<div class="col-md-2 text-right"><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></div>'
		, '		</div>'
		, '	</div>'
		, '{{if hakwonList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학원정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopHakwon) hakwonList}}'
		, '			<li>'
		, '				<a href="#/hakwon/detail/introduce?hakwon_no={{= loopHakwon.hakwon_no}}">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopHakwon.logo_file_path, "hakwon", true)}}" alt="{{= loopHakwon.hakwon_name}}" width="30" height="30">'
		, '					<strong class="name">{{= loopHakwon.hakwon_name}}</strong> <span class="info_text">{{= loopHakwon.old_sido + " " + loopHakwon.old_gugun }}/{{= loopHakwon.hakwon_cate_name}}</span>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'
		, '	<div class="text-right m-t">'
		, '		<button class="btn btn-danger" data-act="stop" data-val="{{= userInfo.use_yn}}" type="button">계정 {{= userInfo.use_yn=="Y"?"일시 정지":"활성화"}}</button>'
		, '		<button class="btn btn-default" data-act="list" type="button">목록으로</button>'
		, '	</div>'
	].join('')
	/*	가입 승인 요청	*/
	, join_request_list : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="이름으로 검색">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름(아이디)</th>'
		, '					<th>가입일</th>'
		, '					<th>성별</th>'
		, '					<th>연락처</th>'
		, '					<th>승인여부</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody></tbody>'
		, '		</table>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button class="btn btn-default" data-act="approved" value="N" type="button">거절</button>'
		, '		<button class="btn btn-primary" data-act="approved" value="Y" type="button">수락</button>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	가입 승인 요청 로우	*/
	, join_request_list_row : [
		'{{each(i, loopMaster) userList}}'
		, '<tr>'
		, '	<td><span><input type="checkbox" class="i-checks" name="reqUSerNo" value="{{= loopMaster.user_no}}"></span></td>'
		, '	<td>'
		, '		<img class="img-circle" src="{{= comm.userProfileImg(loopMaster.user_photo_path)}}" alt="{{= loopMaster.user_name}}" width="30" height="30"> {{= loopMaster.user_name}}({{= loopMaster.user_id}})'
		, '	</td>'
		, '	<td><span>{{= loopMaster.reg_date}}</span></td>'
		, '	<td><span>{{= loopMaster.user_gender=="M"?"남자":"여자"}}</span></td>'
		, '	<td><a href="tel:{{= loopMaster.tel1_no}}">{{= loopMaster.tel1_no}}</a></td>'
		, '	<td><span>{{= loopMaster.approved_yn=="N"?"거절":"대기"}}</span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	, join_request_list_nodata : [
		'<tr>'
		, '<td class="text-center" style="padding:200px 0 !important;">가입요청 원장님이 없습니다.</td>'
		, '</tr>'
	].join('')
};

/*	학생	*/
hakwonTmpl.student = {
	listForm : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="이름으로 검색">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>성별</th>'
		, '					<th>가입일</th>'
		, '					<th>메세지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody></tbody>'
		, '		</table>'
		, '	</div>'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopData) dataList}}'
		, '<tr>'
		, '	<td><span><input type="checkbox" value="{{= loopData.user_no}}" class="i-checks" name="input"></span></td>'
		, '	<td>'
		, '		<a href="'+PageUrl.student.view+'?studentUserNo={{= loopData.user_no}}"><img class="img-circle" src="{{= comm.userProfileImg(loopData.user_photo_path)}}" alt="" width="30" height="30"> {{= loopData.user_name}}</a>'
		, '	</td>'
		, '	<td><span>{{= loopData.user_id}}</span></td>'
		, '	<td><span>{{= loopData.user_gender=="M"?"남":"여"}}</span></td>'
		, '	<td><span>{{= loopData.reg_date}}</span></td>'
		, '	<td><span><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" data-user-no="{{= loopData.user_no}}" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'<tr>'
		, '	<td class="text-center" style="padding:200px 0 !important;">검색된 학생이 없습니다.</td>'
		, '</tr>'
	].join('')
	, viewForm : ['<div class="col-md-8 col-md-offset-2" data-view="data-view">'+hakwonTmpl.common.init+'</div>'].join('')
	, viewData : [
		'	<div class="widget-head-color-box blue-bg p-lg text-center">'
		, '		<h2 class="font-bold">{{= userInfo.user_name}}</h2>'
		, '		<img src="{{= hakwonCommon.createFilePullPath(userInfo.photo_file_path, "photo", true)}}" class="circle-border m-md img-responsive" alt="{{= userInfo.user_name}}" width="300">'
		, '		<p>{{= userInfo.user_gender_name}} / {{= !userInfo.user_age||userInfo.user_age==0?"생일 미입력":userInfo.user_age+"세"}} / {{= schoolInfo.school_name}} {{= schoolInfo.level}}학년</p>'
		, '	</div>'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">연락정보</h3>'
		, '		<div class="row">'
		, '			<div class="col-md-10">'
		, '				<ul>'
		, '					<li>이메일 : <a href="mailto:{{= userInfo.user_email}}">{{= userInfo.user_email}}</a></li>'
		, '					<li>전화번호 : <a href="tel:{{= userInfo.tel1_no}}">{{= userInfo.tel1_no}}</a></li>'
		, '					<li>가입 일자 : {{= userInfo.reg_date}}</li>'
		, '					<li>출결번호 : {{= userInfo.attendance_code}}</li>'
		, '				</ul>'
		, '			</div>'
		, '			<div class="col-md-2 text-right"><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></div>'
		, '		</div>'
		, '	</div>'
		, '{{if hakwonList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학원정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopHakwon) hakwonList}}'
		, '			<li>'
		, '				<a href="#">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopHakwon.logo_file_path, "hakwon", true)}}" alt="{{= loopHakwon.hakwon_name}}" width="30" height="30">'
		, '					<strong class="name">{{= loopHakwon.hakwon_name}}</strong> <span class="info_text">{{= loopHakwon.old_sido}}/{{= loopHakwon.hakwon_cate_name}}/{{= loopHakwon.class_name}}</span>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'
		, '{{if parentList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학부모 정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopParent) parentList}}'
		, '			<li>'
		, '				<a href="#">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopParent.photo_file_path, "photo", true)}}" alt="{{= loopParent.user_name}}" width="30" height="30">'
		, '					<strong class="name">{{= loopParent.user_name}}</strong> <span class="info_text">{{= (loopParent.user_gender=="M"?"남":"여")}} / {{= !loopParent.user_age||loopParent.user_age==0?"생일 미입력":loopParent.user_age+"세"}}</span>'
		, '					<span class="badge badge-plain">{{= (loopParent.user_gender=="M"?"부":"모")}}</span>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'
		, '	<div class="text-right m-t">'
		, '		<button class="btn btn-default" data-act="list" type="button">목록으로</button>'
		, '	</div>'
	].join('')
};

/*	학부모	*/
hakwonTmpl.parent = {
	listForm : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="이름으로 검색">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>성별</th>'
		, '					<th>가입일</th>'
		, '					<th>메세지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody></tbody>'
		, '		</table>'
		, '	</div>'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopData) dataList}}'
		, '<tr>'
		, '	<td><span><input type="checkbox" value="{{= loopData.user_no}}" class="i-checks" name="input"></span></td>'
		, '	<td>'
		, '		<a href="'+PageUrl.parent.view+'?parentUserNo={{= loopData.user_no}}"><img class="img-circle" src="{{= comm.userProfileImg(loopData.user_photo_path)}}" alt="" width="30" height="30"> {{= loopData.user_name}}</a>'
		, '	</td>'
		, '	<td><span>{{= loopData.user_id}}</span></td>'
		, '	<td><span>{{= loopData.user_gender=="M"?"남":"여"}}</span></td>'
		, '	<td><span>{{= loopData.reg_date}}</span></td>'
		, '	<td><span><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" data-user-no="{{= loopData.user_no}}" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'<tr>'
		, '	<td class="text-center" style="padding:200px 0 !important;">검색된 학부모님이 없습니다.</td>'
		, '</tr>'
	].join('')
	, viewForm : ['<div class="col-md-8 col-md-offset-2" data-view="data-view"></div>'].join('')
	, viewData : [
		'	<div class="widget-head-color-box red-bg p-lg text-center">'
		, '		<h2 class="font-bold">{{= userInfo.user_name}}</h2>'
		, '		<img src="{{= hakwonCommon.createFilePullPath(userInfo.photo_file_path, "photo", true)}}" class="circle-border m-md img-responsive" alt="{{= userInfo.user_name}}" width="300">'
		, '		<p>{{= userInfo.user_gender_name}} / {{= !userInfo.user_age||userInfo.user_age==0?"생일 미입력":userInfo.user_age+"세"}}</p>'
		, '	</div>'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">연락정보</h3>'
		, '		<div class="row">'
		, '			<div class="col-md-10">'
		, '				<ul>'
		, '					<li>이메일 : <a href="mailto:{{= userInfo.user_email}}">{{= userInfo.user_email}}</a></li>'
		, '					<li>전화번호 : <a href="tel:{{= userInfo.tel1_no}}">{{= userInfo.tel1_no}}</a></li>'
		, '					<li>가입 일자 : {{= userInfo.reg_date}}</li>'
		, '				</ul>'
		, '			</div>'
		, '			<div class="col-md-2 text-right"><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></div>'
		, '		</div>'
		, '	</div>'
		, '{{if hakwonList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학원정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopHakwon) hakwonList}}'
		, '			<li>'
		, '				<a href="#">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopHakwon.logo_file_path, "hakwon", true)}}" alt="{{= loopHakwon.hakwon_name}}" width="30" height="30">'
		, '					<strong class="name">{{= loopHakwon.hakwon_name}}</strong> <span class="info_text">{{= loopHakwon.old_sido}}/{{= loopHakwon.hakwon_cate_name}}/{{= loopHakwon.class_name}}</span>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'
		, '{{if childList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학생 정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopStudent) childList}}'
		, '			<li>'
		, '				<a href="#">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopStudent.photo_file_path, "photo", true)}}" alt="{{= loopStudent.user_name}}" width="30" height="30">'
		, '					<strong class="name">{{= loopStudent.user_name}}</strong> <span class="info_text">{{= (loopStudent.user_gender=="M"?"남":"여")}} / {{= !loopStudent.user_age||loopStudent.user_age==0?"생일 미입력":loopStudent.user_age+"세"}}</span>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'
		, '	<div class="text-right m-t">'
		, '		<button class="btn btn-default" data-act="list" type="button">목록으로</button>'
		, '	</div>'
	].join('')
};

/*	선생님	*/
hakwonTmpl.teacher = {
	listForm : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="이름으로 검색">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>성별</th>'
		, '					<th>학원</th>'
		, '					<th>담당 교과</th>'
		, '					<th>가입일</th>'
		, '					<th>메세지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody></tbody>'
		, '		</table>'
		, '	</div>'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopData) dataList}}'
		, '<tr>'
		, '	<td><span><input type="checkbox" value="{{= loopData.user_no}}" class="i-checks" name="input"></span></td>'
		, '	<td>'
		, '		<a href="{{= PageUrl.teacher.view+"?teacherUserNo="+loopData.user_no}}"><img class="img-circle" src="{{= comm.userProfileImg(loopData.user_photo_path)}}" alt="" width="30" height="30"> {{= loopData.user_name}}</a>'
		, '	</td>'
		, '	<td><span>{{= loopData.user_id}}</span></td>'
		, '	<td><span>{{= loopData.user_gender=="M"?"남":"여"}}</span></td>'
		, '	<td><span>{{= loopData.hakwon_names}}</span></td>'
		, '	<td><span>{{= loopData.teacher_subject}}</span></td>'
		, '	<td><span>{{= loopData.reg_date}}</span></td>'
		, '	<td><span><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" data-user-no="{{= loopData.user_no}}" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'<tr>'
		, '	<td class="text-center" style="padding:200px 0 !important;">검색된 선생님이 없습니다.</td>'
		, '</tr>'
	].join('')
	, viewForm : ['<div class="col-md-8 col-md-offset-2" data-view="data-view">'+hakwonTmpl.common.init+'</div>'].join('')
	, viewData : [
		'	<div class="widget-head-color-box yellow-bg p-lg text-center">'
		, '		<h2 class="font-bold">{{= userInfo.user_name}}</h2>'
		, '		<img src="{{= hakwonCommon.createFilePullPath(userInfo.photo_file_path, "photo", true)}}" class="circle-border m-md img-responsive" alt="{{= userInfo.user_name}}" width="300">'
		, '		<p>{{= userInfo.user_gender_name}} / {{= !userInfo.user_age||userInfo.user_age==0?"생일 미입력":userInfo.user_age+"세"}}</p>'
		, '	</div>'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">연락정보</h3>'
		, '		<div class="row">'
		, '			<div class="col-md-10">'
		, '				<ul>'
		, '					<li>이메일 : <a href="mailto:{{= userInfo.user_email}}">{{= userInfo.user_email}}</a></li>'
		, '					<li>전화번호 : <a href="tel:{{= userInfo.tel1_no}}">{{= userInfo.tel1_no}}</a></li>'
		, '					<li>가입 일자 : {{= userInfo.reg_date}}</li>'
		, '				</ul>'
		, '			</div>'
		, '			<div class="col-md-2 text-right"><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></div>'
		, '		</div>'
		, '	</div>'
		, '{{if hakwonList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학원정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopHakwon) hakwonList}}'
		, '			<li>'
		, '				<a href="'+PageUrl.hakwonDetail.classList+'?hakwon_no={{= loopHakwon.hakwon_no}}">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopHakwon.logo_file_path, "hakwon", true)}}" alt="{{= loopHakwon.hakwon_name}}" width="30" height="30">'
		, '					<strong class="name">{{= loopHakwon.hakwon_name}}</strong> <span class="info_text">{{= loopHakwon.old_sido}}/{{= loopHakwon.hakwon_cate_name}}/{{= loopHakwon.class_name}}</span>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'
		, '	<div class="text-right m-t">'
		, '		<button class="btn btn-default" data-act="list" type="button">목록으로</button>'
		, '	</div>'
	].join('')
};

/*	매니저	*/
hakwonTmpl.manager = {
	listForm : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="이름으로 검색">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>성별</th>'
		, '					<th>가입일</th>'
		, '					<th>매니저 번호</th>'
		, '					<th>메세지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '				<tr><td colspan="8">'+hakwonTmpl.common.init+'</td></tr>'
		, '			</tbody>'
		, '		</table>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopData) dataList}}'
		, '<tr>'
		, '	<td><span><input type="checkbox" value="{{= loopData.user_no}}" class="i-checks" name="input"></span></td>'
		, '	<td>'
		, '		<a href="'+PageUrl.manager.view+'?managerUserNo={{= loopData.user_no}}"><img class="img-circle" src="{{= comm.userProfileImg(loopData.user_photo_path)}}" alt="" width="30" height="30"> {{= loopData.user_name}}</a>'
		, '	</td>'
		, '	<td><span>{{= loopData.user_id}}</span></td>'
		, '	<td><span>{{= loopData.user_gender=="M"?"남":"여"}}</span></td>'
		, '	<td><span>{{= loopData.reg_date}}</span></td>'
		, '	<td><span>{{= loopData.manager_no}}</span></td>'
		, '	<td><span><button class="btn btn-default btn_message" data-user-no="{{= loopData.user_no}}" type="button" title="메세지 보내기" onclick="alert(\'준비 중 입니다.\');"><i class="fa fa-envelope"></i> </button></span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'<tr>'
		, '	<td class="text-center" style="padding:200px 0 !important;">검색된 매니저가 없습니다.</td>'
		, '</tr>'
	].join('')
	/*	매니저 상세	*/
	, viewForm : ['<div class="col-md-8 col-md-offset-2" data-view="data-view">'+hakwonTmpl.common.init+'</div>'].join('')
	, viewData : [
		'	<div class="widget-head-color-box blue-bg p-lg text-center">'
		, '		<h2 class="font-bold">{{= userInfo.user_name}}</h2>'
		, '		<img src="{{= hakwonCommon.createFilePullPath(userInfo.photo_file_path, "photo", true)}}" class="circle-border m-md img-responsive" alt="{{= userInfo.user_name}}" width="300">'
		, '		<p>{{= userInfo.user_gender_name}} / {{= !userInfo.user_age||userInfo.user_age==0?"생일 미입력":userInfo.user_age+"세"}}</p>'
		, '	</div>'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">연락정보</h3>'
		, '		<div class="row">'
		, '			<div class="col-md-10">'
		, '				<ul>'
		, '					<li>이메일 : <a href="mailto:{{= userInfo.user_email}}">{{= userInfo.user_email}}</a></li>'
		, '					<li>전화번호 : <a href="tel:{{= userInfo.tel1_no}}">{{= userInfo.tel1_no}}</a></li>'
		, '					<li>가입 일자 : {{= userInfo.reg_date}}</li>'
		, '				</ul>'
		, '			</div>'
		, '			<div class="col-md-2 text-right"><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></div>'
		, '		</div>'
		, '	</div>'
		, '{{if hakwonList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학원정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopHakwon) hakwonList}}'
		, '			<li>'
		, '				<a href="#/hakwon/detail/introduce?hakwon_no={{= loopHakwon.hakwon_no}}">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopHakwon.logo_file_path, "hakwon", true)}}" alt="{{= loopHakwon.hakwon_name}}" width="30" height="30">'
		, '					<strong class="name">{{= loopHakwon.hakwon_name}}</strong> <span class="info_text">{{= loopHakwon.old_sido + " " + loopHakwon.old_gugun }}/{{= loopHakwon.hakwon_cate_name}}</span>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'
		, '	<div class="text-right m-t">'
		, '		<button class="btn btn-danger" data-act="stop" data-val="{{= userInfo.use_yn}}" type="button">계정 {{= userInfo.use_yn=="Y"?"일시 정지":"활성화"}}</button>'
		, '		<button class="btn btn-default" data-act="list" type="button">목록으로</button>'
		, '	</div>'
	].join('')
	/*	가입 승인 요청	*/
	, join_request_list : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="이름으로 검색">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름(아이디)</th>'
		, '					<th>가입일</th>'
		, '					<th>성별</th>'
		, '					<th>연락처</th>'
		, '					<th>승인여부</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody></tbody>'
		, '		</table>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button class="btn btn-default" data-act="approved" value="N" type="button">거절</button>'
		, '		<button class="btn btn-primary" data-act="approved" value="Y" type="button">수락</button>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	가입 승인 요청 로우	*/
	, join_request_list_row : [
		'{{each(i, loopMaster) userList}}'
		, '<tr>'
		, '	<td><span><input type="checkbox" class="i-checks" name="reqUSerNo" value="{{= loopMaster.user_no}}"></span></td>'
		, '	<td>'
		, '		<img class="img-circle" src="{{= comm.userProfileImg(loopMaster.user_photo_path)}}" alt="{{= loopMaster.user_name}}" width="30" height="30"> {{= loopMaster.user_name}}({{= loopMaster.user_id}})'
		, '	</td>'
		, '	<td><span>{{= loopMaster.reg_date}}</span></td>'
		, '	<td><span>{{= loopMaster.user_gender=="M"?"남자":"여자"}}</span></td>'
		, '	<td><a href="tel:{{= loopMaster.tel1_no}}">{{= loopMaster.tel1_no}}</a></td>'
		, '	<td><span>{{= loopMaster.approved_yn=="N"?"거절":"대기"}}</span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	, join_request_list_nodata : [
		'<tr>'
		, '<td class="text-center" style="padding:200px 0 !important;">가입요청 매니저님이 없습니다.</td>'
		, '</tr>'
	].join('')
};

/*	test	*/
hakwonTmpl.test = {
	noti : [
		'<div class="middle-box text-center animated fadeInRightBig">'
		, '	<h3 class="font-bold">테스트 push 메시지 입니다.</h3>'
		, '	<div class="error-desc">'
		, '		(입력 안하면 전체 발송)user_no(43:student01) : <input type="text" name="user_no" value="4"><br />'
		, '		메시지 : <input type="text" name="message" value=""><br />'
		, '		timeToLive : <input type="text" name="timeToLive" value=""><br />'
		, '		collapseKey : <input type="text" name="collapseKey" value="Y"><br />'
		, '		delayWhileIdle : <input type="text" name="delayWhileIdle" value="true/false"><br />'
		, '		<button type="button" ng-click="testMsg()">메시지 보내기</button>'
		, '	</div>'
		, '</div>'
	].join('')
	, mail : [
		'<div class="middle-box text-center animated fadeInRightBig">'
		, '	<h3 class="font-bold">테스트 메일 발송 입니다.</h3>'
		, '	<div class="error-desc">'
		, '		이메일 주소 : <input type="text" name="email_address" value=""><br />'
		, '		<button type="button" ng-click="testMail()">메일 보내기</button>'
		, '	</div>'
		, '</div>'
	].join('')
	, questionsMail : [
		'<div class="middle-box text-center animated fadeInRightBig">'
		, '	<h3 class="font-bold">문의 메일 입니다.</h3>'
		, '	<div class="error-desc">'
		, '		제목 : <input type="text" name="title" value="제목~"><br />'
		, '		email : <input type="text" name="email" value="bumworld@gmail.com"><br />'
		, '		연락처 : <input type="text" name="phone" value="02-789-4561"><br />'
		, '		내용 : <textarea name="content" >내용 입니다.</textarea><br />'
		, '		<button type="button" ng-click="sendQuestions()">문의 메일 보내기</button>'
		, '	</div>'
		, '</div>'
	].join('')
};


/*	관리자 문의	*/
hakwonTmpl.adminQuestion = {
	listForm : [
		'<div class="ibox m" data-view="data-div">'
		, '	<div class="ibox-content">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>번호</th>'
		, '					<th>제목</th>'
		, '					<th>학원명</th>'
		, '					<th>등록자</th>'
		, '					<th>등록일</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '			</tbody>'
		, '		</table>'
		, '		<div data-view="page-nav" class="text-center m-b-xl m-t-xl"></div>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopNotice) noticeList}}'
		, '	<tr>'
		, '		<td>{{= loopNotice.notice_no}}</td>'
		, '		<td>'
		, '			<a href="'+PageUrl.adminQuestion.view+'?notice_no={{= loopNotice.notice_no}}">{{= loopNotice.title}}({{= loopNotice.reply_count}})</a>'
		, '		</td>'
		, '		<td><span>{{= loopNotice.hakwon_name}}</span></td>'
		, '		<td><span>{{= loopNotice.reg_user_name}}({{= loopNotice.user_type_name}})</span></td>'
		, '		<td><span>{{= loopNotice.reg_date}}</span></td>'
		, '	</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'	<tr>'
		, '		<td colspan="3" class="box_nodata">등록된 관리자 문의가 없습니다.</td>'
		, '	</tr>'
	].join('')
	, viewForm : [
		'<div class="ibox m" data-view="data-view">'+hakwonTmpl.common.init+'</div>'
	].join('')
	, viewData : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>{{= noticeDetail.title}} <small>등록일 : {{= noticeDetail.reg_date}}</small></h2>'
		, '		<img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(noticeDetail.reg_user_photo_path, "photo", true)}}" width="30" height="30">'
		, '		<span class="badge .badge-plain">{{= noticeDetail.reg_user_type_name}}</span> {{= noticeDetail.reg_user_name}}'
		, '	</div>'
		, '	<div class="ibox-content">{{html noticeDetail.content}}</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="list" class="btn btn-primary">목록으로</button>'
		, '	</div>'

		, '<div class="ibox-content m-t">'
		, '	<!-- 댓글 쓰기 시작 -->'
		, '	<div class="comment_write has-success">'
		, '		<form action="">'
		, '			<textarea rows="3" cols="30" name="replyContent" class="form-control"></textarea>'
		, '			<button type="button" class="btn btn-primary btn-lg m-b" data-act="replyWrite">댓글입력</button>'
		, '		</form>'
		, '	</div>'
		, '	<!-- 댓글 쓰기 끝 -->'
		, '</div>'

		, '<!-- 댓글 리스트 -->'
		, '<div class="comment_list" data-view="comment_div"></div>'
		, '</div>'
	].join('')
	/*	리플	*/
	, replyRow : [
		'	{{each(i, loopReply) replyList }}'
		, '		<div class="feed-element" data-reply-no="{{= loopReply.reply_no}}">'
		, '			<span class="pull-left"><img alt="image" src="{{= hakwonCommon.createFilePullPath(loopReply.photo_file_path, "photo", true)}}" class="img-circle"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopReply.reg_date_long }}</span></small>'
		, '				<p><span class="badge .badge-plain">{{= loopReply.user_type_name }}</span> <strong>{{= loopReply.reg_user_name }}</strong> {{= loopReply.reg_user_id }}</p>'
		, '				<p class="message_body_text">{{html loopReply.reply_content}}</p>'
		, '			</div>'
		, '		</div>'
		, '	{{/each}}'
	].join('')
};


/*	문의 메일	*/
hakwonTmpl.questionsMail = {
	listForm : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="검색어 입력">'
		, '	<span class="input-group-btn"> <button type="button" ng-click="search()" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>번호</th>'
		, '					<th>제목</th>'
		, '					<th>이메일</th>'
		, '					<th>연락처</th>'
		, '					<th>등록일</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '			</tbody>'
		, '		</table>'
		, '		<div data-view="page-nav" class="text-center m-b-xl m-t-xl"></div>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopQuestionsMail) questionsMailList}}'
		, '	<tr>'
		, '		<td>{{= loopQuestionsMail.questions_no}}</td>'
		, '		<td>'
		, '			<a href="'+PageUrl.questionsMail.view+'?questionsNo={{= loopQuestionsMail.questions_no}}">{{= loopQuestionsMail.title}}</a>'
		, '		</td>'
		, '		<td><a href="mailto:{{= loopQuestionsMail.user_email}}">{{= loopQuestionsMail.user_email}}</a></td>'
		, '		<td><span>{{= loopQuestionsMail.phone}}</span></td>'
		, '		<td><span>{{= loopQuestionsMail.req_date}}</span></td>'
		, '	</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'	<tr>'
		, '		<td colspan="5" class="box_nodata">등록된 문의 메일이 없습니다.</td>'
		, '	</tr>'
	].join('')
	, viewForm : [
		'<div class="ibox m" data-view="data-view">'+hakwonTmpl.common.init+'</div>'
	].join('')
	, viewData : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>{{= questionsMailInfo.title}} <small>이메일 : <a href="mailto:{{= questionsMailInfo.user_email}}">{{= questionsMailInfo.user_email}}</a></small> <small>연락처 : {{= questionsMailInfo.phone}}</small> <small>등록일 : {{= questionsMailInfo.req_date}}</small></h2>'
		, '	</div>'
		, '	<div class="ibox-content">{{html questionsMailInfo.content}}</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="list" class="btn btn-primary">목록으로</button>'
		, '	</div>'
	].join('')
};

/*	메세지 뷰 폼	*/
hakwonTmpl.messageView = {
	/*	보낸 메세지 싱글 리스트 폼	*/
	sendMessageSingleListForm : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content message_page" data-view="data-view">'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	보낸 메세지 그룹 리스트 폼	*/
	, sendMessageGroupListForm : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content message_page" data-view="data-view">'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	보낸 메세지 그룹 리스트 row	*/
	, sendMessageGroupListRow : [
		'{{each(i, loopData) dataList}}'
		, '	<!-- 메세지 단위 시작 -->'
		, '	<div class="feed-element message_box">'
		, '		<a href="{{= PageUrl.message.sendGroupMessageDetail+"?messageNo="+loopData.message_no}}" class="media-body">'
		, '		<div class="media-body">'
		, '			<!-- 메세지 텍스트 시작 -->'
		, '			<span class="message_list_text">{{= loopData.title}}</span>'
		, '			<!-- 메세지 텍스트 끝 -->'
		, '			<small class="pull-right"><span class="text-muted">{{= loopData.send_date}}</span></small>'
		, '			<!-- 첨부 파일 영역 시작 -->'
		, '			<span class="m-t">'
		, '				<span><i class="fa fa-paperclip"></i> {{= loopData.file_count}} 개파일 첨부</span>'
		, '			</p>'
		, '		</div>'
		, '		</a>'
		, '	</div>'
		, '{{/each}}'
		, '	<!-- 메세지 단위 끝 -->'
	].join('')
	/*	보낸 메세지 개별 리스트 row	*/
	, sendMessageSingleListRow : [
		'{{each(i, loopData) dataList}}'
		, '	<!-- 메세지 단위 시작 -->'
		, '	<div class="feed-element message_box">'
		, '		<a href="{{= PageUrl.message.sendSingleMessageDetail+"?receiveNo="+loopData.receive_no}}" class="media-body">'
		, '			<span class="pull-left"><img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopData.receive_user_info.user_photo_path, "photo", true)}}"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopData.send_date}}</span> / {{= loopData.receive_date?"읽음("+loopData.receive_date+")":"읽기전"}}</small>'
		, '				<p><span class="badge .badge-plain">{{= loopData.receive_user_info.user_type_name}}</span> <strong>{{= loopData.receive_user_info.user_name}} / {{= loopData.title}}({{= loopData.reply_count}})</strong></p>'
		, '			</div>'
		, '		</a>'
		, '	</div>'
		, '{{/each}}'
		, '	<!-- 메세지 단위 끝 -->'
	].join('')
	/*	보낸 그룹 메세지 상세	*/
	, viewForm : [
		'<div class="ibox float-e-margins" data-view="data-view">'+hakwonTmpl.common.init+'</div>'
	].join('')
	/*	messageDetail, fileList*/
	, sendMessageGroupView : [
		'	<div class="ibox-title"><h2>내용</h2></div>'
		, '	<div class="ibox-content message_page">'
		, '		<!-- 메세지 단위 시작 -->'
		, '		<div class="feed-element">'
		, '			<!-- 메세지 텍스트 시작 -->'
		, '			<p class="message_body_text">{{html messageDetail.content}}</p>'
		, '			<!-- 메세지 텍스트 끝 -->'
		, '			<small class="pull-right"><span class="text-muted">{{= messageDetail.send_date}}</span></small>'
		, '		</div>'
		, '	</div>'
		, '	{{if fileList && fileList.length > 0}}'
		, '	<div class="ibox-title m-t"><h2>첨부파일</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 첨부 파일 영역 시작 -->'
		, '		<p class="m-t-xl">'
		, '			<span><i class="fa fa-paperclip"></i> {{= fileList.length}} 개파일 첨부</span>'
		, '		</p>'
		, '		<div class="attachment">'
		, '	{{each(i, loopFile) fileList}}'
		, '			<div class="file-box">'
		, '				<div class="file">'
		, '					<a href="{{= DefaultInfo.downPath+loopFile.file_path}}">'
		, '						<span class="corner"></span>'
		, '		{{if loopFile.image_yn == "Y" }}'
		, '						<div class="image">'
		, '							<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(loopFile.file_path, "attach", true)}}">'
		, '						</div>'
		, '		{{/if}}'
		, '		{{if loopFile.image_yn == "N" }}'
		, '						<div class="icon">'
		, '							<i class="fa fa-file"></i>'
		, '						</div>'
		, '		{{/if}}'
		, '						<div class="file-name">'
		, '							<p>{{= loopFile.file_name}}</p>'
		, '						</div>'
		, '					</a>'
		, '				</div>'
		, '			</div>'
		, '	{{/each}}'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '		<!-- 첨부 파일 영역 끝 -->'
		, '	</div>'
		, '	{{/if}}'
		, '	<div class="ibox-title m-t">'
		, '		<h2>받은대상</h2>'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '		<!-- 지역일 경우 -->'
		, '	{{if messageDetail.message_type == "area" }}'
		, '		<ul>'
		, '			<li>타입 : 지역</li>'
		, '			<li>시/도 : {{= messageTarget.sido=="all"?"전체":messageTarget.sido}}</li>'
		, '		{{if messageTarget["gugunList"] && messageTarget.gugunList.length > 0 }}'
		, '			<li>구/군 : {{= messageTarget.gugunList.toString()}}</li>'
		, '		{{/if}}'
		, '			<li>업종 : {{= messageTarget.hakwonCateListStr}}</li>'
		, '			<li>사용자 그룹 : {{= messageTarget.userTypeListStr}}</li>'
		, '		</ul>'
		, '	{{/if}}'
		, '	{{if messageDetail.message_type == "hakwonSearch" }}'
		, '		<!-- 학원일 경우 -->'
		, '		<ul>'
		, '			<li>타입 : 학원</li>'
		, '			<li>사용자 그룹 : {{= messageTarget.userTypeListStr}}</li>'
		, '			<li>학원명 : {{= messageTarget.hakwonListStr}}</li>'
		, '		</ul>'
		, '	{{/if}}'
		, '	</div>'
		, '	<div class="ibox-content text-right m-t">'
		, '		<button class="btn btn-default" type="button" data-act="goList" title="목록으로">목록으로</button>'
		, '	</div>'
	].join('')
	/*	messageDetail, replyList, fileList*/
	, sendMessageSingleView : [
		'	<div class="ibox-title">'
		, '		<h2 class="m-r">받은사람 : </h2>'
		, '		<img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(messageDetail.receive_user_info.user_photo_path, "photo", true)}}" width="30" height="30">'
		, '		<span class="badge .badge-plain">{{= messageDetail.receive_user_info.user_type_name}}</span> {{= messageDetail.receive_user_info.user_name}}'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '		<!-- 메세지 텍스트 시작 -->'
		, '		<p class="message_body_text">{{html messageDetail.content}}</p>'
		, '		<!-- 메세지 텍스트 끝 -->'
		, '		<small class="pull-right"><span class="text-muted">{{= messageDetail.send_date}}</span></small>'
		, '	</div>'
		, '	{{if fileList && fileList.length > 0}}'
		, '	<div class="ibox-title m-t"><h2>첨부파일</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 첨부 파일 영역 시작 -->'
		, '		<p class="m-t-xl">'
		, '			<span><i class="fa fa-paperclip"></i> {{= fileList.length}} 개파일 첨부</span>'
		, '		</p>'
		, '		<div class="attachment">'
		, '	{{each(i, loopFile) fileList}}'
		, '			<div class="file-box">'
		, '				<div class="file">'
		, '					<a href="{{= DefaultInfo.downPath+loopFile.file_path}}">'
		, '						<span class="corner"></span>'
		, '		{{if loopFile.image_yn == "Y" }}'
		, '						<div class="image">'
		, '							<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(loopFile.file_path, "attach", true)}}">'
		, '						</div>'
		, '		{{/if}}'
		, '		{{if loopFile.image_yn == "N" }}'
		, '						<div class="icon">'
		, '							<i class="fa fa-file"></i>'
		, '						</div>'
		, '		{{/if}}'
		, '						<div class="file-name">'
		, '							<p>{{= loopFile.file_name}}</p>'
		, '						</div>'
		, '					</a>'
		, '				</div>'
		, '			</div>'
		, '	{{/each}}'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '		<!-- 첨부 파일 영역 끝 -->'
		, '	</div>'
		, '	{{/if}}'
		, '	{{if messageDetail.message_type == "userSearch" }}'
		, '	<div class="ibox-title m-t">'
		, '		<h2>받은대상</h2>'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '		<!-- 사용자일 경우 -->'
		, '		<ul class="chosen_select">'
		, '	{{each(i, loopUser) messageTarget.userList}}'
		, '			<li><a href="{{= hakwonCommon.userDetailLink(loopUser.user_type, loopUser.user_no)}}"><img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopUser.user_photo_path, "photo", true)}}" alt="{{= loopUser.user_name}}" width="30" height="30"> {{= loopUser.user_name + "(" + loopUser.user_type_name + ")"}}</a></li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '	{{/if}}'
		, '	<div class="ibox-content text-right m-t">'
		, '		<button class="btn btn-default" data-act="goList" type="button" title="목록으로">목록으로</button>'
		, '	</div>'
		, '	<div class="ibox-title text-right m-t">'
		, '		<strong data-view="comment_count">0개</strong>의 댓글'
		, '	</div>'
		, '	<div class="comment_list" data-view="comment_list"></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 댓글 쓰기 시작 -->'
		, '		<div class="comment_write has-success">'
		, '			<textarea rows="3" name="replyContent" cols="30" class="form-control"></textarea>'
		, '			<button type="button" data-act="replyWrite" class="btn btn-primary btn-lg m-b">댓글입력</button>'
		, '		</div>'
		, '		<!-- 댓글 쓰기 끝 -->'
		, '	</div>'
	].join('')
	/*	리플	*/
	, replyRow : [
		'	{{each(i, loopReply) replyList }}'
		, '		<div class="feed-element {{= userAuth.userNo==loopReply.reg_user_no?"active":""}}" data-type="reply" data-reply-no="{{= loopReply.reply_no}}">'
		, '			<span class="pull-left"><img alt="image" src="{{= hakwonCommon.createFilePullPath(loopReply.photo_file_path, "photo", true)}}" class="img-circle"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopReply.reg_date_long }}</span></small>'
		, '				<p><span class="badge .badge-plain">{{= loopReply.user_type_name }}</span> <strong>{{= loopReply.reg_user_name }}</strong> {{= loopReply.reg_user_id }}</p>'
		, '				<p class="message_body_text">{{html loopReply.reply_content}}</p>'
		, '			</div>'
		, '		</div>'
		, '	{{/each}}'
	].join('')
	/*	첨부 파일	*/
	, attchFile : [
		'	<div class="file-box" data-file-no="{{= fileInfo.fileNo}}">'
		, '		<div class="file">'
		, '	{{if fileInfo.imageYn == "Y" }}'
		, '			<div class="image">'
		, '				<img alt="image" class="img-responsive" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+fileInfo.filePath}}">'
		, '			</div>'
		, '	{{/if}}'
		, '	{{if fileInfo.imageYn != "Y" }}'
		, '			<div class="icon"><i class="fa fa-file"></i></div>'
		, '	{{/if}}'
		, '			<div class="file-name">'
		, '				<p>{{= fileInfo.fileName}}</p>'
		, '			</div>'
		, '			<button type="button" class="btn btn-circle btn_file_del" title="삭제">X</button>'
		, '		</div>'
		, '	</div>'
	].join('')
};