/**
 * hakwon
 */
var hakwonTmpl = {
	/*	공통	*/
	common : {
		init : [
			'	<div class="sk-spinner sk-spinner-wave">'
			, '		<div class="sk-rect1"></div>'
			, '		<div class="sk-rect2"></div>'
			, '		<div class="sk-rect3"></div>'
			, '		<div class="sk-rect4"></div>'
			, '		<div class="sk-rect5"></div>'
			, '	</div>'
		].join('')
		, pageNav : [
 			'{{if pageList.length === 0 }}'
			, '	<button type="button" class="btn btn-white active">1</button>'
			, '{{/if}}'
			, '{{if pageList.length > 0 }}'
			, '		<button type="button" data-act="left" class="btn btn-white"><i class="fa fa-chevron-left"></i></button>'
			, '	{{each(i, loopPage) pageList}}'
			, '		<button type="button" class="btn btn-white {{= (currentPageNo==loopPage.pageNo)?"active":""}}">{{= loopPage.pageNo}}</button>'
			, '	{{/each}}'
			, '		<button type="button" data-act="right" class="btn btn-white"><i class="fa fa-chevron-right"></i> </button>'
			, '{{/if}}'
		].join('')
		/*	로그인	*/
		, login : [
			'	<div class="middle-box text-center loginscreen animated fadeInDown">'
			, '		<h1 class="logo-name"><small>HAKWONBAND</small><br>LOGIN</h1>'
			, '		<h3>Welcome to HAKWONBAND Manager</h3>'
			, '		<form class="m-t" role="form" action="">'
			, '			<div class="form-group">'
			, '				<input type="text" name="userId" value="" class="form-control m-b-xs" placeholder="아이디">'
			, '				<input type="password" name="userPass" value="" class="form-control" placeholder="비밀번호">'
			, '				<div class="checkbox i-checks">'
			, '					<label for="login_auto"> <input type="checkbox" name="loginSave" value="Y" id="login_auto"> 자동로그인</label>'
			, '					<label for="login_rememberid"> <input type="checkbox" name="idSave" value="Y" id="login_rememberid"> 아이디 기억</label>'
			, '				</div>'
			, '			</div>'
			, '			<button type="button" data-act="login" class="btn btn-primary btn-lg block full-width m-b">로그인</button>'
			, '			<button type="button" data-act="signUp" class="btn btn-info block full-width m-b">학원밴드 매니저 가입하기</button>'
			, '			<a href="'+PageUrl.findInfo+'"><small>아이디나 비밀번호가 생각나지 않는다면?</small></a>'
			, '		</form>'
			, '		<p class="m-t"> <small>HAKWONBAND &copy; 2015</small> </p>'
			, '	</div>'
		].join('')
		, videoHtml : [
			'<video width="320" height="240" controls>'
			, '	<source src="{{=videoUrl}}" type="video/mp4">'
			, '	Your browser does not support the video tag.'
			, '</video>'
		].join('')
	}
};
hakwonTmpl.main = [
	'메인 화면 입니다.'
].join('');

hakwonTmpl.leftMenu = {
	/*	사용자 프로필	*/
	userProfile : [
		'	<img alt="image" class="img-circle" src="{{= comm.userProfileImg(userAuth.profilePath)}}" width="100px" height="100px">'
		, '	<span class="block m-t-xs m-b text-white"> <strong class="font-bold">{{= userAuth.userName}}</strong> / {{= userAuth.userId}}</span>'
	].join('')
};

/*	대시 보드	*/
hakwonTmpl.dashBoard = {
	emptyDashBoard : [
		'<div class="middle-box text-center animated fadeInRightBig">'
		, '	<h3 class="font-bold">준비 중 입니다.</h3>'
		, '</div>'
	].join('')
};

hakwonTmpl.adBanner = {
	list : [
		'<div class="col-md-2 col-md-offset-3">'
		, '	<select name="depositYn" class="form-control">'
		, '		<option value="">결제 여부</option>'
		, '		<option value="Y">결제</option>'
		, '		<option value="N">미결제</option>'
		, '	</select>'
		, '</div>'
		, '<div class="col-md-4 input-group">'
		, '		<input type="text" name="searchText" class="form-control" placeholder="광고 제목으로 검색">'
		, '		<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '	</div>'
		, '	<div class="ibox m m-t-xl">'
		, '		<div class="ibox-content" data-view="data-div">'
		, '			<table class="table table-hover table_link">'
		, '				<thead>'
		, '					<tr>'
		, '						<th>번호</th>'
		, '						<th>제목</th>'
		, '						<th>학원명</th>'
		, '						<th>광고 사이즈</th>'
		, '						<th>결제여부</th>'
		, '						<th>취소여부</th>'
		, '						<th>관리자 중지</th>'
		, '						<th>광고노출여부</th>'
		, '					</tr>'
		, '				</thead>'
		, '				<tbody></tbody>'
		, '			</table>'
		, '			<div class="ibox-content text-center" style="padding:200px 0; display:none;">'
		, '				등록된 광고가 없습니다'
		, '			</div>'
		, '		</div>'
		, '		<div data-view="pagination" class="text-center m-b-xl m-t-xl"></div>'
		, '</div>'
	].join('')
	/*	리스트 로우	*/
	, listRow : [
		'{{each(i, loopAdvertiseInfo) advertiseReqList}}'
		, '<tr>'
		, '	<td><span>{{= loopAdvertiseInfo.advertise_req_no}}</span></td>'
		, '	<td><a href="#/edBanner/view?reqNo={{= loopAdvertiseInfo.advertise_req_no}}" data-req-no="{{= loopAdvertiseInfo.advertise_req_no}}" data-act="adBannerDetail">{{= loopAdvertiseInfo.title}}</a></td>'
		, '	<td><a href="#/hakwon/detail?hakwon_no={{= loopAdvertiseInfo.hakwon_no}}">{{= loopAdvertiseInfo.hakwon_name}}</a></td>'
		, '	<td><span>{{= loopAdvertiseInfo.banner_size}}칸</span></td>'
		, '	<td><span>{{= loopAdvertiseInfo.deposit_yn=="Y"?"입금 완료":"입금 확인 중"}}</span></td>'
		, '	<td><span>-</span></td>'
		, '	<td><span>{{= loopAdvertiseInfo.stop_admin_yn}}</span></td>'
		, '	<td><span>{{= (loopAdvertiseInfo.view_count > 0 && loopAdvertiseInfo.deposit_yn == "Y" && loopAdvertiseInfo.stop_admin_yn == "N" )?"노출중":"" }}</span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	/*	리스트 로우 nodata	*/
	, listRowNoData : [
		'<div class="ibox-content text-center" style="padding:200px 0;">'
		, '	등록된 광고가 없습니다'
		, '</div>'
	].join('')
	/*	광고 상세	*/
	, view : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>{{ reqDetailInfo.title }}</h2>'
		, '	</div>'
		, '	<div class="ibox-content ad_view">'
		, '		<h3 class="text_title">광고 정보</h3>'
		, '		<table class="table table-bordered table_center" data-view="table-view" summary="광고의 크기, 결제여부, 취소여부를 나타내는 표 입니다">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>학원명</th>'
		, '					<th>광고 영역 크기</th>'
		, '					<th>결제여부</th>'
		, '					<th>광고금액</th>'
		, '					<th>시도 / 구군</th>'
		, '					<th>취소여부</th>'
		, '					<th>관리자 중지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '				<tr>'
		, '					<td><a href="#/hakwon/detail?hakwon_no={{reqDetailInfo.hakwon_no}}">{{reqDetailInfo.hakwon_name}}</a></td>'
		, '					<td>{{reqDetailInfo.banner_size}}칸</td>'
		, '					<td>{{reqDetailInfo.deposit_yn=="Y"?"입금 완료":"미입금"}}</td>'
		, '					<td>{{CommUtil.numberWithCommas(reqDetailInfo.price)}}원</td>'
		, '					<td>{{reqDetailInfo.sido}} / {{reqDetailInfo.gugun}}</td>'
		, '					<td>{{reqDetailInfo.cancel_yn}}</td>'
		, '					<td>{{reqDetailInfo.stop_admin_yn}}</td>'
		, '				</tr>'
		, '			</tbody>'
		, '		</table>'

		, '		<h4 class="text_title">광고 이미지</h4>'
		, '		<img ng-src="{{reqDetailInfo.banner_web_path}}" class="ad_img" alt="광고 이미지">'

		, '		<h5 class="text_title">광고 현황 <small>현재 노출중 지역은 배경 컬러로 표시됩니다.</small></h5>'
		, '		<table summary="지역별 광고 기간 현황을 나타냅니다." class="table table-bordered  table_center">'
		, '			<thead>'
		, '				<tr>'
		, '					<td>동/읍/면</td>'
		, '					<td ng-repeat="loopViewMonth in viewMonthArray">{{CommUtil.yearMonthFormatter(loopViewMonth)}}</td>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '				<tr ng-repeat="loopLocalDongName in localDongNameArray">'
		, '					<td>{{loopLocalDongName}}</td>'
		, '					<td data-dong="{{loopLocalDongName}}" data-month="{{loopViewMonth}}" ng-repeat="loopViewMonth in viewMonthArray">'
		, '						<i style="display:none;" class="fa fa-check ad_check text-navy"></i>'
		, '					</td>'
		, '				</tr>'
		, '			</tbody>'
		, '		</table>'
		, '		<h4 class="text_title">광고 금액 정보</h4>'
		, '		<div class="table-responsive m-t">'
		, '			<table class="table invoice-table">'
		, '				<thead>'
		, '				<tr>'
		, '					<th>기간정보</th>'
		, '					<th>배너크기</th>'
		, '					<th>가격</th>'
		, '					<th>지역</th>'
		, '					<th>합계</th>'
		, '				</tr>'
		, '				</thead>'
		, '				<tbody>'
		, '				<tr ng-repeat="loopMonthPrice in monthPriceList">'
		, '					<td>{{CommUtil.yearMonthFormatter(loopMonthPrice.view_month)}}</td>'
		, '					<td>{{loopMonthPrice.banner_size}}칸</td>'
		, '					<td>{{CommUtil.numberWithCommas(loopMonthPrice.price)}}원</td>'
		, '					<td>{{loopMonthPrice.dong_count}}</td>'
		, '					<td>{{CommUtil.numberWithCommas(loopMonthPrice.total_price)}}</td>'
		, '				</tr>'
		, '				</tbody>'
		, '			</table>'
		, '		</div>'
		, '		<table class="table invoice-total">'
		, '			<tbody>'
		, '			<tr>'
		, '				<td><strong>합계 :</strong></td>'
		, '				<td>￦{{CommUtil.numberWithCommas(reqDetailInfo.price)}}</td>'
		, '			</tr>'
		, '			</tbody>'
		, '		</table>'
		, '		<div class="well m-t"><strong>입금계좌정보 : </strong>{{reqDetailInfo.bank_info}}</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" ng-click="goList()" style="float:left;">목록으로</button>'
		, '	</div>'
		, '</div>'
	].join('')
};

/*	관리자 문의	*/
hakwonTmpl.adminQuestion = {
	listForm : [
		'<div class="ibox m" data-view="data-div">'
		, '	<div class="ibox-content">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>번호</th>'
		, '					<th>제목</th>'
		, '					<th>등록일</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '			</tbody>'
		, '		</table>'
		, '		<div data-view="page-nav" class="text-center m-b-xl m-t-xl"></div>'
		, '		<div class="text-right">'
		, '			<button type="button" class="btn btn-primary" data-act="regist">관리자 문의 등록</button>'
		, '		</div>'
		, '	</div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopNotice) noticeList}}'
		, '	<tr>'
		, '		<td>{{= loopNotice.notice_no}}</td>'
		, '		<td>'
		, '			<a href="'+PageUrl.common.adminQuestionView+'?notice_no={{= loopNotice.notice_no}}">{{= loopNotice.title}}</a>'
		, '		</td>'
		, '		<td><span>{{= loopNotice.reg_date}}</span></td>'
		, '	</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'	<tr>'
		, '		<td colspan="3" class="box_nodata">등록된 관리자 문의가 없습니다.</td>'
		, '	</tr>'
	].join('')
	, viewForm : [
		'<div class="ibox m" data-view="data-view">'+hakwonTmpl.common.init+'</div>'
	].join('')
	, viewData : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>{{= noticeDetail.title}} <small>등록일 : {{= noticeDetail.reg_date}}</small></h2>'
		, '	</div>'
		, '	<div class="ibox-content">{{html noticeDetail.content}}</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="noticeDel" class="btn btn-default" ng-if="checkAuthType()">삭제하기</button>'
		, '		<button type="button" data-act="noticeEdit" class="btn btn-werning" ng-if="checkAuthType()">수정하기</button>'
		, '		<button type="button" data-act="list" class="btn btn-primary">목록으로</button>'
		, '	</div>'

		, '<div class="ibox-content m-t">'
		, '	<!-- 댓글 쓰기 시작 -->'
		, '	<div class="comment_write has-success">'
		, '		<form action="">'
		, '			<textarea rows="3" cols="30" name="replyContent" class="form-control"></textarea>'
		, '			<button type="button" class="btn btn-primary btn-lg m-b" data-act="replyWrite">댓글입력</button>'
		, '		</form>'
		, '	</div>'
		, '	<!-- 댓글 쓰기 끝 -->'
		, '</div>'

		, '<!-- 댓글 리스트 -->'
		, '<div class="comment_list"></div>'
		, '</div>'
	].join('')
	/*	리플	*/
	, replyRow : [
		'	{{each(i, loopReply) replyList }}'
		, '		<div class="feed-element" data-reply-no="{{= loopReply.reply_no}}">'
		, '			<span class="pull-left"><img alt="image" src="{{= hakwonCommon.createFilePullPath(loopReply.photo_file_path, "photo")}}" class="img-circle"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopReply.reg_date_long }}</span></small>'
		, '				<p><span class="badge .badge-plain">{{= loopReply.user_type_name }}</span> <strong>{{= loopReply.reg_user_name }}</strong> {{= loopReply.reg_user_id }}</p>'
		, '				<p class="message_body_text">{{html loopReply.reply_content}}</p>'
		, '			</div>'
		, '		</div>'
		, '	{{/each}}'
	].join('')
};


/*	학원	*/
hakwonTmpl.hakwon = {
	/*	학원 리스트	*/
	list : [
		'<div class="col-md-2 col-md-offset-3">'
		, '	<select name="searchSido" class="form-control" ng-model="searchSido" ng-change="sidoSelect()" ng-options="sidoVal for sidoVal in sidoArray track by sidoVal">'
		, '		<option value="">시도 전체</option>'
		, '	</select>'
		, '	<select name="searchGugun" class="form-control">'
		, '		<option value="">구군 전체</option>'
		, '	</select>'
		, '	<select name="searchCateCode" class="form-control" ng-change="cateChange()" ng-model="searchCateCode" ng-options="hakwonCate.cateCode as hakwonCate.cateName for hakwonCate in hakwonCateList track by hakwonCate.cateCode">'
		, '		<option value="">카테고리</option>'
		, '	</select>'
		, '</div>'
		, '<div class="col-md-4 input-group">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="학원명 또는 원장명(아이디)">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>학원번호</th>'
		, '					<th>학원명</th>'
		, '					<th>2달전</th>'
		, '					<th>1달전</th>'
		, '					<th>이번달</th>'
		, '					<th>학원 상태</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody></tbody>'
		, '		</table>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopHakwon) hakwonList}}'
		, '	<tr>'
		, '		<td><span>{{= loopHakwon.hakwon_no}}</span></td>'
		, '		<td>'
		, '			<a href="{{= PageUrl.hakwon.detail}}?hakwon_no={{= loopHakwon.hakwon_no}}">'
		, '				<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopHakwon.logo_file_path, "hakwon", true) }}" alt="" width="30" height="30">{{= loopHakwon.hakwon_name }}'
		, '			</a>'
		, '		</td>'
		, '		<td>{{= loopHakwon.viewMonth00}}</td>'
		, '		<td>{{= loopHakwon.viewMonth01}}</td>'
		, '		<td>{{= loopHakwon.viewMonth02}}</td>'
		, '		<td>{{= loopHakwon.hakwon_status_name}}</td>'
		, '	</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'	<tr>'
		, '		<td colspan="6" class="box_nodata">등록된 광고가 없습니다.</td>'
		, '	</tr>'
	].join('')
	/*	학원상세폼	*/
	, hakwonDetailForm : [
		'<div class="ibox m" data-view="data-view">'
		, hakwonTmpl.common.init
		, '</div>'
	].join('')
	/*	학원상세 소개 수정	*/
	, hakwonIntroUpdate : [
		'	<div class="ibox-title">'
		, '		<h2>학원 소개 수정</h2>'
		, '	</div>'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">내용</label>'
		, '			<div class="col-sm-11">'
		, '				<textarea cols="140" data-lib="editor" rows="10" class="form-control">{{= hakwonInfo.introduction }}</textarea>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">지도첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="input-group">'
		, '					<input type="text" name="daumMapHtml" class="form-control">'
		, '					<span class="input-group-btn"> <button type="button" data-act="daumMapInsert" class="btn btn-primary">지도삽입</button> </span>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">Youtube 동영상 첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="input-group">'
		, '					<input type="text" name="youtubeID" class="form-control">'
		, '					<span class="input-group-btn"> <button type="button" data-act="youtubeInsert" placeholder="Youtube 동영상 코드를 입력해 주세요." class="btn btn-primary">동영상 삽입</button> </span>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" class="input_file" data-act="file_upload" multiple>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">첨부파일</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="attachment" data-list="attachment">'
		, '				{{if fileList && fileList.length > 0}}'
		, '				{{each(i, loopFile) fileList}}'
		, '					<div class="file-box" data-file-no="{{= loopFile.file_no}}">'
		, '						<div class="file">'
		, '					{{if loopFile.image_yn == "Y" }}'
		, '							<div class="image">'
		, '								<img alt="image" class="img-responsive" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+loopFile.file_path}}">'
		, '							</div>'
		, '					{{/if}}'
		, '					{{if loopFile.image_yn != "Y" }}'
		, '							{{if loopFile.file_ext_type.indexOf("video") == 0 }}'
		, '							<div class="icon" data-file-type="video" data-file-url="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+loopFile.file_path}}">'
		, '								<i class="fa fa-file"></i>'
		, '							</div>'
		, '							{{/if}}'
		, '							{{if loopFile.file_ext_type.indexOf("video") != 0 }}'
		, '							<div class="icon">'
		, '								<i class="fa fa-file"></i>'
		, '							</div>'
		, '							{{/if}}'
		, '					{{/if}}'
		, '							<div class="file-name">'
		, '								<p>{{= loopFile.file_name}}</p>'
		, '							</div>'
		, '							<button type="button" data-file-no="{{= loopFile.file_no}}" data-act="fileDel" class="btn btn-circle btn_file_del" title="삭제">X</button>'
		, '						</div>'
		, '					</div>'
		, '				{{/each}}'
		, '				{{/if}}'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" data-act="introUpdateCancel">취소하기</button>'
		, '		<button type="button" class="btn btn-primary" data-act="introUpdateSave">등록하기</button>'
		, '		<button type="button" class="btn btn-primary" data-act="introUpdatePreview">미리보기</button>'
		, '	</div>'
	].join('')
};

/*	원장	*/
hakwonTmpl.master = {
	/*	원장 상세	*/
	viewForm : ['<div class="col-md-8 col-md-offset-2" data-view="data-view">'+hakwonTmpl.common.init+'</div>'].join('')
	, viewData : [
		'	<div class="widget-head-color-box blue-bg p-lg text-center">'
		, '		<h2 class="font-bold">{{= userInfo.user_name}}</h2>'
		, '		<img src="{{= hakwonCommon.createFilePullPath(userInfo.photo_file_path, "photo", true)}}" class="circle-border m-md img-responsive" alt="{{= userInfo.user_name}}" width="300">'
		, '		<p>{{= userInfo.user_gender_name}} / {{= !userInfo.user_age||userInfo.user_age==0?"생일 미입력":userInfo.user_age+"세"}}</p>'
		, '	</div>'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">연락정보</h3>'
		, '		<div class="row">'
		, '			<div class="col-md-10">'
		, '				<ul>'
		, '					<li>이메일 : <a href="mailto:{{= userInfo.user_email}}">{{= userInfo.user_email}}</a></li>'
		, '					<li>전화번호 : <a href="tel:{{= userInfo.tel1_no}}">{{= userInfo.tel1_no}}</a></li>'
		, '					<li>가입 일자 : {{= userInfo.reg_date}}</li>'
		, '				</ul>'
		, '			</div>'
		, '			<div class="col-md-2 text-right"><button class="btn btn-default btn_message" onclick="alert(\'준비 중 입니다.\');" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="text-right m-t">'
		, '		<button class="btn btn-default" data-act="list" type="button">이전</button>'
		, '	</div>'
	].join('')
};


hakwonTmpl.message = {
	/*	첨부 파일	*/
	attchFile : [
		'	<div class="file-box" data-file-no="{{= fileInfo.fileNo}}">'
		, '		<div class="file">'
		, '	{{if fileInfo.imageYn == "Y" }}'
		, '			<div class="image">'
		, '				<img alt="image" class="img-responsive" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+fileInfo.filePath}}">'
		, '			</div>'
		, '	{{/if}}'
		, '	{{if fileInfo.imageYn != "Y" }}'
		, '			<div class="icon"><i class="fa fa-file"></i></div>'
		, '	{{/if}}'
		, '			<div class="file-name">'
		, '				<p>{{= fileInfo.fileName}}</p>'
		, '			</div>'
		, '			<button type="button" class="btn btn-circle btn_file_del" title="삭제">X</button>'
		, '		</div>'
		, '	</div>'
	].join('')
	/*	검색 결과	*/
	, searchData : [
		'{{each(i, searchUser) searchList}}'
		, '<li>'
		, '	<span class="student_add_box">'
		, '		<img class="img-circle" src="{{= comm.userProfileImg(searchUser.user_photo_path)}}" alt="프로필" width="35" height="35">'
		, '		<strong class="name">{{= searchUser.user_name}}</strong> {{= searchUser.hakwon_name}} / {{= searchUser.user_gender=="M"?"남자":"여자"}} / {{= !searchUser.user_age||searchUser.user_age==0?"생일 미입력":searchUser.user_age+"세"}}'
		, '		<button type="button" data-val="{{= searchUser.user_name + CommonConstant.ChDiv.CH_DEL + searchUser.user_no + CommonConstant.ChDiv.CH_DEL + searchUser.hakwon_no + CommonConstant.ChDiv.CH_DEL + searchUser.hakwon_name}}" data-act="target" class="btn btn-default btn-sm">추가</button>'
		, '	</span>'
		, '</li>'
		, '{{/each}}'
	].join('')
	/*	선택 타겟	*/
	, choiceTarget : [
		'<li data-hakwon-no="{{= target.hakwon_no}}">{{= target.hakwon_name}} {{= target.user_name}} <button type="button" class="btn_x" data-act="choiceTargetDel" title="삭제">x</button></li>'
	].join('')
	/*	메세지 보내기	*/
	, sendForm : [
		'<div class="ibox">'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">전송대상타입</label>'
		, '			<div class="col-sm-11">'
		, '				<select name="targetType" class="form-control m-b">'
		, '					<option value="hakwonAll">학원 원장님 전체</option>'
		, '					<option value="search">검색</option>'
		, '				</select>'
		, '			</div>'
		, '		</div>'
		, '		<!-- 상단 셀렉트 박스에서 이름 검새 후 메세지 보내기 선택하면 나오는 영역 시작 -->'
		, '		<div class="form-group" data-target-form="Y" data-target-type="search" style="display:none;">'
		, '			<label class="col-sm-1 control-label">검색하기</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="input-group">'
		, '					<input type="text" name="searchText" class="form-control" placeholder="학원명 및 원장님 이름 검색"> <span class="input-group-btn"> <button type="button" class="btn btn-primary" data-act="messageTargetSearch">검색하기</button></span>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<!-- 검색하기 버튼 클릭시 결과 나타남. 클릭 전에는 나타나지 않음 -->'
		, '		<div class="form-group" data-target-form="Y" data-target-type="search" data-view="searchResult" style="display:none;">'
		, '			<label class="col-sm-1 control-label">검색결과</label>'
		, '			<div class="col-sm-11">'
		, '				<ul class="search_name_list"></ul>'
		, '			</div>'
		, '		</div>'
		, '		<!-- 상단 셀렉트 박스에서 이름 검새 후 메세지 보내기 선택하면 나오는 영역 끝 -->'
		, '		<div class="form-group" data-target-form="Y" data-target-type="search" data-view="searchTarget" style="display:none;">'
		, '			<label class="col-sm-1 control-label">선택자</label>'
		, '			<div class="col-sm-11">'
		, '				<ul class="chosen_select"></ul>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">내용</label>'
		, '			<div class="col-sm-11">'
		, '				<textarea cols="140" rows="10" name="messageContent" class="form-control"></textarea>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" class="input_file" data-act="file_upload" multiple>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">첨부파일</label>'
		, '			<div class="col-sm-11">'
		, '				<p>'
		, '					<span><i class="fa fa-paperclip"></i> 0개파일 첨부</span>'
		, '				</p>'
		, '				<div class="attachment">'
		, '					<div class="clearfix"></div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" data-act="cancel">취소하기</button>'
		, '		<button type="button" class="btn btn-primary" data-act="messageSend">등록하기</button>'
		, '	</div>'
		, '</div>'
	].join('')
};



/*	메세지 뷰 폼	*/
hakwonTmpl.messageView = {
	/*	보낸 메세지 싱글 리스트 폼	*/
	sendMessageSingleListForm : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content message_page" data-view="data-view">'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	보낸 메세지 그룹 리스트 폼	*/
	, sendMessageGroupListForm : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content message_page" data-view="data-view">'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	받은 메세지 리스트 폼	*/
	, receiveMessageListForm : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-title" style="display:none;" data-view="receiveMessageListTitle"></div>'
		, '	<div class="ibox-content message_page" data-view="data-view">'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	보낸 메세지 그룹 리스트 row	*/
	, sendMessageGroupListRow : [
		'{{each(i, loopData) dataList}}'
		, '	<!-- 메세지 단위 시작 -->'
		, '	<div class="feed-element message_box">'
		, '		<a href="{{= PageUrl.message.sendGroupMessageDetail+"?messageNo="+loopData.message_no}}" class="media-body">'
		, '		<div class="media-body">'
		, '			<!-- 메세지 텍스트 시작 -->'
		, '			<span class="message_list_text">'
		, '				{{= loopData.title}}'
		, '			</span>'
		, '			<!-- 메세지 텍스트 끝 -->'
		, '			<small class="pull-right"><span class="text-muted">{{= loopData.send_date}}</span></small>'
		, '			<!-- 첨부 파일 영역 시작 -->'
		, '			<span class="m-t">'
		, '				<span><i class="fa fa-paperclip"></i> {{= loopData.file_count}} 개파일 첨부</span>'
		, '			</p>'
		, '		</div>'
		, '		</a>'
		, '	</div>'
		, '{{/each}}'
		, '	<!-- 메세지 단위 끝 -->'
	].join('')
	/*	보낸 메세지 개별 리스트 row	*/
	, sendMessageSingleListRow : [
		'{{each(i, loopData) dataList}}'
		, '	<!-- 메세지 단위 시작 -->'
		, '	<div class="feed-element message_box">'
		, '		<a href="{{= PageUrl.message.sendSingleMessageDetail+"?receiveNo="+loopData.receive_no}}">'
		, '			<span class="pull-left"><img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopData.receive_user_info.user_photo_path, "photo", true)}}"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopData.send_date}}</span> / {{= loopData.receive_date?"읽음("+loopData.receive_date+")":"읽기전"}}</small>'
		, '				<p><span class="badge .badge-plain">{{= loopData.receive_user_info.user_type_name}}</span> <strong>{{= loopData.receive_user_info.user_name}} / {{= loopData.title}}</strong> ({{= loopData.reply_count}})</p>'
		, '				<!-- 첨부 파일 영역 시작 -->'
		, '				<p><span><i class="fa fa-paperclip"></i> {{= loopData.file_count}} 개파일 첨부</span></p>'
		, '				<div class="attachment">'
		, '				</div>'
		, '				<!-- 첨부 파일 영역 끝 -->'
		, '				<!-- 댓글 영역 시작 -->'
		, '				<div class="comment_box">'
		, '					<div class="comment_count text-right"><i class="fa fa-comment"></i> {{= loopData.reply_count}}개의 댓글</div>'
		, '				</div>'
		, '				<!-- 댓글 영역 끝 -->'
		, '			</div>'
		, '		</a>'
		, '	</div>'
		, '{{/each}}'
		, '	<!-- 메세지 단위 끝 -->'
	].join('')
	/*	받은 메세지 리스트 row	*/
	, receiveMessageListRow : [
		'{{each(i, loopData) dataList}}'
		, '	<!-- 메세지 단위 시작 -->'
		, '	<div class="feed-element message_box">'
		, '		<a href="{{= PageUrl.message.receiveMessageDetail+"?receiveNo="+loopData.receive_no}}">'
		, '			<span class="pull-left"><img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopData.send_user_info.user_photo_path, "photo", true)}}"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopData.send_date}}</span> / {{= loopData.receive_date?"읽음":"읽기전"}}</small>'
		, '				<p>'
		, '					<span class="badge .badge-plain">{{= loopData.send_user_info.user_type_name}}</span> '
		, '					<strong>{{= loopData.send_user_info.user_name}} / {{= loopData.title}}</strong> ({{= loopData.reply_count}})'
		, '				</p>'
		, '				<!-- 첨부 파일 영역 시작 -->'
		, '				<p><span><i class="fa fa-paperclip"></i> {{= loopData.file_count}} 개파일 첨부</span></p>'
		, '				<div class="attachment">'
		, '				</div>'
		, '				<!-- 첨부 파일 영역 끝 -->'
		, '				<!-- 댓글 영역 시작 -->'
		, '				<div class="comment_box">'
		, '					<div class="comment_count text-right"><i class="fa fa-comment"></i> {{= loopData.reply_count}}개의 댓글</div>'
		, '				</div>'
		, '				<!-- 댓글 영역 끝 -->'
		, '			</div>'
		, '		</a>'
		, '	</div>'
		, '{{/each}}'
		, '	<!-- 메세지 단위 끝 -->'
	].join('')
	/*	보낸 그룹 메세지 상세	*/
	, viewForm : [
		'<div class="ibox float-e-margins" data-view="data-view">'+hakwonTmpl.common.init+'</div>'
	].join('')
	/*	messageDetail, fileList*/
	, sendMessageGroupView : [
		'	<div class="ibox-title"><h2>내용</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 메세지 텍스트 시작 -->'
		, '		<p class="message_body_text">{{html messageDetail.content}}</p>'
		, '		<!-- 메세지 텍스트 끝 -->'
		, '		<small class="pull-right"><span class="text-muted">{{= messageDetail.send_date}}</span></small>'
		, '	</div>'
		, '	{{if fileList && fileList.length > 0}}'
		, '	<div class="ibox-title m-t"><h2>첨부파일</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 첨부 파일 영역 시작 -->'
		, '		<p class="m-t-xl">'
		, '			<span><i class="fa fa-paperclip"></i> {{= fileList.length}} 개파일 첨부</span>'
		, '		</p>'
		, '		<div class="attachment">'
		, '	{{each(i, loopFile) fileList}}'
		, '			<div class="file-box">'
		, '				<div class="file">'
		, '					<a href="{{= DefaultInfo.downPath+loopFile.file_path}}">'
		, '						<span class="corner"></span>'
		, '		{{if loopFile.image_yn == "Y" }}'
		, '						<div class="image">'
		, '							<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(loopFile.file_path, "attach", true)}}">'
		, '						</div>'
		, '		{{/if}}'
		, '		{{if loopFile.image_yn == "N" }}'
		, '						<div class="icon">'
		, '							<i class="fa fa-file"></i>'
		, '						</div>'
		, '		{{/if}}'
		, '						<div class="file-name">'
		, '							<p>{{= loopFile.file_name}}</p>'
		, '						</div>'
		, '					</a>'
		, '				</div>'
		, '			</div>'
		, '	{{/each}}'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '		<!-- 첨부 파일 영역 끝 -->'
		, '	</div>'
		, '	{{/if}}'
		, '	<div class="ibox-title m-t">'
		, '		<h2>받은대상</h2>'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '	{{if messageDetail.message_type == "class" }}'
		, '		<ul>'
		, '			<li>타입 : 반 대상</li>'
		, '			<li>반 리스트 : {{= messageTarget.targetClassStr}}</li>'
		, '			<li>사용자 그룹 : {{= messageTarget.userTypeListStr}}</li>'
		, '		</ul>'
		, '	{{/if}}'
		, '	{{if messageDetail.message_type == "userGroup" }}'
		, '		<ul>'
		, '			<li>타입 : 사용자 그룹</li>'
		, '			<li>사용자 그룹 : {{= messageTarget.userTypeListStr}}</li>'
		, '		</ul>'
		, '	{{/if}}'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '		<!-- 사용자일 경우 -->'
		, '		<ul class="chosen_select">'
		, '	{{each(i, loopUser) receiveUserList}}'
		, '			<li><a href="{{= hakwonCommon.userDetailLink(loopUser.user_type, loopUser.user_no)}}" title="{{= loopUser.receive_date}}"><img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopUser.user_photo_path, "photo", true)}}" alt="{{= loopUser.user_name}}" width="30" height="30"> {{= loopUser.user_name + "(" + loopUser.user_type_name + ") "+(loopUser.receive_date?"읽음":"안읽음")}}</a></li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '	<div class="ibox-content text-right m-t">'
		, '		<button class="btn btn-default" type="button" data-act="goList" title="목록으로">목록으로</button>'
		, '	</div>'
	].join('')
	/*	messageDetail, replyList, fileList*/
	, sendMessageSingleView : [
		'	<div class="ibox-title">'
		, '		<h2 class="m-r">받은사람 : </h2>'
		, '		<img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(messageDetail.receive_user_info.user_photo_path, "photo", true)}}" width="30" height="30">'
		, '		<span class="badge .badge-plain">{{= messageDetail.receive_user_info.user_type_name}}</span> {{= messageDetail.receive_user_info.user_name}}'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '		<!-- 메세지 텍스트 시작 -->'
		, '		<p class="message_body_text">{{html messageDetail.content}}</p>'
		, '		<!-- 메세지 텍스트 끝 -->'
		, '		<small class="pull-right"><span class="text-muted">{{= messageDetail.send_date}}</span></small>'
		, '	</div>'
		, '	{{if fileList && fileList.length > 0}}'
		, '	<div class="ibox-title m-t"><h2>첨부파일</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 첨부 파일 영역 시작 -->'
		, '		<p class="m-t-xl">'
		, '			<span><i class="fa fa-paperclip"></i> {{= fileList.length}} 개파일 첨부</span>'
		, '		</p>'
		, '		<div class="attachment">'
		, '	{{each(i, loopFile) fileList}}'
		, '			<div class="file-box">'
		, '				<div class="file">'
		, '					<a href="{{= DefaultInfo.downPath+loopFile.file_path}}">'
		, '						<span class="corner"></span>'
		, '		{{if loopFile.image_yn == "Y" }}'
		, '						<div class="image">'
		, '							<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(loopFile.file_path, "attach", true)}}">'
		, '						</div>'
		, '		{{/if}}'
		, '		{{if loopFile.image_yn == "N" }}'
		, '						<div class="icon">'
		, '							<i class="fa fa-file"></i>'
		, '						</div>'
		, '		{{/if}}'
		, '						<div class="file-name">'
		, '							<p>{{= loopFile.file_name}}</p>'
		, '						</div>'
		, '					</a>'
		, '				</div>'
		, '			</div>'
		, '	{{/each}}'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '		<!-- 첨부 파일 영역 끝 -->'
		, '	</div>'
		, '	{{/if}}'
		, '	<div class="ibox-content text-right m-t">'
		, '		<button class="btn btn-default" data-act="goList" type="button" title="목록으로">목록으로</button>'
		, '	</div>'
		, '	<div class="ibox-title text-right m-t">'
		, '		<strong data-view="comment_count">0개</strong>의 댓글'
		, '	</div>'
		, '	<div class="comment_list" data-view="comment_list"></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 댓글 쓰기 시작 -->'
		, '		<div class="comment_write has-success">'
		, '			<textarea rows="3" name="replyContent" cols="30" class="form-control"></textarea>'
		, '			<button type="button" data-act="replyWrite" class="btn btn-primary btn-lg m-b">댓글입력</button>'
		, '		</div>'
		, '		<!-- 댓글 쓰기 끝 -->'
		, '	</div>'
	].join('')
	/*	받은 메세지 상세	*/
	, receiveMessageView : [
		, '	<div class="ibox-title">'
		, '		<h2 class="m-r">보낸사람 : </h2>'
		, '		<img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(messageDetail.send_user_info.user_photo_path, "photo", true)}}" width="30" height="30">'
		, '		<span class="badge .badge-plain">{{= messageDetail.send_user_info.user_type_name}}</span> {{= messageDetail.send_user_info.user_name}}'
		, '	</div>'
		, '	<div class="ibox-content message_page">'
		, '		<!-- 메세지 텍스트 시작 -->'
		, '		<p class="message_body_text">{{html messageDetail.content}}</p>'
		, '		<!-- 메세지 텍스트 끝 -->'
		, '		<small class="pull-right"><span class="text-muted">{{= messageDetail.send_date}}</span></small>'
		, '	</div>'
		, '	{{if fileList && fileList.length > 0}}'
		, '	<div class="ibox-title m-t"><h2>첨부파일</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 첨부 파일 영역 시작 -->'
		, '		<p class="m-t-xl">'
		, '			<span><i class="fa fa-paperclip"></i> {{= fileList.length}} 개파일 첨부</span>'
		, '		</p>'
		, '		<div class="attachment">'
		, '	{{each(i, loopFile) fileList}}'
		, '			<div class="file-box">'
		, '				<div class="file">'
		, '					<a href="{{= DefaultInfo.downPath+loopFile.file_path}}">'
		, '						<span class="corner"></span>'
		, '		{{if loopFile.image_yn == "Y" }}'
		, '						<div class="image">'
		, '							<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(loopFile.file_path, "attach", true)}}">'
		, '						</div>'
		, '		{{/if}}'
		, '		{{if loopFile.image_yn == "N" }}'
		, '						<div class="icon">'
		, '							<i class="fa fa-file"></i>'
		, '						</div>'
		, '		{{/if}}'
		, '						<div class="file-name">'
		, '							<p>{{= loopFile.file_name}}</p>'
		, '						</div>'
		, '					</a>'
		, '				</div>'
		, '			</div>'
		, '	{{/each}}'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '		<!-- 첨부 파일 영역 끝 -->'
		, '	</div>'
		, '	{{/if}}'
		, '	<div class="ibox-content text-right m-t">'
		, '		<button class="btn btn-default" data-act="goList" type="button" title="목록으로">목록으로</button>'
		, '	</div>'
		, '	{{if messageDetail.group_yn == "N" }}'
		, '	<div class="ibox-title text-right m-t">'
		, '		<strong data-view="comment_count">0개</strong>의 댓글'
		, '	</div>'
		, '	<div class="comment_list" data-view="comment_list"></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 댓글 쓰기 시작 -->'
		, '		<div class="comment_write has-success">'
		, '			<textarea rows="3" name="replyContent" cols="30" class="form-control"></textarea>'
		, '			<button type="button" data-act="replyWrite" class="btn btn-primary btn-lg m-b">댓글입력</button>'
		, '		</div>'
		, '		<!-- 댓글 쓰기 끝 -->'
		, '	</div>'
		, '	{{/if}}'
	].join('')
	/*	리플	*/
	, replyRow : [
		'	{{each(i, loopReply) replyList }}'
		, '		<div class="feed-element {{= userAuth.userNo==loopReply.reg_user_no?"active":""}}" data-type="reply" data-reply-no="{{= loopReply.reply_no}}">'
		, '			<span class="pull-left"><img alt="image" src="{{= hakwonCommon.createFilePullPath(loopReply.photo_file_path, "photo", true)}}" class="img-circle"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopReply.reg_date_long }}</span></small>'
		, '				<p><span class="badge .badge-plain">{{= loopReply.user_type_name }}</span> <strong>{{= loopReply.reg_user_name }}</strong> {{= loopReply.reg_user_id }}</p>'
		, '				<p class="message_body_text">{{html loopReply.reply_content}}</p>'
		, '			</div>'
		, '		</div>'
		, '	{{/each}}'
	].join('')
	/*	첨부 파일	*/
	, attchFile : [
		'	<div class="file-box" data-file-no="{{= fileInfo.fileNo}}">'
		, '		<div class="file">'
		, '	{{if fileInfo.imageYn == "Y" }}'
		, '			<div class="image">'
		, '				<img alt="image" class="img-responsive" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+fileInfo.filePath}}">'
		, '			</div>'
		, '	{{/if}}'
		, '	{{if fileInfo.imageYn != "Y" }}'
		, '			<div class="icon"><i class="fa fa-file"></i></div>'
		, '	{{/if}}'
		, '			<div class="file-name">'
		, '				<p>{{= fileInfo.fileName}}</p>'
		, '			</div>'
		, '			<button type="button" class="btn btn-circle btn_file_del" title="삭제">X</button>'
		, '		</div>'
		, '	</div>'
	].join('')
};