/**
 * hakwon
############################################################
# 2015-06-30 03
############################################################
 */
var hakwonTmpl = {
	/*	공통	*/
	common : {
		init : [
			'	<div class="sk-spinner sk-spinner-wave">'
			, '		<div class="sk-rect1"></div>'
			, '		<div class="sk-rect2"></div>'
			, '		<div class="sk-rect3"></div>'
			, '		<div class="sk-rect4"></div>'
			, '		<div class="sk-rect5"></div>'
			, '	</div>'
		].join('')
		, pageNav : [
 			'{{if pageList.length === 0 }}'
			, '	<button type="button" class="btn btn-white active">1</button>'
			, '{{/if}}'
			, '{{if pageList.length > 0 }}'
			, '		<button type="button" data-act="left" class="btn btn-white"><i class="fa fa-chevron-left"></i></button>'
			, '	{{each(i, loopPage) pageList}}'
			, '		<button type="button" class="btn btn-white {{= (currentPageNo==loopPage.pageNo)?"active":""}}">{{= loopPage.pageNo}}</button>'
			, '	{{/each}}'
			, '		<button type="button" data-act="right" class="btn btn-white"><i class="fa fa-chevron-right"></i> </button>'
			, '{{/if}}'
		].join('')
		/*	로그인	*/
		, login : [
			'	<div class="middle-box text-center loginscreen animated fadeInDown">'
			, '		<h1 class="logo-name"><small>HAKWONBAND</small><br>LOGIN</h1>'
			, '		<h3>Welcome to HAKWONBAND</h3>'
			, '		<form class="m-t" role="form" action="">'
			, '			<div class="form-group">'
			, '				<input type="text" name="userId" value="" class="form-control m-b-xs" placeholder="아이디">'
			, '				<input type="password" name="userPass" value="" class="form-control" placeholder="비밀번호">'
			, '				<div class="checkbox i-checks">'
			, '					<label for="login_auto"> <input type="checkbox" name="loginSave" value="Y" id="login_auto"> 자동로그인</label>'
			, '					<label for="login_rememberid"> <input type="checkbox" name="idSave" value="Y" id="login_rememberid"> 아이디 기억</label>'
			, '				</div>'
			, '			</div>'
			, '			<button type="button" data-act="login" class="btn btn-primary btn-lg block full-width m-b">로그인</button>'
			, '			<button type="button" data-act="signUp" class="btn btn-info block full-width m-b">학원밴드 가입하기</button>'

			, '			<a href="'+PageUrl.findInfo+'"><small>아이디나 비밀번호가 생각나지 않는다면?</small></a>'
			, '		</form>'
			, '		<p class="m-t"> <small>HAKWONBAND &copy; 2015</small> </p>'
			, '	</div>'
		].join('')
		, videoHtml : [
			'<video width="320" height="240" controls>'
			, '	<source src="{{=videoUrl}}" type="video/mp4">'
			, '</video>'
		].join('')
	}
};
hakwonTmpl.main = [
	'메인 화면 입니다.'
].join('');

hakwonTmpl.leftMenu = {
	/*	사용자 프로필	*/
	userProfile : [
		'	<img alt="image" class="img-circle" src="{{= comm.userProfileImg(userAuth.profilePath)}}" width="100px" height="100px">'
		, '	<span class="block m-t-xs m-b text-white"> <strong class="font-bold">{{= userAuth.userName}}</strong> / {{= userAuth.userId}}</span>'
	].join('')
	/*	학원 리스트	*/
	, hakwonList : [
		'{{each(i, loopHakwonInfo) hakwonList}}'
		, '		<option value="{{= loopHakwonInfo.hakwon_no}}" {{= hakwonInfo.hakwon_no==loopHakwonInfo.hakwon_no?"selected":""}}>{{= loopHakwonInfo.hakwon_name}}</option>'
		, '{{/each}}'
	].join('')
	, hakwonList_backup : [
		'	<a data-toggle="dropdown" class="dropdown-toggle" href="#" onclick="return false;">'
		, '		<span class="text-muted text-xs block">{{= hakwonInfo.hakwon_name}} <b class="caret"></b></span>'
		, '	</a>'
		, '	<ul class="dropdown-menu animated fadeInRight m-t-xs">'
		, '{{each(i, loopHakwonInfo) hakwonList}}'
		, '		<li><a href="" data-act="hakwon_change" data-hakwon-no="{{= loopHakwonInfo.hakwon_no}}">{{= loopHakwonInfo.hakwon_name}}</a></li>'
		, '{{/each}}'
		, '	</ul>'
	].join('')
	/*	등록된 학원이 없을시에	*/
	, emptyHakwon : [
		'	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="hakwonCreate"><i class="fa fa-university"></i> <span class="nav-label">학원등록</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="hakwonAllList"><i class="fa fa-university"></i> <span class="nav-label">학원 전체 리스트</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a data-type="leftMenu" data-act="receiveMessageList" href="#">받은 메세지</a>'
		, '	</li>'
	].join('')
	/*	등록된 학원이 없을시에	*/
	, emptyHakwonTeacher : [
		'	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="teacherHakwonAllList"><i class="fa fa-university"></i> <span class="nav-label">학원 전체 리스트</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="teacherHakwonRegist"><i class="fa fa-university"></i> <span class="nav-label">학원추가등록</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a data-type="leftMenu" data-act="receiveMessageList" href="#">받은 메세지</a>'
		, '	</li>'
	].join('')
	/*	원장님	*/
	, wonjang : [
		'	<li>'
		, '		<a href="#"><i class="fa fa-envelope"></i> <span class="nav-label">메세지</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level collapse">'
		, '			<li><a data-type="leftMenu" data-act="receiveMessageList" href="#">받은 메세지</a></li>'
		, '			<li><a data-type="leftMenu" data-act="masterSendMessage" href="#">메세지 보내기</a></li>'
		, '			<li><a data-type="leftMenu" data-act="sendMessageGroupList" href="#">보낸 그룹 메세지</a></li>'
		, '			<li><a data-type="leftMenu" data-act="sendMessageSingleList" href="#">보낸 개별 메세지</a></li>'
		, '		</ul>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#"><i class="fa fa-graduation-cap"></i> <span class="nav-label">선생님</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level collapse">'
		, '			<li><a href="#" data-type="leftMenu" data-act="hakwonTeacherList">학원 선생님</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="joinReqTeacherList">가입요청 선생님</a></li>'
		, '		</ul>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="classList"><i class="fa fa-bullseye"></i> <span class="nav-label">반</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="noticeList"><i class="fa fa-bullhorn"></i> <span class="nav-label">전체 공지</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="studentList"><i class="fa fa-child"></i> <span class="nav-label">학생</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="parentList"><i class="fa fa-male"></i> <span class="nav-label">학부모</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="edBannerList"><i class="fa fa-microphone"></i> <span class="nav-label">광고</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="eventLsit"><i class="fa fa-magic"></i> <span class="nav-label">이벤트</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="hakwonCreate"><i class="fa fa-university"></i> <span class="nav-label">학원추가등록</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="adminQuestion"><i class="fa fa-university"></i> <span class="nav-label">관리자에게 문의</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="hakwonAllList"><i class="fa fa-university"></i> <span class="nav-label">학원 전체 리스트</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">설정</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="settingNoticeCate">공지사항 카테고리</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="settingManager">매니저 설정</a></li>'
		, '		</ul>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">가이드</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="guideMap">학원 소개 지도 삽입</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="guideYoutube">Youtube 동영상 삽입</a></li>'
		, '			<li><a href="/file/학원밴드메뉴얼.zip" target="_blank">학원밴드 메뉴얼</a></li>'
		, '		</ul>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">출결</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendancePop">등원/하원</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceBusPop">승차/하차</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceWeekList">출결 리스트</a></li>'
		, '		</ul>'
		, '	</li>'

		, '	<li>'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">수납</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="receiptInsert">수납 등록</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="receiptList">기간별 수납 리스트</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="receiptYearList">학생별 수납 리스트</a></li>'
		, '		</ul>'
		, '	</li>'

		, '	<li>'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">상담</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselInsert">상담 등록</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselListSt">상담 리스트(학생)</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselListPa">상담 리스트(학부모)</a></li>'
		, '		</ul>'
		, '	</li>'

		, '	<li id="test_li" style="display:none;">'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">테스트</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceMake">코드 생성</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceStart">등원</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceEnd">하원</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="receiptInsert">수납 등록</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="receiptList">수납 리스트</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselInsert">상담 등록</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselListSt">상담 리스트(학생)</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselListPa">상담 리스트(학부모)</a></li>'
		, '		</ul>'
		, '	</li>'
	].join('')
	/*	선생님	*/
	, teacher : [
		'	<li>'
		, '		<a href="#" data-type="leftMenu"><i class="fa fa-envelope"></i> <span class="nav-label">메세지</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level collapse">'
		, '			<li><a data-type="leftMenu" data-act="receiveMessageList" href="#">받은 메세지</a></li>'
		, '			<li><a data-type="leftMenu" data-act="teacherSendMessage" href="#">메세지 보내기</a></li>'
		, '			<li><a data-type="leftMenu" data-act="sendMessageGroupList" href="#">보낸 그룹 메세지</a></li>'
		, '			<li><a data-type="leftMenu" data-act="sendMessageSingleList" href="#">보낸 개별 메세지</a></li>'
		, '		</ul>'
		, '	</li>'
		, '<li>'
		, '		<a href="#" data-type="leftMenu" data-act="classList"><i class="fa fa-bullseye"></i> <span class="nav-label">반</span></a>'
		, '</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="noticeList"><i class="fa fa-bullhorn"></i> <span class="nav-label">전체 공지</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="eventLsit"><i class="fa fa-magic"></i> <span class="nav-label">이벤트</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="teacherHakwonRegist"><i class="fa fa-university"></i> <span class="nav-label">학원추가등록</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="adminQuestion"><i class="fa fa-university"></i> <span class="nav-label">관리자에게 문의</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#" data-type="leftMenu" data-act="teacherHakwonAllList"><i class="fa fa-university"></i> <span class="nav-label">학원 전체 리스트</span></a>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">가이드</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="guideMap">학원 소개 지도 삽입</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="guideYoutube">Youtube 동영상 삽입</a></li>'
		, '			<li><a href="/file/학원밴드메뉴얼.zip" target="_blank">학원밴드 메뉴얼</a></li>'
		, '		</ul>'
		, '	</li>'
		, '	<li>'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">출결</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendancePop">등원/하원</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceBusPop">승차/하차</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceWeekList">출결 리스트</a></li>'
		, '		</ul>'
		, '	</li>'

//		, '	<li>'
//		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">수납</span> <span class="fa arrow"></span></a>'
//		, '		<ul class="nav nav-second-level">'
//		, '			<li><a href="#" data-type="leftMenu" data-act="receiptInsert">수납 등록</a></li>'
//		, '			<li><a href="#" data-type="leftMenu" data-act="receiptList">기간별 수납 리스트</a></li>'
//		, '			<li><a href="#" data-type="leftMenu" data-act="receiptYearList">학생별 수납 리스트</a></li>'
//		, '		</ul>'
//		, '	</li>'

		, '	<li>'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">상담</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselInsert">상담 등록</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselListSt">상담 리스트(학생)</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselListPa">상담 리스트(학부모)</a></li>'
		, '		</ul>'
		, '	</li>'

		, '	<li id="test_li" style="display:none;">'
		, '		<a href="#"><i class="fa fa-cog"></i> <span class="nav-label">테스트</span> <span class="fa arrow"></span></a>'
		, '		<ul class="nav nav-second-level">'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceMake">코드 생성</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceStart">등원</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="attendanceEnd">하원</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="receiptInsert">수납 등록</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="receiptList">수납 리스트</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselInsert">상담 등록</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselListSt">상담 리스트(학생)</a></li>'
		, '			<li><a href="#" data-type="leftMenu" data-act="counselListPa">상담 리스트(학부모)</a></li>'
		, '		</ul>'
		, '	</li>'
	].join('')
};

/*	대시 보드	*/
hakwonTmpl.dashBoard = {
	emptyMaster : [
 		'<div class="middle-box text-center animated fadeInRightBig">'
		, '	<h3 class="font-bold">등록된 학원이 없습니다</h3>'
		, '	<div class="error-desc">'
		, '		학원을 등록해 주세요<br/>'
		, '		<a href="'+PageUrl.master.hakwonCreate+'" class="btn btn-primary m-t">학원등록하기</a>'
		, '	</div>'
		, '</div>'
	].join('')
	, emptyTeacher : [
 		'<div class="middle-box text-center animated fadeInRightBig">'
		, '	<h3 class="font-bold">등록된 학원이 없습니다</h3>'
		, '	<div class="error-desc">'
		, '		학원을 등록해 주세요<br/>'
		, '		<a href="'+PageUrl.teacher.hakwonRegist+'" class="btn btn-primary m-t">학원등록하기</a>'
		, '	</div>'
		, '</div>'
	].join('')
	/*	대시 보드 영역	*/
	, main : [
		'<div class="col-md-6">'
		, '	<div class="widget-head-color-box navy-bg p-lg text-center" data-view="dashProfile">'
		, '		<h2 class="font-bold">{{hakwonObj.hakwon_name}}</h2>'
		, '		<img ng-src="{{ getFileFullPath() }}" class="circle-border m-md img-responsive" alt="학원 프로필 사진" width="300" data-view="logo_preview">'
		, '		<span class="btn btn-danger btn-rounded btn_edit" title="프로필수정" ng-if="checkAuthType()"><i class="fa fa-camera"></i> </span>'
		, '		<input type="file" class="input_file_icon" data-act="logo_upload" accept="image/*" ng-if="checkAuthType()">'
		, '		<p>{{hakwonObj.old_sido}} / {{hakwonObj.hakwon_cate_name}}</p>'
		, '	</div>'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학원정보</h3>'
		, '		<div class="row">'
		, '			<p class="col-md-10">'
		, '				주소 : {{ getAllAddrText() }}<br>'
		, '				전화번호 : {{hakwonObj.tel_no_1}}'
		, '			</p>'
		, '			<div class="col-md-2 text-right"><button ng-if="checkAuthType()" class="btn btn-default btn_edit" data-act="hakwonModify" type="button">수정</button></div>'
		, '		</div>'
		, '	</div>'
		, '</div>'
		, '<div class="col-md-6">'
		, '	<table class="table dashboard_counting" summary="학원의 선생님, 학생, 학부모의 수를 나타냅니다">'
		, '		<caption>학원 인원 정보</caption>'
		, '		<tbody>'
		, '			<tr>'
		, '				<td>'
		, '					<span class="count_num btn-warning">{{userCount.teacher_count}}</span> 선생님'
		, '				</td>'
		, '			</tr>'
		, '			<tr>'
		, '				<td>'
		, '					<span class="count_num btn-success">{{userCount.student_count}}</span> 학생'
		, '				</td>'
		, '			</tr>'
		, '			<tr>'
		, '				<td>'
		, '					<span class="count_num btn-info">{{userCount.parents_count}}</span> 학부모'
		, '				</td>'
		, '			</tr>'
		, '		</tbody>'
		, '	</table>'
		, '	<div class="code_view"><i class="fa fa-angellist btn-danger"></i> 학원코드 : {{hakwonObj.hakwon_code}}</div>'
		, '	<button class="btn btn-block btn-lg btn-primary m-b" data-act="hakwonIntro">학원소개</button>'
		, '	<div class="sns_area" style="display:none;">'
		, '		<ul>'
		, '			<li><button type="button" class="sns_01" data-act="snsShare" data-type="facebook">페이스북</button><li>'
		, '			<li><button type="button" class="sns_03" data-act="snsShare" data-type="line">라인</button><li>'
		, '			<li><button type="button" class="sns_04" data-type="kakao">카카오톡</button><li>'
		, '			<li><button type="button" class="sns_05" data-act="snsShare" data-type="band">밴드</button><li>'
		, '			<li><button type="button" class="sns_06" data-act="snsShare" data-type="sms">메세지</button><li>'
		, '		</ul>'
		, '	</div>'
		, '</div>'
	].join('')
};

/*	이벤트	*/
hakwonTmpl.event = {
	list : [
		'<div class="ibox m" data-view="data-div">'
		, '	<div class="ibox-content">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>제목</th>'
		, '					<th>이벤트 진행 기간</th>'
		, '					<th>이벤트 진행 상태</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '			</tbody>'
		, '		</table>'
		, '		<div class="text-right">'
		, '			<button type="button" class="btn btn-primary" ng-if="checkAuthType()" ng-click="write()">이벤트 등록</button>'
		, '		</div>'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopEvent) eventList}}'
		, '	<tr>'
		, '		<td><a href="'+PageUrl.common.eventView+'?hakwon_no={{= hakwonInfo.hakwon_no}}&event_no={{= loopEvent.event_no}}">{{= loopEvent.event_title}}'
		, '			{{if comm.isNewItem(loopEvent.new_date) == true && loopEvent.read_status == 0 }}'
		, '				<strong class="badge badge-danger">N</strong>'
		, '			{{/if}}'
		, '			</a></td>'
		, '		<td><span>{{= loopEvent.begin_date}} ~ {{= loopEvent.end_date}}</span></td>'
		, '		<td class="event_case"><span><strong class="badge badge-primary">{{= loopEvent.ing_yn=="Y"?"진행중":""}}</strong></span></td>'
		, '	</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'	<tr>'
		, '		<td colspan="3" class="box_nodata">등록된 이벤트가 없습니다.</td>'
		, '	</tr>'
	].join('')
	, write : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>이벤트 등록하기</h2>'
		, '	</div>'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">제목</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="text" name="title" maxLength="20" class="form-control" placeholder="20자까지">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">기간</label>'
		, '			<div class="col-sm-11 event_date_picker">'
		, '				<div class="input-daterange input-group" id="datepicker">'
		, '					<input type="text" name="begin_date" class="input-sm form-control" value="" readOnly/>'
		, '					<span class="input-group-addon">to</span>'
		, '					<input type="text" name="end_date" class="input-sm form-control" value="" readOnly/>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">내용</label>'
		, '			<div class="col-sm-11">'
		, '				<textarea cols="140" name="event_content" data-lib="editor" rows="10" class="form-control"></textarea>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" data-act="file_upload" class="input_file" multiple>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">첨부파일</label>'
		, '			<div class="col-sm-11">'
		, '				<p>'
		, '					<span><i class="fa fa-paperclip"></i> 10 개파일 첨부</span>'
		, '				</p>'
		, '				<div class="attachment"></div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="cancel" class="btn btn-default">취소하기</button>'
		, '		<button type="button" data-act="save" class="btn btn-primary" ng-if="checkAuthType()">등록하기</button>'
		, '	</div>'
		, '</div>'
	].join('')
	, attachFile : [
		'{{each(i, loopFile) fileList}}'
		, '<div class="file-box" data-file-no="{{= loopFile.fileNo}}">'
		, '	<div class="file">'
		, '{{if loopFile.imageYn == "Y" }}'
		, '		<div class="image">'
		, '			<img alt="image" class="img-responsive" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+loopFile.filePath}}">'
		, '		</div>'
		, '{{/if}}'
		, '{{if loopFile.imageYn != "Y" }}'
		, '		{{if loopFile.mimeType.indexOf("video") == 0 }}'
		, '		<div class="icon" data-file-type="video" data-file-url="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+loopFile.filePath}}">'
		, '			<i class="fa fa-file"></i>'
		, '		</div>'
		, '		{{/if}}'
		, '		{{if loopFile.mimeType.indexOf("video") != 0 }}'
		, '		<div class="icon">'
		, '			<i class="fa fa-file"></i>'
		, '		</div>'
		, '		{{/if}}'
		, '{{/if}}'
		, '		<div class="file-name">'
		, '			<p>{{= loopFile.fileName}}</p>'
		, '		</div>'
		, '		<button type="button" data-file-no="{{= loopFile.fileNo}}" data-act="fileDel" class="btn btn-circle btn_file_del" title="삭제">X</button>'
		, '	</div>'
		, '</div>'
		, '{{/each}}'
	].join('')
	, editForm : [
		'<div class="ibox m" data-view="data-view">'
		, hakwonTmpl.common.init
		, '</div>'
	].join('')
	, editData : [
		'	<div class="ibox-title">'
		, '		<h2>이벤트 수정하기</h2>'
		, '	</div>'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">제목</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="text" name="title" value="{{= eventInfo.event_title}}" class="form-control" maxLength="20" placeholder="20자까지">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">기간</label>'
		, '			<div class="col-sm-11 event_date_picker">'
		, '				<div class="input-daterange input-group" id="datepicker">'
		, '					<input type="text" name="begin_date" class="input-sm form-control" value="{{= eventInfo.begin_date}}" readOnly/>'
		, '					<span class="input-group-addon">to</span>'
		, '					<input type="text" name="end_date" class="input-sm form-control" value="{{= eventInfo.end_date}}" readOnly/>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">내용</label>'
		, '			<div class="col-sm-11">'
		, '				<textarea cols="140" data-lib="editor" rows="10" class="form-control"></textarea>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" data-act="file_upload" class="input_file" multiple>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">첨부파일</label>'
		, '			<div class="col-sm-11">'
		, '				<p>'
		, '					<span><i class="fa fa-paperclip"></i> 10 개파일 첨부</span>'
		, '				</p>'
		, '				<div class="attachment"></div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="cancel" class="btn btn-default">취소하기</button>'
		, '		<button type="button" data-act="edit" class="btn btn-primary" ng-if="checkAuthType()">수정하기</button>'
		, '	</div>'
	].join('')
	, viewForm : [
		'<div class="ibox m" data-view="data-view">'+hakwonTmpl.common.init+'</div>'
	].join('')
	, viewData : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>{{= eventInfo.event_title}} <small>등록일 : {{= eventInfo.reg_date}} / 등록자 : {{= eventInfo.reg_user_name}}</small></h2>'
		, '	</div>'
		, '	<div class="ibox-content">이벤트 기간 : {{= eventInfo.begin_date}} ~ {{= eventInfo.end_date}}</div>'
		, '	<div class="ibox-content" id="content_view_div">{{html eventInfo.event_content}}</div>'
		, '	<div class="ibox-content text-right">'
		, '	{{if userAuth.userNo == eventInfo.reg_user_no }}'
		, '		<button type="button" data-act="eventDel" class="btn btn-default" ng-if="checkAuthType()">삭제하기</button>'
		, '		<button type="button" data-act="eventEdit" class="btn btn-werning" ng-if="checkAuthType()">수정하기</button>'
		, '	{{/if}}'
		, '		<button type="button" data-act="list" class="btn btn-primary">목록으로</button>'
		, '	</div>'
		, '</div>'
		, '<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h3>이벤트 신청자</h3>'
		, '		<div class="ibox-tools">'
		, '			<button class="btn btn-primary btn_message" type="button">전체 신청자에게 메세지 보내기</button>'
		, '			<a class="collapse-link">'
		, '				<i class="fa fa-chevron-up"></i>'
		, '			</a>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content event_applicant_list">'
		, '		<ul>'
		, '	{{each(i, loopMember) eventMemberList}}'
		, '			<li>'
		, '				<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopMember.photo_file_path)}}" alt="{{= loopMember.user_name}}" width="30" height="30">'
		, '				<span class="badge .badge-plain">{{= loopMember.user_type_name}}</span>'
		, '				<strong class="name">{{= loopMember.user_name}}</strong> <span>{{= loopMember.user_id}} / {{= loopMember.user_gender_name}} / {{= !loopMember.user_age||loopMember.user_age==0?"생일 미입력":loopMember.user_age+" 세"}} / <a href="tel:{{= loopMember.tel1_no}}">{{= loopMember.tel1_no}}</a></span>'
		, '				<button class="btn btn-default btn_message" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button>'
		, '			</li>'
		, '	{{/each}}'
		, '	{{if eventMemberList.length == 0 }}'
		, '<li class="box_nodata">이벤트 신청자가 없습니다</li>'
		, '	{{/if}}'
		, '		</ul>'
		, '	</div>'
		, '</div>'
	].join('')
};
	/*	광고	*/
hakwonTmpl.adBanner = {
	/*	광고 리스트	*/
	list : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>광고 리스트</h2>'
		, '	</div>'
		, '	<div data-view="list-div" class="ibox-content">'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" ng-click="write()" class="btn btn-primary">광고 등록</button>'
		, '	</div>'
		, '	<div data-view="page-nav" class="text-center m-b-xl m-t-xl"></div>'
		, '</div>'
	].join('')
	/*	리스트 로우	*/
	, listRow : [
		'<ul class="ad_list_box">'
		, '{{each(i, loopAdvertiseInfo) advertiseReqList}}'
		, '	<li>'
		, '		<a href="'+PageUrl.common.edBannerView+'?hakwonNo={{= hakwonInfo.hakwon_no}}&reqNo={{= loopAdvertiseInfo.advertise_req_no}}">'
		, '			<strong class="ad_size badge-primary" title="광고 배너 사이즈">{{= loopAdvertiseInfo.banner_size}}</strong>'
		, '			<span class="ad_title">{{= loopAdvertiseInfo.title}}{{= (loopAdvertiseInfo.view_month_count>0&&loopAdvertiseInfo.deposit_yn=="Y")?"(광고 노출 중)":""}}</span>'
		, '			<span class="ad_size_text">광고 사이즈 : {{= loopAdvertiseInfo.banner_size}}칸 </span>'
		, '			<span class="ad_info">'
		, '				결제 여부 : <small class="badge badge-plain">{{= loopAdvertiseInfo.deposit_yn=="Y"?"입금 완료":"입금 확인 중"}}</small><br>'
		, '				취소 여부 : <small class="badge badge-plain">{{= loopAdvertiseInfo.cancel_yn=="Y"?"취소":"-"}}</small>'
		, '			</span>'
		, '		</a>'
		, '		<div class="clearfix"></div>'
		, '	</li>'
		, '{{/each}}'
		, '</ul>'
	].join('')
	/*	리스트 로우 nodata	*/
	, listRowNoData : [
		'등록된 광고가 없습니다<br>광고를 등록해 주세요.<br>'
		, '<a href="'+PageUrl.common.edBannerWrite+'" class="btn btn-primary m-t-xl">광고 등록하기</a>'
	].join('')
	/*	광고 상세	*/
	, view : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>{{ reqDetailInfo.title }}</h2>'
		, '	</div>'
		, '	<div class="ibox-content ad_view">'
		, '		<h3 class="text_title">광고 정보</h3>'
		, '		<table class="table table-bordered table_center" summary="광고의 크기, 결제여부, 취소여부를 나타내는 표 입니다">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>광고 영역 크기</th>'
		, '					<th>결제여부</th>'
		, '					<th>광고금액</th>'
		, '					<th>시도 / 구군</th>'
		, '					<th>취소여부</th>'
		, '					<th>관리자 중지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '				<tr>'
		, '					<td>{{reqDetailInfo.banner_size}}칸</td>'
		, '					<td>{{reqDetailInfo.deposit_yn=="Y"?"입금 완료":"미입금"}}</td>'
		, '					<td>{{reqDetailInfo.price}}원</td>'
		, '					<td>{{reqDetailInfo.sido}} / {{reqDetailInfo.gugun}}</td>'
		, '					<td>{{reqDetailInfo.cancel_yn}}</td>'
		, '					<td>{{reqDetailInfo.stop_admin_yn}}</td>'
		, '				</tr>'
		, '			</tbody>'
		, '		</table>'
		, '		<h4 class="text_title">광고 이미지</h4>'
		, '		<img ng-src="{{reqDetailInfo.banner_web_path}}" class="ad_img" alt="광고 이미지">'

		, '		<h5 class="text_title">광고 현황</h5>'
		, '		<table summary="지역별 광고 기간 현황을 나타냅니다." class="table table-bordered  table_center">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>동/읍/면</th>'
		, '					<th ng-repeat="loopViewMonth in viewMonthArray">{{CommUtil.yearMonthFormatter(loopViewMonth)}}</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '				<tr ng-repeat="loopLocalDongName in localDongNameArray">'
		, '					<td>{{loopLocalDongName}}</td>'
		, '					<td data-dong="{{loopLocalDongName}}" data-month="{{loopViewMonth}}" ng-repeat="loopViewMonth in viewMonthArray">'
		, '						<i style="display:none;" class="fa fa-check ad_check text-navy"></i>'
		, '					</td>'
		, '				</tr>'
		, '			</tbody>'
		, '		</table>'
		, '		<h4 class="text_title">광고 금액 정보</h4>'
		, '		<div class="table-responsive m-t">'
		, '			<table class="table invoice-table">'
		, '				<thead>'
		, '				<tr>'
		, '					<th>기간정보</th>'
		, '					<th>배너크기</th>'
		, '					<th>가격</th>'
		, '					<th>지역</th>'
		, '					<th>합계</th>'
		, '				</tr>'
		, '				</thead>'
		, '				<tbody>'
		, '				<tr ng-repeat="loopMonthPrice in monthPriceList">'
		, '					<td>{{loopMonthPrice.view_month}}</td>'
		, '					<td>{{loopMonthPrice.banner_size}}칸</td>'
		, '					<td>{{loopMonthPrice.price}}원</td>'
		, '					<td>{{loopMonthPrice.dong_count}}</td>'
		, '					<td>{{loopMonthPrice.total_price}}</td>'
		, '				</tr>'
		, '				</tbody>'
		, '			</table>'
		, '		</div>'
		, '		<table class="table invoice-total">'
		, '			<tbody>'
		, '			<tr>'
		, '				<td><strong>합계 :</strong></td>'
		, '				<td>￦{{reqDetailInfo.price}}</td>'
		, '			</tr>'
		, '			</tbody>'
		, '		</table>'
		, '		<div class="well m-t"><strong>입금계좌정보 : </strong>{{reqDetailInfo.bank_info}}</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" ng-click="goList()" style="float:left;">목록으로</button>'
		, '		<button type="button" class="btn btn-danger" ng-if="!isCancel(reqDetailInfo.cancel_yn)" ng-click="cancel()">광고 취소하기</button>'
		, '		<button type="button" class="btn btn-warning" ng-if="!isCancel(reqDetailInfo.cancel_yn)" ng-click="goEdit()">광고 수정하기</button>'
		, '	</div>'
		, '</div>'
	].join('')
	/*	광고 등록	*/
	, write : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>광고 등록</h2>'
		, '	</div>'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">지역</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="row">'
		, '					<div class="col-md-3">'
		, '						<select name="sido" class="form-control m-b" ng-options="sidoName for sidoName in sidoArray track by sidoName" ng-model="sidoName" ng-change="sido_change()">'
		, '							<option value="">시도 선택</option>'
		, '						</select>'
		, '					</div>'
		, '					<div class="col-md-3">'
		, '						<select name="gugun" class="form-control m-b" ng-options="gugunName for gugunName in gugunArray track by gugunName" ng-model="gugunName" ng-change="gugun_change()">'
		, '							<option value="">구군 선택</option>'
		, '						</select>'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">광고기간</label>'
		, '			<div class="col-sm-11">'
		, '				<table class="table table-bordered table_center" data-type="calendar_table" summary="지역별, 기간별로 광고를 등록할 수 있도록 선택하는 표 입니다">'
		, '					<thead>'
		, '						<tr>'
		, '							<th>지역</th>'
		, '						</tr>'
		, '					</thead>'
		, '					<tbody></tbody>'
		, '				</table>'
		, '				<div class="table_info row">'
		, '					<span class="info_box info_01"></span> 선택불가(매진)'
		, '					<span class="info_box info_02"></span> 선택불가(기존광고)'
		, '					<span class="info_box info_03"></span> 선택가능'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">제목</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="text" name="title" class="form-control" placeholder="제목을 입력하세요">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">배너 크기</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="row">'
		, '					<div class="col-md-3">'
		, '						<select class="form-control m-b" name="banner_size">'
		, '							<option value="1" label="1">1</option>'
		, '							<option value="2" label="2">2</option>'
		, '							<option value="3" label="3">3</option>'
		, '							<option value="4" label="4">4</option>'
		, '						</select>'
		, '					</div>'
		, '					<div data-view="banner_sample_view" class="col-md-8">'
		, '						<!-- 광고 크기 1을 선택할 경우 나타냄 -->'
		, '						<div class="ad_size_sample ad_size_01">148px x 148px</div>'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">광고 예상 가격</label>'
		, '			<div class="col-sm-11" data-view="price_preview"></div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" data-act="banner_upload" class="input_file" accept="image/*">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">이미지 확인</label>'
		, '			<div class="col-sm-11" data-view="banner_preview">'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" ng-click="cancel()">취소하기</button>'
		, '		<button type="button" class="btn btn-primary" ng-click="regist()">등록하기</button>'
		, '	</div>'
		, '</div>'
	].join('')
	/*	광고 수정	*/
	, edit : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>광고 수정</h2>'
		, '	</div>'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">제목</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="text" name="title" value="{{reqDetailInfo.title}}" class="form-control" placeholder="제목을 입력하세요">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" data-act="banner_upload" class="input_file" accept="image/*">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">이미지 확인</label>'
		, '			<div class="col-sm-11">'
		, '				<img alt="image" data-file-no="{{reqDetailInfo.banner_file_no}}" data-view="banner_preview" ng-src="{{reqDetailInfo.banner_web_path}}">'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" ng-click="cancel()" class="btn btn-default">취소하기</button>'
		, '		<button type="button" ng-click="modify()" class="btn btn-primary">등록하기</button>'
		, '	</div>'
		, '</div>'
	].join('')
};

/*	학원	*/
hakwonTmpl.hakwon = {
	/*	학원 생성	*/
	create : [
		'<form>'
		, '<div class="ibox m">'
		, '	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_01">학원명</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="text" name="hakwonName" class="form-control" placeholder="20자까지" maxLength="20" id="academy_write_01">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_02">로고 이미지</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" class="input_file" data-act="photo_upload" id="academy_write_02" accept="image/*">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">이미지 확인</label>'
		, '			<div class="col-sm-11" data-view="image_preveiw">'
		, '				<button type="button" ng-click="logoDelete()" class="btn btn-default">삭제</button>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_02">전화번호</label>'
		, '			<div class="col-sm-11">'
		, '				<input type="tel" name="telNo" class="form-control" placeholder="전화번호" id="academy_write_02">'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_03">업종</label>'
		, '			<div class="col-sm-11">'
		, '				<select name="hakwonCate" class="form-control" ng-options="hakwonCate.cateName for hakwonCate in hakwonCateList track by hakwonCate.cateCode" ng-model="searchCateCode">'
		, '					<option value="">카테고리</option>'
		, '				</select>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_04">지번주소</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="col-md-4 input-group m-b">'
		, '					<input type="text" class="form-control" name="searchOldDong" placeholder="동 이름으로 검색" id="academy_write_04">'
		, '					<span class="input-group-btn"> <button type="button" data-act="searchOldAddr" class="btn btn-primary">검색</button> </span>'
		, '				</div>'
		, '				<ul class="address_search_result" style="display:none;" data-view="oldAddrList"></ul>'
		, '				<div class="row">'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="oldAddr1" class="form-control" placeholder="검색된 주소" readOnly="true">'
		, '					</div>'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="oldAddr2" class="form-control" placeholder="기타주소 입력">'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label" for="academy_write_05">도로명주소</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="col-md-4 input-group m-b">'
		, '					<input type="text" name="searchStreetDong" class="form-control" placeholder="동 이름으로 검색" id="academy_write_05">'
		, '					<span class="input-group-btn"> <button type="button" data-act="searchStreetDong" class="btn btn-primary">검색</button> </span>'
		, '				</div>'
		, '				<ul class="address_search_result" style="display:none;" data-view="streetAddrList"></ul>'
		, '				<div class="row">'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="streetAddr1" class="form-control" placeholder="검색된 주소" readOnly="true">'
		, '					</div>'
		, '					<div class="col-md-6">'
		, '						<input type="text" name="streetAddr2" class="form-control" placeholder="기타주소 입력">'
		, '					</div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" ng-click="goList()" class="btn btn-default">취소하기</button>'
		, '		<button type="button" ng-click="regist()" class="btn btn-primary">등록하기</button>'
		, '	</div>'
		, '</div>'
		, '</form>'
	].join('')
	, oldAddrRow : [
		'{{each(i, loopOldAddr) dataList}}'
		, '<li data-addr-no="{{= loopOldAddr.addr_no}}" data-act="oldAddrLI">'
		, '	<a href="#" onclick="return false;" data-addr-no="{{= loopOldAddr.addr_no}}">{{= loopOldAddr.zip_code}} <span>{{= loopOldAddr.sido}} {{= loopOldAddr.gugun}} {{= loopOldAddr.dong}} </span>{{= loopOldAddr.ri}} {{= loopOldAddr.bldg_name}} {{= loopOldAddr.bunji}}</a>'
		, '</li>'
		, '{{/each}}'
	].join('')
};

/*	원장	*/
hakwonTmpl.master = {
	joinReqTeacherList : [
		'<div class="contact_wrap row" data-view="data-view"></div>'
	].join('')
	, joinReqTeacherRow : [
		'{{each(i, loopTeacher) dataList}}'
		, '	<div class="col-lg-4 contact_item" data-target="teacher_{{= loopTeacher.user_no}}_{{= loopTeacher.hakwon_no}}">'
		, '		<div class="contact-box">'
		, '			<div class="col-sm-4">'
		, '				<div class="text-center">'
		, '					<img class="img-circle m-t-xs img-responsive" src="{{= comm.userProfileImg(loopTeacher.user_photo_path)}}" alt="{{= loopTeacher.user_name}}">'
		, '				</div>'
		, '			</div>'
		, '			<div class="col-sm-8">'
		, '				<h3 class="title_name">{{= loopTeacher.user_name}}</h3>'
		, '				<ul class="contact-box-info">'
		, '					<li>아이디 : {{= loopTeacher.user_id}}</li>'
		, '					<li>요청 학원 : {{= loopTeacher.hakwon_name}}</li>'
		, '					<li>핸드폰 : <a href="tel:{{= loopTeacher.tel1_no}}">{{= loopTeacher.tel1_no}}</a></li>'
		, '					<li>성별/나이 : {{= loopTeacher.user_gender=="M"?"남자":"여자"}} / {{= !loopTeacher.user_age||loopTeacher.user_age==0?"생일 미입력":loopTeacher.user_age+"세"}}</li>'
		, '					<li class="message_btn_box"><button type="button" data-act="approved" data-user-name="{{= loopTeacher.user_name}}" data-hakwon-name="{{= loopTeacher.hakwon_name}}" data-user-no="{{= loopTeacher.user_no}}" data-hakwon-no="{{= loopTeacher.hakwon_no}}" class="btn btn-primary m-t"><i class="fa fa-check-circle"></i> 수락하기</button></li>'
		, '				</ul>'
		, '			</div>'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '	</div>'
		, '{{/each}}'
	].join('')
}
/*	학생	*/
hakwonTmpl.student = {
	listForm : [
		'<div class="col-md-6 input-group col-md-offset-3">'
		, '	<input type="text" name="searchText" class="form-control" placeholder="이름 및 아이디 검색">'
		, '	<span class="input-group-btn"> <button type="button" data-act="search" class="btn btn-primary">검색</button> </span>'
		, '</div>'
		, '<div class="ibox m m-t-xl">'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="ibox-content" data-view="data-div">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th><input type="checkbox" class="i-checks" name="input"></th>'
		, '					<th>이름</th>'
		, '					<th>아이디</th>'
		, '					<th>학원 가입일</th>'
		, '					<th>기타</th>'
		, '					<th>메세지</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody></tbody>'
		, '		</table>'
		, '	</div>'
//		, '	<div class="ibox-content text-right">'
//		, '		<button class="btn btn-primary" type="button" title="메세지 보내기">단체 메세지 보내기</button>'
//		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopData) dataList}}'
		, '<tr>'
		, '	<td><span><input type="checkbox" value="{{= loopData.user_no}}" class="i-checks" name="input"></span></td>'
		, '	<td>'
		, '		<a href="'+PageUrl.common.studentView+'?hakwon_no={{= hakwonInfo.hakwon_no}}&studentUserNo={{= loopData.user_no}}"><img class="img-circle" src="{{= comm.userProfileImg(loopData.user_photo_path)}}" alt="" width="30" height="30"> {{= loopData.user_name}}</a>'
		, '	</td>'
		, '	<td><span>{{= loopData.user_id}}</span></td>'
		, '	<td><span>{{= loopData.reg_date}}</span></td>'
		, '	<td><span>{{= loopData.user_gender=="M"?"남":"여"}}({{= !loopData.user_age||loopData.user_age==0?"생일 미입력":loopData.user_age+"세"}})</span></td>'
		, '	<td><span><button class="btn btn-default btn_message" data-act="user_message" data-user-no="{{= loopData.user_no}}" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></span></td>'
		, '</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'<tr>'
		, '	<td class="text-center" style="padding:200px 0 !important;">검색된 학생이 없습니다.</td>'
		, '</tr>'
	].join('')
	, viewForm : ['<div class="ibox m m-t-xl"><div class="ibox-content"><div class="col-md-8 col-md-offset-2" data-view="data-view">'+hakwonTmpl.common.init+'</div></div></div>'].join('')
	, viewData : [
		'	<div class="widget-head-color-box blue-bg p-lg text-center">'
		, '		<h2 class="font-bold">{{= userInfo.user_name}}</h2>'
		, '		<img src="{{= hakwonCommon.createFilePullPath(userInfo.photo_file_path, "photo")}}" class="circle-border m-md img-responsive" alt="{{= userInfo.user_name}}" width="300" height="300">'
		, '		<p>{{= userInfo.user_gender_name}} / {{= !userInfo.user_age||userInfo.user_age==0?"생일 미입력":userInfo.user_age+"세"}} / {{= schoolInfo.school_name}} {{= schoolInfo.level}}학년</p>'
		, '	</div>'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">연락정보</h3>'
		, '		<div class="row">'
		, '			<div class="col-md-10">'
		, '				<ul>'
		, '					<li>이메일 : <a href="mailto:{{= userInfo.user_email}}">{{= userInfo.user_email}}</a></li>'
		, '					<li>전화번호 : <a href="tel:{{= userInfo.tel1_no}}">{{= userInfo.tel1_no}}</a></li>'
		, '					<li>출결코드 : {{= userInfo.attendance_code}}</li>'
		, '					<li name="registDate">등록일 : <input type="text" name="registDate" value="{{= userInfo.receipt_date}}" readonly="readonly"> &nbsp; <button name="update" style="display : none; ">확인</button> <button name="update_ready">수정</button></li>'
		, '				</ul>'
		, '			</div>'
		, '			<div class="col-md-2 text-right"><button class="btn btn-default btn_message" data-act="user_message" data-user-no="{{= userInfo.user_no}}" type="button" title="메세지 보내기"><i class="fa fa-envelope"></i> </button></div>'
		, '		</div>'
		, '	</div>'
		, '{{if hakwonClassList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">반정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopClass) hakwonClassList}}'
		, '			<li>'
		, '				<a href="#/class/noticeList?hakwon_no={{= hakwonInfo.hakwon_no}}&class_no={{= loopClass.class_no}}">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopClass.logo_file_path, "hakwon")}}" alt="{{= loopClass.class_title}}" width="30">'
		, '					<strong class="name">{{= loopClass.class_title}}</strong>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'
		, '{{if parentList.length > 0 }}'
		, '	<div class="widget-text-box">'
		, '		<h3 class="media-heading">학부모 정보</h3>'
		, '		<ul class="academy_info">'
		, '	{{each(i, loopParent) parentList}}'
		, '			<li>'
		, '				<a href="'+PageUrl.common.parentView+'?hakwon_no={{= hakwonInfo.hakwon_no}}&parentUserNo={{= loopParent.parent_user_no}}">'
		, '					<img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopParent.photo_file_path, "photo")}}" alt="{{= loopParent.user_name}}" width="30" height="30">'
		, '					<strong class="name">{{= loopParent.user_name}}</strong> <span class="info_text">{{= (loopParent.user_gender=="M"?"남":"여")}} / {{= !loopParent.user_age||loopParent.user_age==0?"생일 미입력":loopParent.user_age + "세"}}</span>'
		, '					<span class="badge badge-plain">{{= (loopParent.user_gender=="M"?"부":"모")}}</span>'
		, '				</a>'
		, '			</li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '{{/if}}'

		, '<div class="widget-text-box">'
		, '		<h3 class="media-heading">출결관리</h3>'
		, '		<div id="attendanceCalendar">'
		, '		</div>'
		, '</div>'
		, '	<div class="text-right m-t">'
		//, '		<button class="btn btn-default" data-act="modify" type="button">수정</button>'
		, '		<button class="btn btn-default" data-act="list" type="button">목록으로</button>'
		, '	</div>'
	].join('')
};

/*	메세지	*/
hakwonTmpl.message = {
	/*	선생님 메세지 보내기	*/
	teacherSendForm : [
		'<div class="ibox">'+hakwonTmpl.common.init+'</div>'
	].join('')
	/*	선생님 메세지 보내기	*/
	, teacherSend : [
		'	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">반 선택</label>'
		, '			<div class="col-sm-11">'
		, '				<select name="classTarget" class="form-control m-b">'
		, '	{{each(i, loopClass) classList}}'
		, '					<option value="{{= loopClass.class_no}}" data-count="{{= loopClass.student_count}}">{{= loopClass.class_title}}(학생수:{{= loopClass.student_count}})</option>'
		, '	{{/each}}'
		, '					<option value="search">검색</option>'
		, '				</select>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group" data-target-type="class">'
		, '			<label class="col-sm-1 control-label">예약 발송</label>'
		, '			<div class="col-md-2">'
		, '				<input type="text" class="form-control" name="reservationDate" placeholder="날짜" readOnly>'
		, '			</div>'
		, '			<div class="col-md-2">'
		, '				<input type="time" class="form-control" name="reservationTime" placeholder="시간">'
		, '			</div>'
		, '			<div class="col-md-2">'
		, '				<span class="input-group-btn"> <button type="button" data-act="reservationCancel" class="btn btn-primary">예약 취소</button> </span>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">선택방법</label>'
		, '			<div class="col-sm-11">'
		, '				<select class="form-control m-b" name="targetType">'
		, '					<option value="student_all">학생 전체 메세지 보내기</option>'
		, '					<option value="parent_all">학부모 전체 메세지 보내기</option>'
		, '					<option value="all">학생/학부모 전체 메세지 보내기</option>'
		, '				</select>'
		, '			</div>'
		, '		</div>'
		, '		<!-- 상단 셀렉트 박스에서 이름 검새 후 메세지 보내기 선택하면 나오는 영역 시작 -->'
		, '		<div class="form-group" data-view="searchDiv" style="display:none;">'
		, '			<label class="col-sm-1 control-label">검색하기</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="input-group">'
		, '					<input type="text" name="searchText" class="form-control" placeholder="학생 아이디 및 이름으로 검색"> <span class="input-group-btn"> <button type="button" class="btn btn-primary" data-act="messageTargetSearch">검색하기</button></span>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<!-- 검색하기 버튼 클릭시 결과 나타남. 클릭 전에는 나타나지 않음 -->'
		, '		<div class="form-group" data-view="searchResult" style="display:none;">'
		, '			<label class="col-sm-1 control-label">검색결과</label>'
		, '			<div class="col-sm-11">'
		, '				<ul class="search_name_list"></ul>'
		, '			</div>'
		, '		</div>'
		, '		<!-- 상단 셀렉트 박스에서 이름 검새 후 메세지 보내기 선택하면 나오는 영역 끝 -->'
		, '		<div class="form-group" data-view="searchTarget" style="display:none;">'
		, '			<label class="col-sm-1 control-label">선택자</label>'
		, '			<div class="col-sm-11">'
		, '				<ul class="chosen_select"></ul>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">내용</label>'
		, '			<div class="col-sm-11">'
		, '				<textarea cols="140" rows="10" name="messageContent" class="form-control" data-lib="editor"></textarea>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" class="input_file" data-act="file_upload" multiple>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">첨부파일</label>'
		, '			<div class="col-sm-11">'
		, '				<p>'
		, '					<span><i class="fa fa-paperclip"></i> 0 개파일 첨부</span>'
		, '				</p>'
		, '				<div class="attachment">'
		, '					<div class="clearfix"></div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" data-act="cancel">취소하기</button>'
		, '		<button type="button" class="btn btn-primary" data-act="messageSend">등록하기</button>'
		, '	</div>'
	].join('')
	/*	첨부 파일	*/
	, attchFile : [
		'	<div class="file-box" data-file-no="{{= fileInfo.fileNo}}" data-file-type="{{= fileInfo.extType}}" data-file-url="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+fileInfo.filePath}}">'
		, '		<div class="file">'
		, '	{{if fileInfo.imageYn == "Y" }}'
		, '			<div class="image">'
		, '				<img alt="image" class="img-responsive" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+fileInfo.filePath}}">'
		, '			</div>'
		, '	{{/if}}'
		, '	{{if fileInfo.imageYn != "Y" }}'
		, '			<div class="icon"><i class="fa fa-file"></i></div>'
		, '	{{/if}}'
		, '			<div class="file-name">'
		, '				<p>{{= fileInfo.fileName}}</p>'
		, '			</div>'
		, '			<button type="button" class="btn btn-circle btn_file_del" title="삭제">X</button>'
		, '		</div>'
		, '	</div>'
	].join('')
	/*	검색 결과	*/
	, searchData : [
		'{{each(i, searchUser) searchList}}'
		, '<li>'
		, '	<span class="student_add_box">'
		, '		<img class="img-circle" src="{{= comm.userProfileImg(searchUser.user_photo_path)}}" alt="프로필" width="35" height="35">'
		, '		<strong class="name">{{= searchUser.user_name}}</strong> {{= searchUser.user_id}} / {{= searchUser.user_gender=="M"?"남자":"여자"}} / {{= !searchUser.user_age||searchUser.user_age==0?"생일 미입력":searchUser.user_age+"세"}}'
		, '		<button type="button" data-val="{{= searchUser.user_name + CommonConstant.ChDiv.CH_DEL + searchUser.user_no}}" data-act="target" class="btn btn-default btn-sm">추가</button>'
		, '	</span>'
		, '	{{each(i, parentUser) searchUser.relationList}}'
		, '	<span class="parents_add_box">'
		, '		<i>{{= parentUser.user_gender=="M"?"부":"모"}}</i>'
		, '		<img class="img-circle" src="{{= comm.userProfileImg(parentUser.user_photo_path)}}" alt="프로필" width="30" height="30">'
		, '		<strong class="name">{{= parentUser.user_name}}</strong> {{= parentUser.user_id}} / {{= parentUser.user_gender=="M"?"남자":"여자"}} / {{= !parentUser.user_age||parentUser.user_age==0?"생일 미입력":parentUser.user_age+"세"}}'
		, '		<button type="button" data-val="{{= parentUser.user_name + CommonConstant.ChDiv.CH_DEL + parentUser.user_no}}" data-act="target" class="btn btn-default btn-xs">추가</button>'
		, '	</span>'
		, '	{{/each}}'
		, '</li>'
		, '{{/each}}'
	].join('')
	/*	선택 타겟	*/
	, choiceTarget : [
		'<li data-user-no="{{= target.user_no}}">{{= target.user_name?target.user_name:target.user_id}} <button type="button" class="btn_x" data-act="choiceTargetDel" title="삭제">x</button></li>'
	].join('')
	/*	원장님 메세지 보내기	*/
	, masterSendForm : [
		'<div class="ibox">'+hakwonTmpl.common.init+'</div>'
	].join('')
	/*	원장님 메세지 보내기	*/
	, masterSend : [
		'	<div class="ibox-content form-horizontal">'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">전송대상타입</label>'
		, '			<div class="col-sm-11">'
		, '				<select name="targetType" class="form-control m-b">'
		, '					<option value="class">반 선택</option>'
		, '					<option value="userGroup">사용자 그룹</option>'
		, '					<option value="search">검색</option>'
		, '				</select>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group" data-target-type="class">'
		, '			<label class="col-sm-1 control-label">예약 발송</label>'
		, '			<div class="col-md-2">'
		, '				<input type="text" class="form-control" name="reservationDate" placeholder="날짜" readOnly>'
		, '			</div>'
		, '			<div class="col-md-2">'
		, '				<input type="time" class="form-control" name="reservationTime" placeholder="시간">'
		, '			</div>'
		, '			<div class="col-md-2">'
		, '				<span class="input-group-btn"> <button type="button" data-act="reservationCancel" class="btn btn-primary">예약 취소</button> </span>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group" data-target-form="Y" data-target-type="class" style="display:none;">'
		, '			<label class="col-sm-1 control-label">반 선택</label>'
		, '			<div class="col-sm-11">'
		, '	{{each(i, loopClass) classList}}'
		, '				<label class="i-checks ca_checks" for="check_class_{{= loopClass.class_no}}">'
		, '					<input type="checkbox" value="{{= loopClass.class_no}}" data-count="{{= loopClass.student_count}}" id="check_class_{{= loopClass.class_no}}" name="targetClass">'
		, '					{{= loopClass.class_title}}(학생수:{{= loopClass.student_count}})'
		, '				</label>'
		, '	{{/each}}'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group" data-target-form="Y" data-target-type="class" data-target-user="user" style="display:none;">'
		, '			<label class="col-sm-1 control-label">전송 대상</label>'
		, '			<div class="col-sm-11">'
		, '				<label class="i-checks ca_checks" for="check_category_01" data-type="targetUserType" data-value="teacher">'
		, '					<input type="checkbox" value="teacher" id="check_category_01" name="targetUserType">'
		, '					<strong class="name">선생님</strong>'
		, '				</label>'
		, '				<label class="i-checks ca_checks" for="check_category_02" data-type="targetUserType" data-value="parent">'
		, '					<input type="checkbox" value="parent" id="check_category_02" name="targetUserType">'
		, '					<strong class="name">정회원 학생의 학부모</strong>'
		, '				</label>'
		, '				<label class="i-checks ca_checks" for="check_category_03" data-type="targetUserType" data-value="student">'
		, '					<input type="checkbox" value="student" id="check_category_03" name="targetUserType">'
		, '					<strong class="name">정회원 학생</strong>'
		, '				</label>'
		, '				<label class="i-checks ca_checks" for="check_category_04" data-type="targetUserType" data-value="nonParent"  style="display:none;">'
		, '					<input type="checkbox" value="nonParent" id="check_category_04" name="targetUserType">'
		, '					<strong class="name">비회원 학부모</strong>'
		, '				</label>'
		, '				<label class="i-checks ca_checks" for="check_category_05" data-type="targetUserType" data-value="nonStudent"  style="display:none;">'
		, '					<input type="checkbox" value="nonStudent" id="check_category_05" name="targetUserType">'
		, '					<strong class="name">비회원 학생</strong>'
		, '				</label>'
		, '			</div>'
		, '		</div>'


		, '		<!-- 상단 셀렉트 박스에서 이름 검새 후 메세지 보내기 선택하면 나오는 영역 시작 -->'
		, '		<div class="form-group" data-target-form="Y" data-target-type="search" style="display:none;">'
		, '			<label class="col-sm-1 control-label">검색하기</label>'
		, '			<div class="col-sm-11">'
		, '				<div class="input-group">'
		, '					<input type="text" name="searchText" class="form-control" placeholder="학생 및 선생님 (아이디,이름) 검색"> <span class="input-group-btn"> <button type="button" class="btn btn-primary" data-act="messageTargetSearch">검색하기</button></span>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '		<!-- 검색하기 버튼 클릭시 결과 나타남. 클릭 전에는 나타나지 않음 -->'
		, '		<div class="form-group" data-target-form="Y" data-target-type="search" data-view="searchResult" style="display:none;">'
		, '			<label class="col-sm-1 control-label">검색결과</label>'
		, '			<div class="col-sm-11">'
		, '				<ul class="search_name_list"></ul>'
		, '			</div>'
		, '		</div>'
		, '		<!-- 상단 셀렉트 박스에서 이름 검새 후 메세지 보내기 선택하면 나오는 영역 끝 -->'
		, '		<div class="form-group" data-target-form="Y" data-target-type="search" data-view="searchTarget" style="display:none;">'
		, '			<label class="col-sm-1 control-label">선택자</label>'
		, '			<div class="col-sm-11">'
		, '				<ul class="chosen_select"></ul>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">내용</label>'
		, '			<div class="col-sm-11">'
		//, '				<textarea cols="140" rows="10" name="messageContent" class="form-control"></textarea>'
		, '				<textarea cols="140" rows="10" name="messageContent" class="form-control" data-lib="editor"></textarea>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">파일첨부</label>'
		, '			<div class="col-sm-11">'
		, '				<span class="btn btn-primary">파일 업로드</span>'
		, '				<input type="file" class="input_file" data-act="file_upload" multiple>'
		, '			</div>'
		, '		</div>'
		, '		<div class="form-group">'
		, '			<label class="col-sm-1 control-label">첨부파일</label>'
		, '			<div class="col-sm-11">'
		, '				<p>'
		, '					<span><i class="fa fa-paperclip"></i> 0개파일 첨부</span>'
		, '				</p>'
		, '				<div class="attachment">'
		, '					<div class="clearfix"></div>'
		, '				</div>'
		, '			</div>'
		, '		</div>'
		, '	</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" class="btn btn-default" data-act="cancel">취소하기</button>'
		, '		<button type="button" class="btn btn-primary" data-act="messageSend">등록하기</button>'
		, '	</div>'
	].join('')
};

/*	선생님	*/
hakwonTmpl.teacher = {
	/*	학원 추가 등록	*/
	hakwonRegist : [
		'<div class="middle-box">'
		, '	<p>학원코드로 검색한 후 학원추가 버튼으로 등록하세요.</p>'
		, '		<div class="input-group">'
		, '			<input type="text" name="hakwonCode" class="form-control" placeholder="학원코드로 검색">'
		, '			<span class="input-group-btn"><button type="button" data-act="search" class="btn btn-primary">검색</button></span>'
		, '		</div>'
		, '	<div class="feed-activity-list m-t-xl search_result">'
		, '		<h2>검색결과</h2>'
		, '		<div class="feed-element"></div>'
		, '	</div>'
		, '</div>'
	].join('')
	/*	학원 추가 등록 검색 결과	*/
	, hakwonRegistSearchRow : [
		'	<a href="#" onclick="return false;" class="pull-left">'
		, '		<img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(hakwonInfo.logo_file_path, "hakwon")}}">'
		, '	</a>'
		, '	<div class="media-body">'
		, '{{if isNull(hakwonInfo.member_approved_yn) }}'
		, '		<div class="pull-right"><button type="button" data-act="hakwonRegist" data-hakwon-no="{{= hakwonInfo.hakwon_no}}" class="btn btn-primary btn-outline">추가</button></div>'
		, '{{/if}}'
		, '{{if hakwonInfo.member_approved_yn == "Y" }}'
		, '		<div class="pull-right">이미 등록된 학원 입니다.</div>'
		, '{{/if}}'
		, '{{if hakwonInfo.member_approved_yn == "N" }}'
		, '		<div class="pull-right"><button type="button" data-act="hakwonReqCancel" data-hakwon-no="{{= hakwonInfo.hakwon_no}}" class="btn btn-primary btn-outline">요청취소</button></div>'
		, '{{/if}}'
		, '		<strong>{{= hakwonInfo.hakwon_name}}</strong><br>'
		, '		{{= hakwonInfo.old_sido}} / {{= hakwonInfo.hakwon_cate_name}} / {{= hakwonInfo.tel_no_1}}'
		, '	</div>'
	].join('')
};

/*	셋팅	*/
hakwonTmpl.setting = {
	/*	매니저	*/
	manager : {
		/*	검색된 매니저	*/
		searchManager : [
			'	{{each(i, loopManager) dataList}}'
			, '	<div class="contact-box class_box">'
			, '		<img src="{{= hakwonCommon.createFilePullPath(loopManager.photo_file_path)}}" class="img-circle m-t-xs img-responsive" alt="">'
			, '		<h3 class="title_name">{{= loopManager.user_name}}</h3>'
			, '		<button type="button" data-act="registManager" data-manager-no="{{= loopManager.manager_no}}" class="btn btn-primary">매니저 선택</button>'
			, '	</div>'
			, '{{/each}}'
		].join('')
		/*	등록된 매니저	*/
		, registManager : [
			'	<div class="contact-box class_box">'
			, '		<img src="{{= hakwonCommon.createFilePullPath(managerInfo.photo_file_path)}}" class="img-circle m-t-xs img-responsive" alt="">'
			, '		<h3 class="title_name">{{= managerInfo.user_name}}</h3>'
			, '		<p class="contact-box-info">'
			, '			매니저 번호 : {{= managerInfo.manager_no}}/ 연락처 : {{= managerInfo.tel1_no}}'
			, '		</p>'
			, '	</div>'
		].join('')
	}
	/*	공지 카테고리	*/
	, noticeCategory : {
		form : [
			'<div class="ibox m">'
			, '	<div class="ibox-content form-horizontal" data-view="noticeCateList"></div>'
			, '	<div class="ibox-content text-right">'
			, '		<button type="button" data-act="newCate" class="btn btn-warning">새 카테고리 추가</button>'
			, '	</div>'
			, '</div>'
		].join('')
		, listCateRow : [
			'	{{each(i, loopCate) dataList}}'
			, '		<div class="form-group" data-id="{{= loopCate.cateNo}}">'
			, '			<label class="col-sm-1 control-label" for="category_name_01">카테고리명</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="text" name="cate_name" value="{{= loopCate.cateName}}" class="form-control" id="category_name_01">'
			, '			</div>'
			, '			<label class="col-sm-1 control-label" for="category_name_02">노출 순서</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="text" name="cate_order" value="{{= loopCate.cateOrder}}" onkeydown="commProto.onlyNumber(event)" onkeypress="commProto.onlyNumber(event)" class="form-control" id="category_name_02">'
			, '			</div>'
			, '			<div class="col-sm-2">'
			, '				<button type="button" data-act="rowModify" class="btn btn-default">수정</button>'
			, '				<button type="button" data-act="rowDelete" class="btn btn-default">삭제</button>'
			, '			</div>'
			, '		</div>'
			, '	{{/each}}'
		].join('')
		, newCateRow : [
			, '		<div class="form-group" data-id="new">'
			, '			<label class="col-sm-1 control-label" for="category_name_01">신규 카테고리명</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="text" name="cate_name" class="form-control" id="category_name_01">'
			, '			</div>'
			, '			<label class="col-sm-1 control-label" for="category_name_02">노출 순서</label>'
			, '			<div class="col-sm-4">'
			, '				<input type="text" name="cate_order" class="form-control" onkeydown="commProto.onlyNumber(event)" onkeypress="commProto.onlyNumber(event)" id="category_name_02">'
			, '			</div>'
			, '			<div class="col-sm-2">'
			, '				<button type="button" data-act="newSave" class="btn btn-default">저장</button>'
			, '				<button type="button" data-act="newCancel" class="btn btn-default">취소</button>'
			, '			</div>'
			, '		</div>'
		].join('')
	}
};


/*	관리자 문의	*/
hakwonTmpl.adminQuestion = {
	listForm : [
		'<div class="ibox m" data-view="data-div">'
		, '	<div class="ibox-content">'
		, '		<table class="table table-hover table_link">'
		, '			<thead>'
		, '				<tr>'
		, '					<th>번호</th>'
		, '					<th>제목</th>'
		, '					<th>등록일</th>'
		, '				</tr>'
		, '			</thead>'
		, '			<tbody>'
		, '			</tbody>'
		, '		</table>'
		, '		<div data-view="page-nav" class="text-center m-b-xl m-t-xl"></div>'
		, '		<div class="text-right">'
		, '			<button type="button" class="btn btn-primary" data-act="regist">관리자 문의 등록</button>'
		, '		</div>'
		, '	</div>'
		, '</div>'
	].join('')
	, listRow : [
		'{{each(i, loopNotice) noticeList}}'
		, '	<tr>'
		, '		<td>{{= loopNotice.notice_no}}</td>'
		, '		<td>'
		, '			<a href="'+PageUrl.common.adminQuestionView+'?notice_no={{= loopNotice.notice_no}}&hakwon_no={{= hakwonInfo.hakwon_no}}">{{= loopNotice.title}}</a>'
		, '		</td>'
		, '		<td><span>{{= loopNotice.reg_date}}</span></td>'
		, '	</tr>'
		, '{{/each}}'
	].join('')
	, listNoData : [
		'	<tr>'
		, '		<td colspan="3" class="box_nodata">등록된 관리자 문의가 없습니다.</td>'
		, '	</tr>'
	].join('')
	, viewForm : [
		'<div class="ibox m" data-view="data-view">'+hakwonTmpl.common.init+'</div>'
	].join('')
	, viewData : [
		'<div class="ibox m">'
		, '	<div class="ibox-title">'
		, '		<h2>{{= noticeDetail.title}} <small>등록일 : {{= noticeDetail.reg_date}}</small></h2>'
		, '	</div>'
		, '	<div class="ibox-content">{{html noticeDetail.content}}</div>'
		, '	<div class="ibox-content text-right">'
		, '		<button type="button" data-act="noticeDel" class="btn btn-default" ng-if="checkAuthType()">삭제하기</button>'
		, '		<button type="button" data-act="noticeEdit" class="btn btn-werning" ng-if="checkAuthType()">수정하기</button>'
		, '		<button type="button" data-act="list" class="btn btn-primary">목록으로</button>'
		, '	</div>'

		, '<div class="ibox-content m-t">'
		, '	<!-- 댓글 쓰기 시작 -->'
		, '	<div class="comment_write has-success">'
		, '		<form action="">'
		, '			<textarea rows="3" cols="30" name="replyContent" class="form-control"></textarea>'
		, '			<button type="button" class="btn btn-primary btn-lg m-b" data-act="replyWrite">댓글입력</button>'
		, '		</form>'
		, '	</div>'
		, '	<!-- 댓글 쓰기 끝 -->'
		, '</div>'

		, '<!-- 댓글 리스트 -->'
		, '<div class="comment_list"></div>'
		, '</div>'
	].join('')
	/*	리플	*/
	, replyRow : [
		'	{{each(i, loopReply) replyList }}'
		, '		<div class="feed-element" data-reply-no="{{= loopReply.reply_no}}">'
		, '			<span class="pull-left"><img alt="image" src="{{= hakwonCommon.createFilePullPath(loopReply.photo_file_path, "photo")}}" class="img-circle"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopReply.reg_date_long }}</span></small>'
		, '				<p><span class="badge .badge-plain">{{= loopReply.user_type_name }}</span> <strong>{{= loopReply.reg_user_name }}</strong> {{= loopReply.reg_user_id }}</p>'
		, '				<p class="message_body_text">{{html loopReply.reply_content}}</p>'
		, '			</div>'
		, '		</div>'
		, '	{{/each}}'
	].join('')
};

/**
 * 가이드
 */
hakwonTmpl.guide = {
	map : [
		'<div class="ibox">'
		, '	<div class="ibox-title">1. 다음지도에서 주소를 찾은 후 <strong>지도공유</strong> 에서  <strong>지도퍼가기</strong> 클릭 </div>'
		, '	<div class="ibox-content">'
		, '		<a href="/assets/img/guide/05.gif" target="_blank"><img src="/assets/img/guide/05.gif" class="img-responsive"></a>'
		, '	</div>'
		, '</div>'
		, '<div class="ibox">'
		, '	<div class="ibox-title">2. 지도 크기를 640 x 300 으로 조절</div>'
		, '	<div class="ibox-content">'
		, '		<a href="/assets/img/guide/06.gif" target="_blank"><img src="/assets/img/guide/06.gif" class="img-responsive"></a>'
		, '	</div>'
		, '</div>'
		, '<div class="ibox">'
		, '	<div class="ibox-title">3. 소스 생성하기부분에서 이미지 지도 선택후 소스 복사</div>'
		, '	<div class="ibox-content">'
		, '		<a href="/assets/img/guide/07.gif" target="_blank"><img src="/assets/img/guide/07.gif" class="img-responsive"></a>'
		, '	</div>'
		, '</div>'
		, '<div class="ibox">'
		, '	<div class="ibox-title">4. 학원밴드 로그인 후 우측 하단의 학원소개 클릭</div>'
		, '	<div class="ibox-content">'
		, '		<a href="/assets/img/guide/01.gif" target="_blank"><img src="/assets/img/guide/01.gif" class="img-responsive"></a>'
		, '	</div>'
		, '</div>'
		, '<div class="ibox">'
		, '	<div class="ibox-title">5. 학원소개 수정 클릭</div>'
		, '	<div class="ibox-content">'
		, '		<a href="/assets/img/guide/02.gif" target="_blank"><img src="/assets/img/guide/02.gif" class="img-responsive"></a>'
		, '	</div>'
		, '</div>'
		, '<div class="ibox">'
		, '	<div class="ibox-title">6. 지도 첨부 란에 복사해온 소스 붙여넣기</div>'
		, '	<div class="ibox-content">'
		, '		<a href="/assets/img/guide/03.gif" target="_blank"><img src="/assets/img/guide/03.gif" class="img-responsive"></a>'
		, '	</div>'
		, '</div>'
		, '<div class="ibox">'
		, '	<div class="ibox-title">7. 지도 삽입 버튼 클릭 후 하단의 등록하기 버튼으로 수정 완료</div>'
		, '	<div class="ibox-content">'
		, '		<a href="/assets/img/guide/04.gif" target="_blank"><img src="/assets/img/guide/04.gif" class="img-responsive"></a>'
		, '	</div>'
		, '</div>'
	].join('')
	, youtube : [
	].join('')
};

/*	메세지 뷰 폼	*/
hakwonTmpl.messageView = {
	/*	보낸 메세지 싱글 리스트 폼	*/
	sendMessageSingleListForm : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content message_page" data-view="data-view">'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	보낸 메세지 그룹 리스트 폼	*/
	, sendMessageGroupListForm : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-content message_page" data-view="data-view">'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	받은 메세지 리스트 폼	*/
	, receiveMessageListForm : [
		'<div class="ibox float-e-margins">'
		, '	<div class="ibox-title" style="display:none;" data-view="receiveMessageListTitle"></div>'
		, '	<div class="ibox-content message_page" data-view="data-view">'
		, '	</div>'
		, '	<div class="text-center m-b-xl m-t-xl" data-view="pagination"></div>'
		, '</div>'
	].join('')
	/*	보낸 메세지 그룹 리스트 row	*/
	, sendMessageGroupListRow : [
		'{{each(i, loopData) dataList}}'
		, '	<!-- 메세지 단위 시작 -->'
		, '	<div class="feed-element message_box">'
		, '		<a href="{{= PageUrl.message.sendGroupMessageDetail+"?hakwon_no="+hakwonInfo.hakwon_no+"&messageNo="+loopData.message_no}}" class="media-body">'
		, '		<div class="media-body">'
		, '			<!-- 메세지 텍스트 시작 -->'
		, '			<span class="message_list_text">'
		, '			{{if loopData.reservation_yn == "Y" && !loopData.reservation_send_date }}'
		, '			[예약]'
		, '			{{/if}}'
		, '				{{= loopData.title}}'
		, '			</span>'
		, '			<!-- 메세지 텍스트 끝 -->'
		, '			{{if loopData.reservation_yn == "Y" && !loopData.reservation_send_date }}'
		, '			<small class="pull-right">예약일 : <span class="text-muted">{{= loopData.reservation_date}}</span></small>'
		, '			{{else}}'
		, '			<small class="pull-right"><span class="text-muted">{{= loopData.send_date}}</span></small>'
		, '			{{/if}}'
		, '			<!-- 첨부 파일 영역 시작 -->'
		, '			<span class="m-t">'
		, '				<span><i class="fa fa-paperclip"></i> {{= loopData.file_count}} 개파일 첨부</span>'
		, '			</p>'
		, '		</div>'
		, '		</a>'
		, '	</div>'
		, '{{/each}}'
		, '	<!-- 메세지 단위 끝 -->'
	].join('')
	/*	보낸 메세지 개별 리스트 row	*/
	, sendMessageSingleListRow : [
		'{{each(i, loopData) dataList}}'
		, '	<!-- 메세지 단위 시작 -->'
		, '	<div class="feed-element message_box">'
		, '		<a href="{{= PageUrl.message.sendSingleMessageDetail+"?hakwon_no="+hakwonInfo.hakwon_no+"&receiveNo="+loopData.receive_no}}">'
		, '			<span class="pull-left"><img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopData.receive_user_info.user_photo_path, "photo", true)}}"></span>'
		, '			<div class="media-body">'
		, '			{{if loopData.reservation_yn == "Y" && !loopData.reservation_send_date }}'
		, '				<small class="pull-right">예약일 : <span class="text-muted">{{= loopData.reservation_date}}</span></small>'
		, '			{{else}}'
		, '				<small class="pull-right"><span class="text-muted">{{= loopData.send_date}}</span> / {{= loopData.receive_date?"읽음("+loopData.receive_date+")":"읽기전"}}</small>'
		, '			{{/if}}'
		, '				<p>'
		, '					<span class="badge .badge-plain">{{= loopData.receive_user_info.user_type_name}}</span> '
		, '					<strong>'
		, '						{{if loopData.reservation_yn == "Y" && !loopData.reservation_send_date }}'
		, '						[예약]'
		, '						{{/if}}'
		, '					{{= loopData.receive_user_info.user_name}} / {{= loopData.title}}'
		, '					</strong>'
		, '					 ({{= loopData.reply_count}})'
		, '				</p>'
		, '				<!-- 첨부 파일 영역 시작 -->'
		, '				<p><span><i class="fa fa-paperclip"></i> {{= loopData.file_count}} 개파일 첨부</span></p>'
		, '				<div class="attachment">'
		, '				</div>'
		, '				<!-- 첨부 파일 영역 끝 -->'
		, '				<!-- 댓글 영역 시작 -->'
		, '				<div class="comment_box">'
		, '					<div class="comment_count text-right"><i class="fa fa-comment"></i> {{= loopData.reply_count}}개의 댓글</div>'
		, '				</div>'
		, '				<!-- 댓글 영역 끝 -->'
		, '			</div>'
		, '		</a>'
		, '	</div>'
		, '{{/each}}'
		, '	<!-- 메세지 단위 끝 -->'
	].join('')
	/*	받은 메세지 리스트 row	*/
	, receiveMessageListRow : [
		'{{each(i, loopData) dataList}}'
		, '	<!-- 메세지 단위 시작 -->'
		, '	<div class="feed-element message_box">'
		, '		<a href="{{= PageUrl.message.receiveMessageDetail+"?hakwon_no="+hakwonInfo.hakwon_no+"&receiveNo="+loopData.receive_no}}">'
		, '			<span class="pull-left"><img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopData.send_user_info.user_photo_path, "photo", true)}}"></span>'
		, '			<div class="media-body">'
		, '				<small class="pull-right"><span class="text-muted">{{= loopData.send_date}}</span> / {{= loopData.receive_date?"읽음":"읽기전"}}</small>'
		, '				<p>'
		, '					<span class="badge .badge-plain">{{= loopData.send_user_info.user_type_name}}</span> '
		, '					<strong>{{= loopData.send_user_info.user_name}} / {{= loopData.title}}</strong> ({{= loopData.reply_count}})'
		, '				</p>'
		, '				<!-- 첨부 파일 영역 시작 -->'
		, '				<p><span><i class="fa fa-paperclip"></i> {{= loopData.file_count}} 개파일 첨부</span></p>'
		, '				<div class="attachment">'
		, '				</div>'
		, '				<!-- 첨부 파일 영역 끝 -->'
		, '				<!-- 댓글 영역 시작 -->'
		, '				<div class="comment_box">'
		, '					<div class="comment_count text-right"><i class="fa fa-comment"></i> {{= loopData.reply_count}}개의 댓글</div>'
		, '				</div>'
		, '				<!-- 댓글 영역 끝 -->'
		, '			</div>'
		, '		</a>'
		, '	</div>'
		, '{{/each}}'
		, '	<!-- 메세지 단위 끝 -->'
	].join('')
	/*	보낸 그룹 메세지 상세	*/
	, viewForm : [
		'<div class="ibox float-e-margins" data-view="data-view">'+hakwonTmpl.common.init+'</div>'
	].join('')
	/*	messageDetail, fileList*/
	, sendMessageGroupView : [
		'	<div class="ibox-title"><h2>내용</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 메세지 텍스트 시작 -->'
		, '		<p class="message_body_text">{{html messageDetail.content}}</p>'
		, '		<!-- 메세지 텍스트 끝 -->'
		, '		<small class="pull-right"><span class="text-muted">{{= messageDetail.send_date}}</span></small>'
		, '	</div>'
		, '	{{if fileList && fileList.length > 0}}'
		, '	<div class="ibox-title m-t"><h2>첨부파일</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 첨부 파일 영역 시작 -->'
		, '		<p class="m-t-xl">'
		, '			<span><i class="fa fa-paperclip"></i> {{= fileList.length}} 개파일 첨부</span>'
		, '		</p>'
		, '		<div class="attachment">'
		, '	{{each(i, loopFile) fileList}}'
		, '			<div class="file-box">'
		, '				<div class="file">'
		, '					<a href="{{= DefaultInfo.downPath+loopFile.file_path}}">'
		, '						<span class="corner"></span>'
		, '		{{if loopFile.image_yn == "Y" }}'
		, '						<div class="image">'
		, '							<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(loopFile.file_path, "attach", true)}}">'
		, '						</div>'
		, '		{{/if}}'
		, '		{{if loopFile.image_yn == "N" }}'
		, '						<div class="icon">'
		, '							<i class="fa fa-file"></i>'
		, '						</div>'
		, '		{{/if}}'
		, '						<div class="file-name">'
		, '							<p>{{= loopFile.file_name}}</p>'
		, '						</div>'
		, '					</a>'
		, '				</div>'
		, '			</div>'
		, '	{{/each}}'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '		<!-- 첨부 파일 영역 끝 -->'
		, '	</div>'
		, '	{{/if}}'
		, '	<div class="ibox-title m-t">'
		, '		<h2>받은대상</h2>'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '	{{if messageDetail.message_type == "class" }}'
		, '		<ul>'
		, '			<li>타입 : 반 대상</li>'
		, '			<li>반 리스트 : {{= messageTarget.targetClassStr}}</li>'
		, '			<li>사용자 그룹 : {{= messageTarget.userTypeListStr}}</li>'
		, '		</ul>'
		, '	{{/if}}'
		, '	{{if messageDetail.message_type == "userGroup" }}'
		, '		<ul>'
		, '			<li>타입 : 사용자 그룹</li>'
		, '			<li>사용자 그룹 : {{= messageTarget.userTypeListStr}}</li>'
		, '		</ul>'
		, '	{{/if}}'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '		<!-- 사용자일 경우 -->'
		, '		<ul class="chosen_select">'
		, '	{{each(i, loopUser) receiveUserList}}'
		, '			<li><a href="{{= hakwonCommon.userDetailLink(loopUser.user_type, loopUser.receive_user_no)}}" title="{{= loopUser.receive_date}}"><img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopUser.user_photo_path, "photo", true)}}" alt="{{= loopUser.user_name}}" width="30" height="30"> {{= loopUser.user_name + "(" + loopUser.user_type_name + ") "+(loopUser.receive_date?"읽음":"안읽음")}}</a></li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '	<div class="ibox-content text-right m-t">'
		, '	{{if messageDetail.reservation_yn == "Y" && !messageDetail.reservation_send_date }}'
		, '		<button class="btn btn-default" type="button" data-act="reservationMsgDelete" title="예약메세지 삭제">예약메세지 삭제</button>'
		, '	{{/if}}'
		, '		<button class="btn btn-default" type="button" data-act="goList" title="목록으로">목록으로</button>'
		, '	</div>'
	].join('')
	/*	messageDetail, replyList, fileList*/
	, sendMessageSingleView : [
		'	<div class="ibox-title">'
		, '		<h2 class="m-r">받은사람 : </h2>'
		, '		<img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(messageDetail.receive_user_info.user_photo_path, "photo", true)}}" width="30" height="30">'
		, '		<span class="badge .badge-plain">{{= messageDetail.receive_user_info.user_type_name}}</span> {{= messageDetail.receive_user_info.user_name}}'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '		<!-- 메세지 텍스트 시작 -->'
		, '		<p class="message_body_text">{{html messageDetail.content}}</p>'
		, '		<!-- 메세지 텍스트 끝 -->'
		, '		<small class="pull-right"><span class="text-muted">{{= messageDetail.send_date}}</span></small>'
		, '	</div>'
		, '	{{if fileList && fileList.length > 0}}'
		, '	<div class="ibox-title m-t"><h2>첨부파일</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 첨부 파일 영역 시작 -->'
		, '		<p class="m-t-xl">'
		, '			<span><i class="fa fa-paperclip"></i> {{= fileList.length}} 개파일 첨부</span>'
		, '		</p>'
		, '		<div class="attachment">'
		, '	{{each(i, loopFile) fileList}}'
		, '			<div class="file-box">'
		, '				<div class="file">'
		, '					<a href="{{= DefaultInfo.downPath+loopFile.file_path}}">'
		, '						<span class="corner"></span>'
		, '		{{if loopFile.image_yn == "Y" }}'
		, '						<div class="image">'
		, '							<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(loopFile.file_path, "attach", true)}}">'
		, '						</div>'
		, '		{{/if}}'
		, '		{{if loopFile.image_yn == "N" }}'
		, '						<div class="icon">'
		, '							<i class="fa fa-file"></i>'
		, '						</div>'
		, '		{{/if}}'
		, '						<div class="file-name">'
		, '							<p>{{= loopFile.file_name}}</p>'
		, '						</div>'
		, '					</a>'
		, '				</div>'
		, '			</div>'
		, '	{{/each}}'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '		<!-- 첨부 파일 영역 끝 -->'
		, '	</div>'
		, '	{{/if}}'
		, '	{{if messageDetail.message_type == "search" }}'
		, '	<div class="ibox-title m-t">'
		, '		<h2>받은대상</h2>'
		, '	</div>'
		, '	<div class="ibox-content">'
		, '		<!-- 사용자일 경우 -->'
		, '		<ul class="chosen_select">'
		, '	{{each(i, loopUser) messageTarget.userList}}'
		, '			<li><a href="{{= hakwonCommon.userDetailLink(loopUser.user_type, loopUser.receive_user_no)}}"><img class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopUser.user_photo_path, "photo", true)}}" alt="{{= loopUser.user_name}}" width="30" height="30"> {{= loopUser.user_name + "(" + loopUser.user_type_name + ")"}}</a></li>'
		, '	{{/each}}'
		, '		</ul>'
		, '	</div>'
		, '	{{/if}}'
		, '	<div class="ibox-content text-right m-t">'
		, '	{{if messageDetail.reservation_yn == "Y" && !messageDetail.reservation_send_date }}'
		, '		<button class="btn btn-default" type="button" data-message-no="{{= messageDetail.message_no}}" data-act="reservationMsgDelete" title="예약메세지 삭제">예약메세지 삭제</button>'
		, '	{{/if}}'
		, '		<button class="btn btn-default" data-act="goList" type="button" title="목록으로">목록으로</button>'
		, '	</div>'
		, '	<div class="ibox-title text-right m-t">'
		, '		<strong data-view="comment_count">0개</strong>의 댓글'
		, '	</div>'
		, '	<div class="comment_list" data-view="comment_list"></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 댓글 쓰기 시작 -->'
		, '		<div class="comment_write has-success">'
		, '			<textarea rows="3" name="replyContent" cols="30" class="form-control"></textarea>'
		, '			<button type="button" data-act="replyWrite" class="btn btn-primary btn-lg m-b">댓글입력</button>'
		, '		</div>'
		, '		<!-- 댓글 쓰기 끝 -->'
		, '	</div>'
	].join('')
	/*	받은 메세지 상세	*/
	, receiveMessageView : [
		, '	<div class="ibox-title">'
		, '		<h2 class="m-r">보낸사람 : </h2>'
		, '		<img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(messageDetail.send_user_info.user_photo_path, "photo", true)}}" width="30" height="30">'
		, '		<span class="badge .badge-plain">{{= messageDetail.send_user_info.user_type_name}}</span> {{= messageDetail.send_user_info.user_name}}'
		, '	</div>'
		, '	<div class="ibox-content message_page">'
		, '		<!-- 메세지 텍스트 시작 -->'
		, '		<p class="message_body_text">{{html messageDetail.content}}</p>'
		, '		<!-- 메세지 텍스트 끝 -->'
		, '		<small class="pull-right"><span class="text-muted">{{= messageDetail.send_date}}</span></small>'
		, '	</div>'
		, '	{{if fileList && fileList.length > 0}}'
		, '	<div class="ibox-title m-t"><h2>첨부파일</h2></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 첨부 파일 영역 시작 -->'
		, '		<p class="m-t-xl">'
		, '			<span><i class="fa fa-paperclip"></i> {{= fileList.length}} 개파일 첨부</span>'
		, '		</p>'
		, '		<div class="attachment">'
		, '	{{each(i, loopFile) fileList}}'
		, '			<div class="file-box">'
		, '				<div class="file">'
		, '					<a href="{{= DefaultInfo.downPath+loopFile.file_path}}">'
		, '						<span class="corner"></span>'
		, '		{{if loopFile.image_yn == "Y" }}'
		, '						<div class="image">'
		, '							<img alt="image" class="img-responsive" src="{{= hakwonCommon.createFilePullPath(loopFile.file_path, "attach", true)}}">'
		, '						</div>'
		, '		{{/if}}'
		, '		{{if loopFile.image_yn == "N" }}'
		, '						<div class="icon">'
		, '							<i class="fa fa-file"></i>'
		, '						</div>'
		, '		{{/if}}'
		, '						<div class="file-name">'
		, '							<p>{{= loopFile.file_name}}</p>'
		, '						</div>'
		, '					</a>'
		, '				</div>'
		, '			</div>'
		, '	{{/each}}'
		, '			<div class="clearfix"></div>'
		, '		</div>'
		, '		<!-- 첨부 파일 영역 끝 -->'
		, '	</div>'
		, '	{{/if}}'
		, '	<div class="ibox-content text-right m-t">'
		, '		<button class="btn btn-default" data-act="goList" type="button" title="목록으로">목록으로</button>'
		, '	</div>'
		, '	{{if messageDetail.group_yn == "N" }}'
		, '	<div class="ibox-title text-right m-t">'
		, '		<strong data-view="comment_count">0개</strong>의 댓글'
		, '	</div>'
		, '	<div class="comment_list" data-view="comment_list"></div>'
		, '	<div class="ibox-content">'
		, '		<!-- 댓글 쓰기 시작 -->'
		, '		<div class="comment_write has-success">'
		, '			<textarea rows="3" name="replyContent" cols="30" class="form-control"></textarea>'
		, '			<button type="button" data-act="replyWrite" class="btn btn-primary btn-lg m-b">댓글입력</button>'
		, '		</div>'
		, '		<!-- 댓글 쓰기 끝 -->'
		, '	</div>'
		, '	{{/if}}'
	].join('')
	/*	리플	*/
	, replyRow : [
		'	{{each(i, loopReply) replyList }}'
		, '		<div class="comment_box {{= userAuth.userNo==loopReply.reg_user_no?"my_comment":""}}" data-type="reply" data-reply-no="{{= loopReply.reply_no}}">'
		, '			<span class="profile_img"><img alt="image" class="img-circle" src="{{= hakwonCommon.createFilePullPath(loopReply.photo_file_path, "photo", true)}}"></span>'
		, '			<div class="arrow"></div>'
		, '			<div class="media-body">'
		, '				<p><span class="badge .badge-plain">{{= loopReply.user_type_name }}</span> <strong>{{= loopReply.reg_user_name }}</strong> / {{= loopReply.reg_user_id }}</p>'
		, '				<p class="message_body_text">{{html loopReply.reply_content}}'
		, '					<button class="btn btn-default btn-circle btn_x" style="{{= userAuth.userNo==loopReply.reg_user_no?"":"display:none;"}}" type="button" data-reply-no="{{= loopReply.reply_no}}"><i class="fa fa-times"></i></button>'
		, '				</p>'
		, '				<small class="time_text"><span class="text-muted">{{= loopReply.reg_date_long }}</span></small>'
		, '			</div>'
		, '		</div>'

//		, '		<div class="feed-element {{= userAuth.userNo==loopReply.reg_user_no?"active":""}}" data-type="reply" data-reply-no="{{= loopReply.reply_no}}">'
//		, '			<span class="pull-left"><img alt="image" src="{{= hakwonCommon.createFilePullPath(loopReply.photo_file_path, "photo", true)}}" class="img-circle"></span>'
//		, '			<div class="media-body">'
//		, '				<small class="pull-right"><span class="text-muted">{{= loopReply.reg_date_long }}</span></small>'
//		, '				<p><span class="badge .badge-plain">{{= loopReply.user_type_name }}</span> <strong>{{= loopReply.reg_user_name }}</strong> {{= loopReply.reg_user_id }}</p>'
//		, '				<p class="message_body_text">{{html loopReply.reply_content}}</p>'
//		, '			</div>'
//		, '		</div>'

		, '	{{/each}}'
	].join('')
	/*	첨부 파일	*/
	, attchFile : [
		'	<div class="file-box" data-file-no="{{= fileInfo.fileNo}}">'
		, '		<div class="file">'
		, '	{{if fileInfo.imageYn == "Y" }}'
		, '			<div class="image">'
		, '				<img alt="image" class="img-responsive" src="{{= HakwonConstant.FileServer.ATTATCH_DOMAIN+fileInfo.filePath}}">'
		, '			</div>'
		, '	{{/if}}'
		, '	{{if fileInfo.imageYn != "Y" }}'
		, '			<div class="icon"><i class="fa fa-file"></i></div>'
		, '	{{/if}}'
		, '			<div class="file-name">'
		, '				<p>{{= fileInfo.fileName}}</p>'
		, '			</div>'
		, '			<button type="button" class="btn btn-circle btn_file_del" title="삭제">X</button>'
		, '		</div>'
		, '	</div>'
	].join('')
};