var hakwonTmpl = {
	/*	초기화	*/
	init : [
/*
		'<section id="fn_12">'
		, '<img src="/assets/images/loading.gif">'
		, '</section>'
*/
		'<div class="sk-spinner sk-spinner-wave">'
		, '	<div class="sk-rect1"></div>'
		, '	<div class="sk-rect2"></div>'
		, '	<div class="sk-rect3"></div>'
		, '	<div class="sk-rect4"></div>'
		, '	<div class="sk-rect5"></div>'
		, '</div>'
	].join('')
	/*	헤더	*/
	, header : {
		/*	사용자 헤더	*/
		user : [
			'	<button type="button" data-act="leftMenu" class="btn_privacy icon_bg">개인정보</button>'
			, '	<h1>{{= headerTitle}}</h1>'
		].join('')
		/*	공통	*/
		, comm : [
			'<h1>{{= headerTitle}}</h1>'
		].join('')
		/*	학원	*/
		, hakwon : [
			'	<button type="button" data-act="leftMenu" class="btn_privacy icon_bg">개인정보</button>'
			, '	<h1><a href="#/hakwon/detail?hakwon_no={{= hakwonInfo.currentHakwon.hakwon_no}}">{{= headerTitle}}</a></h1>'
			, '	<button type="button" data-act="rightMenu" class="btn_info icon_bg">학원정보</button>'
		].join('')
		/*	왼쪽 메뉴	*/
		, leftMenu : [
			'	<div class="tit">'
			, '		<span>My Page</span>'
			, '		<a href="#" class="btn_close" onclick="return false;"><img src="/assets/images/btn_close.png" alt="닫기" width="15"></a>'
			, '	</div>'
			, '	<div class="my_info">'
			, '		<div class="about">'
			, '			<div class="img"><img src="{{= comm.userProfileImg(userAuth.userPhotoPath, true)}}" alt="{{= userAuth.userName}}" width="50" height="50"></div>'
			, '			<ul class="info">'
			, '				<li class="name">{{= userAuth.userName}}</li>'
			, '				<li class="id">{{= userAuth.userId}}</li>'
			, '				<li class="txt">{{= userAuth.userAge?userAuth.userAge+"세/":""}}{{= userAuth.userGender=="M"?"남":"여"}}/{{= userAuth.userType == HakwonConstant.UserType.STUDENT?"학생":"학부모"}}</li>'
			, '			</ul>'
			, '			<a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="myInfo" class="profile_edit">프로필 수정하기</a>'
			, '		</div>'
			, '	{{if userAuth.familyList.length > 0 }}'
			, '		<div class="{{= userAuth.userType == HakwonConstant.UserType.STUDENT?"child":"parent"}}">'
			, '{{each(i, loopUser) userAuth.familyList}}'
			, '		<div class="{{= userAuth.userType == HakwonConstant.UserType.STUDENT?"parent":"child"}}">'
			, '			<span class="tit">{{= userAuth.userType == HakwonConstant.UserType.STUDENT?"학부모":"학생"}}</span>'
			, '			<span class="img"><img src="{{= comm.userProfileImg(loopUser.photo_file_path)}}" alt="" width="25" height="25"></span>'
			, '			<span class="name">{{= loopUser.user_name}}</span>'
			, '		</div>'
			, '{{/each}}'
			, '		</div>'
			, '{{/if}}'
			, '		<ul class="mn_list">'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="userMain" class="mn_01">홈</a></li>'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="hakwonSearch" class="mn_02">학원검색</a></li>'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="eventJoin" class="mn_03">참여한 이벤트</a></li>'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="receiveMessageList" class="mn_04">메세지</a></li>'
//			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="receiveMessageList" class="mn_04">받은메세지</a></li>'
//			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="sendMessageList" class="mn_05">보낸메세지</a></li>'
//			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="messageWrite" class="mn_06">메세지 보내기</a></li>'

			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="attendanceList" class="mn_03">출결관리</a></li>'
			, '		</ul>'
			, '	</div>'
			, '	<div class="my_academy">'
			, '		<div class="join_info">'
			, '			가입된 학원'
			, '		</div>'
			, '		<ul class="mn_list" data-view="left_hakwon_list">'
			, '{{each(i, loopHakwon) hakwonInfo.hakwonList}}'
			, '			<li><a href="#" onclick="return false;" data-act="selectHakwonBtn" data-id="{{= loopHakwon.hakwon_no }}">{{= loopHakwon.hakwon_name }}</a></li>'
			, '{{/each}}'
			, '		</ul>'
			, '	</div>'
		].join('')
		/*	오른쪽 메뉴	*/
		, rightMenu : [
			'	<div class="tit">'
			, '		<span>학원정보</span>'
			, '		<a href="#" class="btn_close" onclick="return false;"><img src="/assets/images/btn_close.png" alt="닫기" width="15" /></a>'
			, '	</div>'
			, '	<div class="my_info">'
			, '	<div class="about">'
			, '		<div class="img"><img src="{{= comm.hakwonLogoImg(hakwonInfo.currentHakwon.file_path, true) }}" alt="{{= hakwonInfo.currentHakwon.hakwon_name }}" width="50" /></div>'
			, '			<ul class="info">'
			, '				<li class="name">{{= hakwonInfo.currentHakwon.hakwon_name }}</li>'
			, '				<li class="id">원장 : {{= hakwonInfo.currentHakwon.master_user_name }}</li>'
			, '				<li class="txt">{{= hakwonInfo.currentHakwon.all_addr_text }}</li>'
			, '				<li class="txt"><a href="tel:{{= hakwonInfo.currentHakwon.tel_no_1 }}">{{= hakwonInfo.currentHakwon.tel_no_1 }}</a></li>'
			, '			</ul>'
			, '		</div>'
			, '		<ul class="mn_list">'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="hakwonIntro" class="mn_01">학원소개</a></li>'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="eventList" class="mn_02">이벤트</a></li>'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="noticeList" class="mn_03">공지사항</a></li>'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="hakwonTeacher" class="mn_04">선생님</a></li>'
			, '	{{if isNull(userAuth.userNo) == false }}'
			, '			<li><a href="#" onclick="return false;" data-act="changeUrlBtn" data-url="hakwonMemberOut" class="mn_05">학원탈퇴</a></li>'
			, '	{{/if}}'
			, '		</ul>'
			, '	</div>'
			, '	{{if hakwonInfo.currentHakwon.classList && hakwonInfo.currentHakwon.classList.length > 0}}'
			, '	<div class="my_academy">'
			, '		<div class="join_info">'
			, '			나의 반'
			, '		</div>'
			, '		<ul class="mn_list" data-view="right_class_list">'
			, '{{each(i, loopClass) hakwonInfo.currentHakwon.classList}}'
			, '			<li><a href="#" onclick="return false;" data-act="selectClassBtn" data-id="{{= loopClass.class_no }}">{{= loopClass.class_title }}</a></li>'
			, '{{/each}}'
			, '		</ul>'
			, '	</div>'
			, '	{{/if}}'
		].join('')
	}
	/*	로그인	*/
	, login : [
		'<section>'
		, '	<div class="sec_title">'
		, '		<h2 class="tit hide">로그인</h2>'
		, '	</div>'

		, '	<div class="sec_login">'
		, '		<div class="tit">'
		, '			<img src="/assets/images/tit_band.gif" alt="HAKWONBAND" width="186" />'
		, '		</div>'
		, '		<div class="input">'
		, '			<input type="text" name="userId" title="아이디 입력" placeholder="아이디" class="id" value="" />'
		, '			<input type="password" name="userPass" title="비밀번호 입력" placeholder="비밀번호" class="pw" value="" />'
		, '		</div>'
		, '		<div class="chk" style="display:none;">'
		, '			<input type="checkbox" name="idSave" id="save_id" value="Y" /> <label for="save_id" class="mr_20">아이디 저장</label>'
		, '			<input type="checkbox" name="loginSave" id="login_keep" value="Y" /> <label for="login_keep">로그인 유지</label>'
		, '		</div>'

		, '		<!--버튼 영역-->'
		, '		<button type="button" data-act="login" class="btn btn_style_submit btn_bold btn_block mb_5">로그인</button>'
		, '		<button type="button" data-act="signUp" class="btn btn_style_info btn_bold btn_block">학원밴드 가입하기</button>'
		, '		<!--//버튼 영역-->'

		, '		<div class="txt">'
		, '			<a href="#findId">아이디나 비밀번호가<br>생각나지 않는다면?</a>'
		, '		</div>'
		, '	</div>'
		, '</section>'
	].join('')
	/*	광고 리스트	*/
	, advertList : [
		'<section>'
		, '	<h2 class="tit hide">광고</h2>'
		, '	<ul class="list_hakwon list_ad_hakwon" data-view="data-veiw"></ul>'
		, '</section>'
	].join('')
	, advertRow : [
		'	{{each(i, loopAdvert) blockList}}'
		, '	<li>'
		, '	{{if isNull(loopAdvert.redirect_url)}}'
		, '		<a href="#/hakwon/detail?hakwon_no={{= loopAdvert.hakwon_no}}" class="a_hakwon">'
		, '	{{/if}}'
		, '	{{if isNull(loopAdvert.redirect_url) == false}}'
		, '		<a href="{{= loopAdvert.redirect_url}}" target="_blank" class="a_hakwon">'
		, '	{{/if}}'
		, '			<img src="{{= comm.hakwonLogoImg(loopAdvert.logo_file_path, true)}}" alt="{{= loopAdvert.hakwon_name}}" title="{{= loopAdvert.hakwon_name}}" width="48" height="48" class="list_profile_img" />'
		, '			<ul class="list_contents">'
		, '				<li class="tit">{{= loopAdvert.hakwon_name}}</li>'
		, '				<li>종류 : {{= loopAdvert.hakwon_cate_name}}</li>'
		, '			</ul>'
		, '		</a>'
		, '	{{if loopAdvert.tel_no_1 }}'
		, '		<a href="tel:{{= loopAdvert.tel_no_1}}" class="a_tel">{{= loopAdvert.hakwon_name}} 학원 전화하기</a>'
		, ' {{/if}}'
		, '	</li>'
		, '{{/each}}'
		, '	{{each(i, loopAdvert) areaList}}'
		, '	{{if blockHakwonArray.indexOf(loopAdvert.hakwon_no) == -1 }}'
		, '	<li>'
		, '		<a href="#/hakwon/detail?hakwon_no={{= loopAdvert.hakwon_no}}" class="a_hakwon">'
		, '			<img src="{{= comm.hakwonLogoImg(loopAdvert.logo_file_path, true)}}" alt="{{= loopAdvert.hakwon_name}}" width="48" height="48" class="list_profile_img" />'
		, '			<ul class="list_contents">'
		, '				<li class="tit">{{= loopAdvert.hakwon_name}}</li>'
		, '				<li>종류 : {{= loopAdvert.hakwon_cate_name}}</li>'
		, '			</ul>'
		, '		</a>'
		, '		{{if loopAdvert.tel_no_1 }}'
		, '		<a href="tel:{{= loopAdvert.tel_no_1}}" class="a_tel">{{= loopAdvert.hakwon_name}} 학원 전화하기</a>'
		, ' 	{{/if}}'
		, ' {{/if}}'
		, '	</li>'
		, '{{/each}}'
/*
		, '	{{each(i, loopAdvert) commList}}'
		, '	<li>'
		, '		<a href="#/hakwon/detail?hakwon_no={{= loopAdvert.hakwon_no}}" class="a_hakwon">'
		, '			<img src="{{= comm.hakwonLogoImg(loopAdvert.logo_file_path, true)}}" alt="{{= loopAdvert.hakwon_name}}" width="48" height="48" class="list_profile_img" />'
		, '			<ul class="list_contents">'
		, '				<li class="tit">{{= loopAdvert.hakwon_name}}</li>'
		, '				<li>종류 : {{= loopAdvert.hakwon_cate_name}}</li>'
		, '			</ul>'
		, '		</a>'
		, '	{{if loopAdvert.tel_no_1 }}'
		, '		<a href="tel:{{= loopAdvert.tel_no_1}}" class="a_tel">{{= loopAdvert.hakwon_name}} 학원 전화하기</a>'
		, ' {{/if}}'
		, '	</li>'
		, '{{/each}}'
*/
	].join('')
	, loading : [
		'<div class="sk-spinner sk-spinner-wave">'
		, '	<div class="sk-rect1"></div>'
		, '	<div class="sk-rect2"></div>'
		, '	<div class="sk-rect3"></div>'
		, '	<div class="sk-rect4"></div>'
		, '	<div class="sk-rect5"></div>'
		, '</div>'
	].join('')
	/*	광고 블록	*/
	, advertBlock : [
		'<section class="line_n">'
		, '	<div class="sec_blk_02">'
		, '		<div class="sec_ad_area">'
		, '			<ul class="sec_ad_list">'
		, '				<li><img src="/assets/images/img_ad_01.gif" alt="" width="74" /></li>'
		, '				<li><img src="/assets/images/img_ad_02.gif" alt="" width="149" /></li>'
		, '				<li><img src="/assets/images/img_ad_03.gif" alt="" width="74" /></li>'
		, '				<li class="clear"><img src="/assets/images/img_ad_04.gif" alt="" width="224" /></li>'
		, '				<li><img src="/assets/images/img_ad_05.gif" alt="" width="74" /></li>'
		, '				<li class="clear"><img src="/assets/images/img_ad_06.gif" alt="" width="149" /></li>'
		, '				<li><img src="/assets/images/img_ad_07.gif" alt="" width="74" /></li>'
		, '				<li><a href="#/edvertiseList?hakwon_no={{= hakwonInfo.currentHakwon.hakwon_no}}"><img src="/assets/images/img_ed_btn.gif" alt="목록" width="74" /></a></li>'
		, '			</ul>'
		, '		</div>'
		, '	</div>'
		, '	</section>'
	].join('')
};